### ISSUE TITLE
Using "snapshot_identifier" with no "allocated_storage" gives an error

### ISSUE THREAD

**Issue by jcmcken** [terraform-aws-modules/terraform-aws-rds#109]
The ``allocated_storage`` variable is not required when using ``snapshot_identifier``, because the DB instance will use whatever storage size the snapshot used (the documentation also states this)

However, if you try to pass ``snapshot_identifier`` (but not ``allocated_storage``), you get a type error:

```
allocated_storage: cannot parse '' as int: strconv.ParseInt: parsing "": invalid syntax
```

Version info:

```
Terraform v0.11.11
+ provider.aws v2.3.0
```

**Comment by sdouche** [comment]
Hello,
I think the simplest solution is to:
- Add a default value to `allocated_storage`
- Select the variable if no snapshot is specified (`allocated_storage = var.snapshot_identifier != "" ? null : var.allocated_storage`).

What do you think @antonbabenko?

**Comment by aleon1220** [comment]
is happenning to me now and i am on terraform cloud. I believe the conflict is in
the duplicate use of the var.snapshot_identifier

Take a look at line 63 and 139

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L139

**Comment by aleon1220** [comment]
I think the majority of the community is tracking the issue at https://github.com/hashicorp/terraform-provider-aws/issues/17712

**Comment by bryantbiggs** [comment]
hi all, I believe this was an issue in the upstream AWS provider (https://github.com/hashicorp/terraform-provider-aws/pull/17755) - so closing for now. please feel free to respond or open a new issue if necessary
