### ISSUE TITLE
Is there a terraform 0.12 compatible version ?

### ISSUE THREAD

**Issue by mutt13y** [terraform-aws-modules/terraform-aws-rds#111]
Hello,
The module is not compatible with terraform 0.12-beta-1
Is anyone working on this?
If not would you be interested in making a branch ?

I think it only needs some minor syntax tweaks.
e.g.
```
Error: Inconsistent conditional result types

  on .terraform/modules/db/terraform-aws-modules-terraform-aws-rds-9b665b9/main.tf line 3, in locals:
   3:   enable_create_db_subnet_group = "${var.db_subnet_group_name == "" ? var.create_db_subnet_group : 0}"
    |----------------
    | var.create_db_subnet_group is true
    | var.db_subnet_group_name is "DB"

The true and false result expressions must have consistent types. The given
expressions are bool and number, respectively.

```

Thanks

**Comment by Vlaaaaaaad** [comment]
0.12 was released and this was not upgraded 😱

**Comment by antonbabenko** [comment]
I am planning to spend time and update most of the terraform-aws-modules during next week.

**Comment by wardviaene** [comment]
I've added a PR with the syntax updates for terraform 0.12 (https://github.com/terraform-aws-modules/terraform-aws-rds/pull/123)

**Comment by ekamil** [comment]
What's needed for #123 to be merged? Any more changes? Testing? (I'm also eagerly waiting for compatibility with 0.12 :) )

**Comment by italolelis** [comment]
Is there any extra work needed for #123 PR? I would be happy to help. I'm really looking forward for this changes.

**Comment by wardviaene** [comment]
You can test it and see if it works for you. We're running the PR-code in our terraform repos, but only use a small part of it

**Comment by antonbabenko** [comment]
If you are using Terraform 0.12, you can use [v2.0.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.0.0) of this module which has been just released.

**Comment by pythian-ciciliani** [comment]
Hi, I'm experiencing  an issue similar to the one that @Vlaaaaaaad reported.

**Terraform version:** 0.12.5
**AWS Provider version:** 2.27.0

Resource definition:
```hcl
resource "aws_rds_cluster_parameter_group" "cpg-west1-m" {
  name   = "cpg-medium"
  family = var.db_parameter_family
  provider    = "aws.uswest1"
  parameter = []
}

```


Error:
```
...

Error: Unsupported argument

  on aurora_mysql.tf line 18, in resource "aws_rds_cluster_parameter_group" "cpg-west1-m":
  18:   parameter = []

An argument named "parameter" is not expected here. Did you mean to define a
block of type "parameter"?
```
Is it possible to pass a list of parameters to this module or that option was deprecated?

Thanks!

**Comment by gabocic** [comment]
Hi, I'm experiencing  an issue similar to the one that @Vlaaaaaaad reported.

**Terraform version:** 0.12.5
**AWS Provider version:** 2.27.0

Resource definition:
```hcl
resource "aws_rds_cluster_parameter_group" "cpg-west1-m" {
  name   = "cpg-medium"
  family = var.db_parameter_family
  provider    = "aws.uswest1"
  parameter = []
}

```


Error:
```
...

Error: Unsupported argument

  on aurora_mysql.tf line 18, in resource "aws_rds_cluster_parameter_group" "cpg-west1-m":
  18:   parameter = []

An argument named "parameter" is not expected here. Did you mean to define a
block of type "parameter"?
```
Is it possible to pass a list of parameters to this module or that option was deprecated?

Thanks!
