### ISSUE TITLE
aws_db_instance - Add ca_cert_identifier as an output

### ISSUE THREAD

**Issue by SolidSly** [terraform-aws-modules/terraform-aws-rds#114]
Greetings,

AWS allow users to perform SSL connection to their RDS. So, the resource `aws_db_instance` for the provider aws has an output for that called `ca_cert_identifier`.
It should be should be an output for this RDS module.

**Comment by antonbabenko** [comment]
This is available since [v2.7.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.7.0) of this module.
