### ISSUE TITLE
performance_insights doesn't support yet

### ISSUE THREAD

**Issue by debu99** [terraform-aws-modules/terraform-aws-rds#119]
https://github.com/terraform-providers/terraform-provider-aws/pull/6453

Thanks

**Comment by analytically** [comment]
Released as part of 2.12

**Comment by hato221** [comment]
I've created PR for Terraform 0.11.X https://github.com/terraform-aws-modules/terraform-aws-rds/pull/132

**Comment by bryantbiggs** [comment]
closed in #139
