### ISSUE TITLE
Error when final_snapshot_identifier is not set

### ISSUE THREAD

**Issue by santi698** [terraform-aws-modules/terraform-aws-rds#12]
Hi, I've been using the module for a while but after the last version I'm getting an error after every `terraform plan` when `final_snapshot_identifier` is not set.
```
* module.db_instance.aws_db_instance.this: only alphanumeric characters and hyphens allowed in "final_snapshot_identifier"
```

It may be related to [this closed issue](https://github.com/hashicorp/terraform/issues/6786)

**Comment by antonbabenko** [comment]
Thanks for reporting this issue. The problem was that the default value (empty string) was not good enough even though it is not used. Fixed in v1.0.8
