### ISSUE TITLE
DB engine versions issues

### ISSUE THREAD

**Issue by audiolomb** [terraform-aws-modules/terraform-aws-rds#124]
I have a MSSQL deployment with RDS module for SQL.
The Engine Version was set to:

engine_version              = "14.00.3035.2.v1"

with the minor autoupgrade option to TRUE.
Now, few months have passed and the RDS instance in AWS has been upgraded automatically to version "14.00.3049.1.v1".

Today I made a change to the terraform code to create an additional instance, and Terraform Plan is returning this change for the DB above:

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.-----------
      engine_version: "14.00.3049.1.v1" => "~>14.00.3035.2.v1"

Obviously I do not want the db engine to be downgraded.
I haven't found a way to "ignore" the  parameter once the instance was created.

Am I missing something?

Thank you,
Claudio

**Comment by tiagocborg** [comment]
If you are using autopgrade = true, you should not tie the minor version. Just use `14.00` https://www.terraform.io/docs/providers/aws/r/db_instance.html#engine_version
