### ISSUE TITLE
RDS Postgres read replica as multi-az

### ISSUE THREAD

**Issue by ZakariaHili** [terraform-aws-modules/terraform-aws-rds#125]
I found an interesting article about using RDS read replica as multi-AZ. https://aws.amazon.com/about-aws/whats-new/2018/01/amazon-rds-read-replicas-now-support-multi-az-deployments/?nc1=h_ls

I found that I can do this using the AWS console: 
![image](https://user-images.githubusercontent.com/10983844/58789076-941a3680-85ed-11e9-88a2-6abb5ad8853a.png)

So I would like to deploy this strategy using Terraform, but there is nothing about deploying a Postgresql database read replica as multi-AZ in the Terraform documentation.

Is there an example for multi-AZ read replicas?

Thank ou in advance,
Zakaria

**Comment by tiagocborg** [comment]
Yes, there is. You just need to pass your database source in the `replicate_source_db` field to make that `aws_rds_instance` into a read replica. To make it multi-az, just use `multi_az = true`

https://www.terraform.io/docs/providers/aws/r/db_instance.html#replicate_source_db

**Comment by SolidSly** [comment]
It seems a solved problem, if you have any other troubles, don't hesitate to reopen the issue. closes #125

**Comment by antonbabenko** [comment]
This has been resolved already.
