### ISSUE TITLE
Postgres example doesn't work with terraform 0.12.2

### ISSUE THREAD

**Issue by markmsmith** [terraform-aws-modules/terraform-aws-rds#134]
### Environment
```
Terraform v0.12.2
provider.aws v2.15.0

terraform-aws-rds module version: 2.0.0
```

### Problem
I attempted to run the example from here:
https://github.com/terraform-aws-modules/terraform-aws-rds/tree/master/examples/complete-postgres
with minimal changes (to use a smaller instance).  
The `plan` step works fine, but the `apply` step fails with the following errors:
```
$ terraform apply main.tfplan
module.db.module.db_subnet_group.aws_db_subnet_group.this[0]: Creating...
module.db.module.db_subnet_group.aws_db_subnet_group.this[0]: Creation complete after 1s [id=demodb-postgres-20190620003555762500000001]

Error: Resource node has no configuration attached

The graph node for
module.db.module.db_parameter_group.aws_db_parameter_group.this[0] has no
configuration attached to it. This suggests a bug in Terraform's apply graph
builder; please report it!


Error: Reference to undeclared module

  on .terraform/modules/db/terraform-aws-modules-terraform-aws-rds-fedd420/main.tf line 6, in locals:
   6:   parameter_group_name_id = var.parameter_group_name != "" ? var.parameter_group_name : module.db_parameter_group.this_db_parameter_group_id

The configuration contains no module.db.module.db_parameter_group.


Error: Reference to undeclared module

  on .terraform/modules/db/terraform-aws-modules-terraform-aws-rds-fedd420/outputs.tf line 73, in output "this_db_parameter_group_id":
  73:   value       = module.db_parameter_group.this_db_parameter_group_id

The configuration contains no module.db.module.db_parameter_group.


Error: Reference to undeclared module

  on .terraform/modules/db/terraform-aws-modules-terraform-aws-rds-fedd420/outputs.tf line 78, in output "this_db_parameter_group_arn":
  78:   value       = module.db_parameter_group.this_db_parameter_group_arn

The configuration contains no module.db.module.db_parameter_group.
```

### Terraform Files + Console Output
A gist with the files I was running as well as the full console output can be found here:  
https://gist.github.com/markmsmith/7d9544d5ccab0b6a3793b33601d5e6c3

**Comment by markmsmith** [comment]
It looks like this may be a bug with terraform:  
https://github.com/hashicorp/terraform/issues/21515
however, some of the commenters on that issue mention that problems with variable defaulting in a module can also trigger this, so I'll leave this open until the cause can be pinned down definitively.

**Comment by scorpp** [comment]
same issue here on version 0.12.1

**Comment by nghiapt** [comment]
Posible fix? https://github.com/terraform-aws-modules/terraform-aws-rds/pull/138

**Comment by 51004143** [comment]
That's work !!! Thank you @nghiapt

**Comment by antonbabenko** [comment]
Thanks @nghiapt for the update!

[v2.1.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.1.0) has been released.
