### ISSUE TITLE
Support for max_allocated_storage

### ISSUE THREAD

**Issue by acidwars** [terraform-aws-modules/terraform-aws-rds#141]
I think the "max_allocated_storage" is not supported yet:

```
Error: Unsupported argument

  on database.tf line 27, in module "postgres":
  27:   max_allocated_storage        = 100

An argument named "max_allocated_storage" is not expected here.
```

See: https://www.terraform.io/docs/providers/aws/r/db_instance.html#storage-autoscaling

**Comment by wollerman** [comment]
@antonbabenko this would be great to have. Is there an expected timeline for another release with this PR? Thanks for maintaining this repo!

**Comment by mattyait** [comment]
@antonbabenko created a PR for this repo, please review and merge.

**Comment by antonbabenko** [comment]
Thanks @acidwars for the PR!

[v2.3.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.3.0) has been released.

**Comment by oxynux** [comment]
@antonbabenko is this work with v1.30.0+ ?
