### ISSUE TITLE
Bug invalid or unknown key: performance_insights_enabled

### ISSUE THREAD

**Issue by bravecobra** [terraform-aws-modules/terraform-aws-rds#149]
Using v1.29.0 I now get the following error 

    Error: module.db_instance.aws_db_instance.this: : invalid or unknown key: performance_insights_enabled

Reverting back to version 1.28.0 makes it work again. I'm using terraform v0.11.14
I didn't specify anything extra, compared to my v1.28 usage, so somehow the default value performance_insights_enabled didn't kick in properly.

**Comment by mattyait** [comment]
It must be related to aws provider version you are using, make sure it is atleast 2.8.0 version or make it to latest.
https://github.com/terraform-providers/terraform-provider-aws/pull/6453

```
provider "aws" {
  version = ">= 2.19.0"
}
```

**Comment by bravecobra** [comment]
Yes indeed my aws provider is specified lower than that.
My version is like this:
```
provider "aws" {
  region = "eu-west-1"
  profile = "my-profile-name"
  version = "~> 1.54.0"
}
```
Updating it to 2.19.0 fixes the issue. Is the minimum aws provider version specified in the docs somewhere? That might be a welcome addition ;)

**Comment by antonbabenko** [comment]
Currently, there is no easy way to track which release of this module has specific version requirements. This will, hopefully, become easier and will require less manual archeological work in the upcoming releases of Terraform registry.

Closing for now, because the issue has been solved.
