### ISSUE TITLE
RDS Oracle support

### ISSUE THREAD

**Issue by apjneeraj** [terraform-aws-modules/terraform-aws-rds#15]
Hi,

Does this module support Oracle RDS? I tried using it but as Oracle needs "license_model" to be provided, so when I checked in Terraform documentation, it supports it but upon checking the module code, it does not have this parameter available so I get below error everytime I run terraform plan:

1 error(s) occurred:
module root: module db: license_model is not a valid parameter

Please advise.

**Comment by antonbabenko** [comment]
Done. New version has been released - [v1.1.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/tag/v1.1.0)

**Comment by apjneeraj** [comment]
@antonbabenko  : Thanks for fixing it so fast.
