### ISSUE TITLE
[BUG] Cannot set PerformanceInsightsRetention without EnablePerformanceInsights

### ISSUE THREAD

**Issue by mprenditore** [terraform-aws-modules/terraform-aws-rds#151]
Module version: 2.4.0
Terraform version: 12.3
AWS module version: latest

Since PR #147  was merged there is a bug that arise if `performance_inisight_enabled` is set to `false` as per default.

I've posted in the PR my solution but I don't know if there is a better way to fix it.

**Comment by walkafwalka** [comment]
Sorry about that. Submitted fix PR.

**Comment by antonbabenko** [comment]
Thanks @walkafwalka for fast update.

[v2.5.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.5.0) has been released with this fix.

**Comment by mprenditore** [comment]
Thank you for the quick fix!
