### ISSUE TITLE
Issue with max_allocated_storage

### ISSUE THREAD

**Issue by imbkr** [terraform-aws-modules/terraform-aws-rds#152]
I'm using v2.4.0 and when running plan, I'm getting this error 

`terraform plan

Error: Unsupported argument

  on .terraform/modules/db/modules/db_instance/main.tf line 82, in resource "aws_db_instance" "this":
  82:   max_allocated_storage       = var.max_allocated_storage

An argument named "max_allocated_storage" is not expected here.

Error: Unsupported argument

  on .terraform/modules/db/modules/db_instance/main.tf line 153, in resource "aws_db_instance" "this_mssql":
 153:   max_allocated_storage       = var.max_allocated_storage

An argument named "max_allocated_storage" is not expected here.`

anyone has come across this?

**Comment by walkafwalka** [comment]
You need to upgrade your AWS provider.

**Comment by jonny-wg2** [comment]
What AWS Provider is required? I am receiving the same error using aws provider 2.4

`Error: module.rds.aws_db_instance.postgres: : invalid or unknown key: max_allocated_storage`

**Comment by mattyait** [comment]
@jonny-wg2 you need to refer https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md always to be in sync for available changes.
for max_allocated_storage you need to update 2.17.0

**Comment by flyinprogrammer** [comment]
then this should have never made it into the `~1.x` branches of this module?

**Comment by bryantbiggs** [comment]
@imbkr can we close this issue now?

**Comment by bryantbiggs** [comment]
@antonbabenko ok to close
