### ISSUE TITLE
passsing db_subnet_group_name causes the module not to create a db_subnet_group

### ISSUE THREAD

**Issue by arjun-motocho** [terraform-aws-modules/terraform-aws-rds#158]
VERSION: 2.5.0

`enable_create_db_subnet_group = var.db_subnet_group_name == "" ? var.create_db_subnet_group : false
`

if i pass the value db_subnet_group_name the condition fails and the code assumes i don't want subnet being created 

solution ( what i think ) : 
1. remove variable db_subnet_group 
2. if a subnet group name is passed , i definitely know that a subnet group will be created ( change the condition )

**Comment by weyderfs** [comment]
Here when I try `terraform apply -target=db_foo` return `Unknown token: 2:35 IDENT var.db_subnet_group_name`

**Comment by dpiddockcmp** [comment]
@weyderfs you're using the Terraform 0.12 version of the module with Terraform 0.11.

Either upgrade your terraform plans or put in a version constraint on the module definition:
https://www.terraform.io/docs/configuration-0-11/modules.html#module-versions

**Comment by antonbabenko** [comment]
@arjun-motocho If you pass `db_subnet_group_name` it means that this module should not create a new DB subnet because it has been already created outside of it (eg, by using `terraform-aws-modules/vpc/aws` module). This is the desired behavior.

Closing this one.
