### ISSUE TITLE
Create from snapshot boolean.

### ISSUE THREAD

**Issue by kirubakaran25** [terraform-aws-modules/terraform-aws-rds#159]
Hi,

Is there any option to explicitly mention whether or not to create a DB from snapshot? The reason why I'm asking this is it will be easier to reuse the same code for multiple environments when we have an option which easily can parameterize.

Say for example we have multiple sets of environments pulling from the same repo which contains the RDS module and since it is not possible to set snapshot_identifier to an incorrect value, is it possible to bring in another parameter like "create_from_snapshot" which when set to true will consider "snapshot_identifier" variable otherwise ignore it?

**Comment by marshall0705** [comment]
Hey,

Is it not possible to set snapshot_identifier to an empty string, which should cause it to be ignored? I've not tried it yet myself but that's the default according to the docs, so in theory it should act the same if you pass an empty string.

**Comment by bryantbiggs** [comment]
By default this is set to an empty string in the module (https://github.com/terraform-aws-modules/terraform-aws-rds/blob/85de0ce0deb7b2bb6088c01dbd6d0f7d3c233fb5/modules/db_instance/variables.tf#L41) and therefore, yes, you can either create from a base DB engine image or you can create from the snapshot that you pass to `var.snapshot_identifier`

**Comment by bryantbiggs** [comment]
@kirubakaran25 can we close this issue now?

**Comment by kirubakaran25** [comment]
Hi Bryant,

Yes, Please
