### ISSUE TITLE
terraform 0.11.14 fmt issue with examples/enhanced-monitoring/main.tf

### ISSUE THREAD

**Issue by jeohist** [terraform-aws-modules/terraform-aws-rds#160]
I was updating the version of the terraform-aws-rds module in our repositories and noticed that since version v1.29.0, it requires a terraform fmt on examples/enhanced-monitoring/main.tf in combination with Terraform 0.11.14. It looks like there were some formatting changes in that file to prepare it for Terraform 0.12, but the change in commit 05360c2 changing 

```
maintenance_window      = "Mon:00:00-Mon:03:00"
  backup_window           = "03:00-06:00"
  backup_retention_period = 0 // disable backups to create DB faster

  tags = {
    Owner       = "user"
    Environment = "dev"
  }
```

to

```
maintenance_window      = "Mon:00:00-Mon:03:00"
  backup_window           = "03:00-06:00"
  backup_retention_period = 0 // disable backups to create DB faster

  tags = {
    Owner       = "user"
    Environment = "dev"
  }
```

seems to be non-compliant with the way Terraform 0.11 expects files to be formatted. This is the output I get from terraform fmt -diff=true:

```
-  backup_retention_period = 0 // disable backups to create DB faster
+  backup_retention_period = 0                                         // disable backups to create DB faster
```

**Comment by antonbabenko** [comment]
Thanks, Joey!

[v1.32.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v1.32.0) has been just released.
