### ISSUE TITLE
Destroy fails due to option group deletion

### ISSUE THREAD

**Issue by timbrammer** [terraform-aws-modules/terraform-aws-rds#162]
When attempting to destroy an instance of this module, the process always fails due to the final snapshot being associated with the db options group created as part of the deploy. Is there a work around to skip destroying the option group or something?

**Comment by sreecodeslayer** [comment]
I have been using this module for a while now, testing it alongside other resources. 
I haven't had this issue up until today.

```Error: Error Deleting DB Option Group: InvalidOptionGroupStateFault: The option group 'tf-test-rds-postgres-20200108062450789800000003' cannot be deleted because it is in use.```

**Comment by antonbabenko** [comment]
As a workaround you can use submodules of this module - one submodule to create just a DB option group and another one to create a DB instance(s).

```hcl
module "db_instance" {
  source = "terraform-aws-modules/rds/aws//modules/db_instance"

  option_group_name = module.db_option_group.this_db_option_group_id

  # ... omitted
}

module "db_option_group" {
  source = "terraform-aws-modules/rds/aws//modules/db_option_group"

  # ... omitted
}
```

Also, deletion of DB option group can take a long time and you need to increase maximum timeout for it (see https://github.com/terraform-aws-modules/terraform-aws-rds/issues/144#issuecomment-572499341).

**Comment by sreecodeslayer** [comment]
Interesting!
I was able to delete the option group without any changes after a day, as one of comments mentions in https://github.com/terraform-providers/terraform-provider-aws/issues/4597#issuecomment-427266552.

What would be a good timeout value here, as I find it reasonably long

**Comment by antonbabenko** [comment]
Yes, it usually works if you just rerun the same terraform command after it fails to delete on the first attempt. Regarding the duration of a timeout, I see [this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/4597#issuecomment-521633150) where it sets to `2h`.

I think if something takes longer than half an hour to delete, the solution should be reworked or revised.

**Comment by bryantbiggs** [comment]
closing this out for now
