### ISSUE TITLE
RDS gets triggered for replacement when getting username from aws secrets manager even though no change has been made

### ISSUE THREAD

**Issue by schrill** [terraform-aws-modules/terraform-aws-rds#163]
I'm experiencing a problem when I try to get username and password from data source of AWS secret manager as such:

  username = data.external.secret_map.result["rds_user"]
  password = data.external.secret_map.result["rds_pass"]

The other parts are in a separate template as such:

data "aws_secretsmanager_secret_version" "rds" {
  secret_id = "${var.secret_id_rds}${var.env_tag}"
  depends_on = [aws_secretsmanager_secret_version.rds]
}
data "external" "secret_map" {
  program = ["echo", data.aws_secretsmanager_secret_version.rds.secret_string]
}

I can confirm that the secrets placement and retrieval works for all my other segments and that only the username part in the module triggers the replacement and not the password one.

This happens after a successful first apply, on the second the replacement is suggested,
      ~ username                              = "root" -> (known after apply) # forces replacement
but fails if I continue with the error message that the database already exists
Error: Error creating DB Instance: DBInstanceAlreadyExists: DB Instance already exists
	status code: 400, request id: 

Using aws_secretsmanager_secret_version becuase aws_secretsmanager_secret does not offer secret placement and retrieval only retrieval.

**Comment by hcandia-uala** [comment]
did you find any solution to to this? I'm facing the same problem

**Comment by hcandia-lagash** [comment]
did you find any solution to to this? I'm facing the same problem

**Comment by schrill** [comment]
Unfortunately no, I've even asked the community over stackoverflow: https://stackoverflow.com/questions/57956142/rds-gets-triggered-for-replacement-when-getting-username-from-aws-secrets-manage?noredirect=1#comment102348552_57956142
but other then a series of unproductive back and forward messages in the thread you won't find anything useful.

**Comment by bryantbiggs** [comment]
hello @schrill - could you use the markdown formatting on the code to make it a bit easier to read?

I don't know that you need all the configurations that you've provided, have you tried:

```hcl
data "aws_secretsmanager_secret_version" "rds" {
secret_id = "${var.secret_id_rds}${var.env_tag}"
}
```

and the just pull the secret value directly with:

```hcl
resource "aws_db_instance" "default" {
  allocated_storage    = 20
  storage_type         = "gp2"
  engine               = "mysql"
  engine_version       = "5.7"
  instance_class       = "db.t2.micro"
  name                 = "mydb"
  username             = jsondecode(data.aws_secretsmanager_secret_version.rds.secret_string)["username"]
  password             = jsondecode(data.aws_secretsmanager_secret_version.rds.secret_string)["password"]
  parameter_group_name = "default.mysql5.7"
}
```

**Comment by schrill** [comment]
Tnx @brayantbigs I'll try the direct method as suggested and report back. Since then I've managed to do a workaround, since I'm also generating the secrets and placing them in the AWS secrets manager prior using I've replaced the data with locals.

**Comment by bcomnes** [comment]
Running in to the same issue.   Although nothing actually changes on apply, our plan view shows that various dependencies on the data value will be updated in place.

It appears to do so because `data.aws_secretsmanager_secret_version.foo will be read during apply`.  

Creates for some very noise plans.

**Comment by bcomnes** [comment]
My apologies, this the wrong repo.

**Comment by yanivpaz** [comment]
@schrill any chance to share this full example?

**Comment by bryantbiggs** [comment]
hi all, I'm going to close this issue out for now - if there are any further issues please feel free to open a new issue
