### ISSUE TITLE
v2.4.0+ missing from registry

### ISSUE THREAD

**Issue by dekimsey** [terraform-aws-modules/terraform-aws-rds#165]
Versions v2.4.0 and above are not published on the [terraform registry][0]. I'm guessing this isn't expected, but I'm not sure.

[0]: https://registry.terraform.io/modules/terraform-aws-modules/rds-aurora/aws

**Comment by antonbabenko** [comment]
Hi Daniel,

`rds-aurora` and `rds` are two different modules, and both are published on the registry:
https://registry.terraform.io/modules/terraform-aws-modules/rds/aws
https://registry.terraform.io/modules/terraform-aws-modules/rds-aurora/aws

**Comment by dekimsey** [comment]
Sigh. I thought I had double-checked that. Thank you!
