### ISSUE TITLE
required variable "identifier" not set

### ISSUE THREAD

**Issue by fbuchmeier** [terraform-aws-modules/terraform-aws-rds#17]
Hi,

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/variables.tf

states that if `identifier` is not set, Terraform will assign an unique identifier on its own. This does currently not work, since `tf plan` fails with:

```
* module root: module application_db: required variable "identifier" not set
```

Is there a workaround to generate a unique identifier?

Thanks!

Flo.

Update: This also applies to the other "required" variables, like `name`.

**Comment by antonbabenko** [comment]
Have you tried to pass an empty value as `identifier` and `name`?

**Comment by fbuchmeier** [comment]
Hi,

thanks for the suggestion. Passing an empty string with double quotes does not work.
````
module "test_db" {
  source = "terraform-aws-modules/rds/aws"

  identifier = ""
  name = ""
```

```
~/git/sandbox(modules*) » tf plan                                                    
3 error(s) occurred:

* module.test_db.module.db_instance.aws_db_instance.this: first character of "identifier" must be a letter
* module.test_db.module.db_instance.aws_db_instance.this: only lowercase alphanumeric characters and hyphens allowed in "identifier"
* module.test_db.module.db_parameter_group.aws_db_parameter_group.this: first character of "name_prefix" must be a letter
```

When I use single quotes, it does not work either.
```
~/git/sandbox(modules*) » tf plan                                                       
Failed to load root config module: Error parsing /Users/fbuchmeier/git/sandbox/main.tf: At 154:16: illegal char
```

Cheers,

Florian.

**Comment by antonbabenko** [comment]
Yes, this is correct behavior. You actually should set valid `identifier`, but we also have to update variable's description.
