### ISSUE TITLE
Update ca_cert_identifier

### ISSUE THREAD

**Issue by chelomontilla** [terraform-aws-modules/terraform-aws-rds#171]
Hello,
I found it's still not supported by terraform to manage the ca_cert_identifier of the db instance, but there's already a [PR open](https://github.com/terraform-providers/terraform-provider-aws/pull/10490). It would be great to have support for this also for the tf module.

**Comment by andrewwatson** [comment]
Because RDS is forcing people to update the CA on their RDS instances by 2/5 it would be really great to have this ASAP!
