### ISSUE TITLE
ParameterGroupFamily postgres10.7 is not a valid parameter group family

### ISSUE THREAD

**Issue by dshuvar** [terraform-aws-modules/terraform-aws-rds#173]
Error: Error creating DB Parameter Group: InvalidParameterValue: ParameterGroupFamily postgres10.7 is not a valid parameter group family
	
status code: 400

part of playbook just a bit changed from an example:

```
  # DB parameter group
  family = "postgres10.7"
```

**Comment by antonbabenko** [comment]
You are right, `postgres10` is a valid family name for Postgres 10 and 11.

See this answer - https://stackoverflow.com/a/55818740/550451
