### ISSUE TITLE
Error Enabling SQLSERVER_AUDIT in db_options_group 

### ISSUE THREAD

**Issue by sunkara687** [terraform-aws-modules/terraform-aws-rds#180]
Hi all,

Please let me know how to enable SQLServer_Audit in db_option_group parameter in terraform? I need to keep the audit log files to s3 bucket. I'm getting the below error when trying to enable it.  I'm attaching my code and error screenshots. Requesting your support.
Thankyou.

![code](https://user-images.githubusercontent.com/59390204/71619247-8b65ff00-2bd4-11ea-946f-641122535539.PNG)
![error](https://user-images.githubusercontent.com/59390204/71619249-8bfe9580-2bd4-11ea-92f7-e8ff9e4671d1.PNG)

**Comment by bryantbiggs** [comment]
@sunkara687 - please reference the AWS documentation, you are missing required option settings https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.SQLServer.Options.Audit.html

**Comment by bryantbiggs** [comment]
@antonbabenko ok to close
