### ISSUE TITLE
Error: ca_cert_identifier this field cannot be set

### ISSUE THREAD

**Issue by flmmartins** [terraform-aws-modules/terraform-aws-rds#184]
Hello all,
I have an existing databases which I changed the ca_cert_indentifier manually to rds-ca-2019. Now the version of my module was updated to 1.35.0 (I use terraform 11) and when I plan it shows the error below:

```
module.my-database1.module.db.module.db_instance.aws_db_instance.this: "ca_cert_identifier": this field cannot be set
```

PS: I try with default value and setting it. 

Any suggestions?

**Comment by antonbabenko** [comment]
Are you using AWS provider where this is supported? v2.37.0 or newer? [See CHANGELOG.md](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2370-november-18-2019)

**Comment by flmmartins** [comment]
Oh jez... I updated the aws provider and it works. Closing this now...
