### ISSUE TITLE
Could not download last released module

### ISSUE THREAD

**Issue by kozub** [terraform-aws-modules/terraform-aws-rds#185]
Hello Team,

Today I found some issues with running Terraform module which uses "terraform-aws-rds" on CD/CI. The error message says: 

> Error: Failed to download module

> Could not download module "my_module" (main.tf:16) source code from
"https://api.github.com/repos/terraform-aws-modules/terraform-aws-rds/tarball/v2.12.0//*?archive=tar.gz":
Error opening a gzip reader for

It was quite surprising because it worked fine yesterday and there was no changes on my side. After quick investigation I found that an issue is related to last release of terraform-aws-rds. I did not have specified version in my module, so it tries to use last one. I've added version property to refer to previous release and my issue disappear: 

```
module "my_module" {
  source     = "terraform-aws-modules/rds/aws"
  version =  "2.11.0"
  ...
```
for version = 2.12.0 issue still exits.

So details about the environment:
- TeamCity linux agent
- docker container: hashicorp/terraform:0.12.17

I've tried to reproduce this issue on my MacOS machine  but surprisingly it is able to use the module without any problems, so my assumption is that it might be related to linux module binary. 

Please let me know if there is anything that I can help to reproduce this bug.

**Comment by antonbabenko** [comment]
Hi @kozub !

There often is a problem with network connectivity or cache somewhere in the process. Github or Terraform Registry may be a bit unstable and it often results as "Failed to download module".

The difference between v2.11.0 and v2.12.0 is rather small - https://github.com/terraform-aws-modules/terraform-aws-rds/compare/v2.11.0..v2.12.0

You can try to reproduce this bug if you clear cache on your CI/CD system (eg, `rm -rf .terraform`).

**Comment by antonbabenko** [comment]
Terraform's CHANGELOG has a couple of points that may be related to what you have experienced: 

>  command/init: Cache Terraform Registry metadata responses when handling multiple references to the same module. [GH-23727]

>  commant/init: Fix an issue with via an update to go-getter where modules would fail to download from the registry [GH-23792]


See this link for full CHANGELOG - https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#01219-unreleased

**Comment by kozub** [comment]
Hi Anton (@antonbabenko) ,

Thank you for your help. I believe that issue that we experienced might be related to the mentioned issue in Terraform. I've tried to run it on v0.12.19 and it works. 

Thank you!
