### ISSUE TITLE
DB option group is created with create_db_option_group = false parameter

### ISSUE THREAD

**Issue by mgaal86** [terraform-aws-modules/terraform-aws-rds#188]
Hi,

Currently it is not possible to avoid creating a DB option group only with a workaround (setting `option_group_name` to some dummy value): 
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/3997fcb615d1fa516cc7815e12b130a9cd987f3c/main.tf#L9

Was this really the intention?

Thanks!

**Comment by mgoldman-solarwinds** [comment]
Can confirm, seeing this too.

**Comment by daefresh** [comment]
Seeing this too.
