### ISSUE TITLE
RDS Proxy

### ISSUE THREAD

**Issue by nickhalden** [terraform-aws-modules/terraform-aws-rds#190]
Hi,
When does the RDS Proxy support get released in terraform released during 2019 reinvent? I see the service supported in the RDS console already (us-west-2).

**Comment by Thomas-X** [comment]
+1

**Comment by cursedcoder** [comment]
+1

**Comment by kiyono** [comment]
+1

**Comment by els-idimitrov** [comment]
+1

**Comment by nipunchawla-bc** [comment]
+1

**Comment by antonbabenko** [comment]
I know, we all want to have this immediately after AWS re:invent.

We can't do much without having this feature supported by [Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws) before we can add it to this module.

From what I understand, it is not supported there yet. Am I wrong?

**Comment by phanimullapudi** [comment]
When is suppport for RDS proxy coming ?

**Comment by nickhalden** [comment]
@antonbabenko pleas refer to these. The AWS cli supports it now. 
https://aws.amazon.com/rds/proxy/
https://docs.aws.amazon.com/cli/latest/reference/rds/index.html

**Comment by dpiddockcmp** [comment]
Terraform does not call the AWS CLI. Support needs to be added to the terraform aws provider before this module can use the feature.

There's an issue requesting support here: https://github.com/terraform-providers/terraform-provider-aws/issues/12690
And looks like someone has created a PR adding the resource: https://github.com/terraform-providers/terraform-provider-aws/pull/12704

**Comment by anonxss** [comment]
+1

**Comment by miseyu** [comment]
+1

**Comment by antonbabenko** [comment]
This resource is now supported in AWS provider v3.5.0 (ref https://github.com/terraform-providers/terraform-provider-aws/pull/12704).

**Comment by bryantbiggs** [comment]
we'll need to wait most likely for the proxy target before we can look at bringing this in. without the target, the proxy is not pointed at any database instances and therefore not usable unless manually configured. hopefully this resource makes it in on 3.6.0 https://github.com/terraform-providers/terraform-provider-aws/pull/12784

**Comment by nirsv** [comment]
Any idea how do I add Database proxies to a lambda in terraform? I am afraid it is not supported (not sure if this PR will solve it)

**Comment by larstobi** [comment]
This has been released in version 3.9.0 of the Terraform AWS provider.
https://github.com/terraform-providers/terraform-provider-aws/pull/12784#issuecomment-702910011

**Comment by JeffNguyen-Diginex** [comment]
> Any idea how do I add Database proxies to a lambda in terraform? I am afraid it is not supported (not sure if this PR will solve it)

It seems not to support yet

**Comment by bryantbiggs** [comment]
https://github.com/clowdhaus/terraform-aws-rds-proxy

**Comment by andreikho** [comment]
> Any idea how do I add Database proxies to a lambda in terraform? I am afraid it is not supported (not sure if this PR will solve it)

Still not supported?

**Comment by bryantbiggs** [comment]
what is the question?

**Comment by antonbabenko** [comment]
The question is probably related to some people having an expectation that this feature should be part of this module also. I don't think so because RDS Proxy is a rather complex piece (see resources created in [the module](https://github.com/clowdhaus/terraform-aws-rds-proxy)).

I would like us to have a link in the README to the https://github.com/clowdhaus/terraform-aws-rds-proxy explaining relations.

**Comment by bryantbiggs** [comment]
ah ok, I see. I didn't know if it was asking about RDS Proxy support in the module or support to add the config to Lambda functions, etc.

Yes I can add something to the documentation. I agree - especially with having multiple proxies point to the same RDS instance (i.e. - one for IAM auth, one for standard auth, etc.), and we would also need to add support for the Aurora module as well - its best if its separate. makes life more simple and the modules easier to manage
