### ISSUE TITLE
Race condition on creating replica right after master RDS is created

### ISSUE THREAD

**Issue by tylux** [terraform-aws-modules/terraform-aws-rds#192]
I am unable to create a replica at the same time as the master RDS, it fails saying the current DB instance is not in the available state, if I run it again after it works just fine.

```
Error: Error creating DB Instance: InvalidDBInstanceState: DB instance is not in the available state
	status code: 400, request id: 46476712-6967-4bb2-a0c8-a699fce6cbd0
```

Is there a way to include a sleep or depends on the master being available before trying the readreplica.

**Comment by LouisPolyconseil** [comment]
You can use `replicate_source_db = module.rds.this_db_instance_id` where module.rds is your master rds.

**Comment by bryantbiggs** [comment]
please see the above statements and what has been demonstrated in the `examples/replica-mysql` or `examples/replica-postgresql`
