### ISSUE TITLE
Official VPC module integration

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [terraform-aws-modules/terraform-aws-rds#20]
https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/1.0.4
The module can create the default database subnet group. How can I use it in RDS module?

**Comment by antonbabenko** [comment]
You basically have two main options:
1. Use database subnet group created by VPC module and use module `db_instance` of `terraform-aws-modules/rds/aws`.
2. Use this module which will create RDS instance and database subnet group, but disable creation of database subnet group in VPC module (`create_database_subnet_group = false`)

For me, it seems that option 2 is better.

**Comment by Ilya-Kuchaev** [comment]
Hm... But why I can't use the already created subnet group? Even if it's manually created?

**Comment by antonbabenko** [comment]
You certainly can. This is the same as the first option. Use module `db_instance` of `terraform-aws-modules/rds/aws`.
