### ISSUE TITLE
RDS replicas don't have password exported

### ISSUE THREAD

**Issue by jtai-omniex** [terraform-aws-modules/terraform-aws-rds#207]
The postgres RDS replicas require that null is passed in for the password, given that it's assigned the same password as the source database. However, the replica's password is exported as "null" rather than the actual value that it's given.

This causes missing information for modules that are dependent on the correct password, such as creating a Secrets Manager record that contains the database credentials.

**Comment by bryantbiggs** [comment]
hi @jtai-omniex  - I would recommend not exporting passwords from the replicas as the passwords are set/controlled in the read/write (primary) instance. Replicas are just that, an exact copy of the primary

**Comment by bryantbiggs** [comment]
@antonbabenko we can close
