### ISSUE TITLE
parameter_group_name fails to create parameter group

### ISSUE THREAD

**Issue by ashwiniag** [terraform-aws-modules/terraform-aws-rds#213]
I want to create parameter group with custom name, but it fails with following error.
```
 Error creating DB Instance: DBParameterGroupNotFound: DBParameterGroup not found: testing-pg status code: 404, request id: 638b7724-0f76-4caf-88f1-2bd17ea14477
```
as per the documentation I have set the following
`version = "2.14.0"`
```
  family = "mysql8.0" 
  create_db_parameter_group = true
  parameter_group_name = "testing-pg" 
```

**Comment by krzysztof-miemiec** [comment]
Try setting `use_parameter_group_name_prefix` to `false` - from what I see, internal name is generated because this flag is set to `true` by default.

**Comment by ashwiniag** [comment]
Thank you @krzysztof-miemiec . It worked
