### ISSUE TITLE
DB Identifier input documentation seems to be wrong and incomplete

### ISSUE THREAD

**Issue by ykshatroff** [terraform-aws-modules/terraform-aws-rds#214]
The docs for DB identifier say:

> The name of the RDS instance, if omitted, Terraform will assign a random, unique identifier

Unfortunately for me, it doesn't work:

> The argument "identifier" is required, but no definition was found.

Moreover, there is nothing said about the restrictions on the identifier format: it can't be anything but alphanumeric due apparently to AWS API limitations (https://github.com/terraform-providers/terraform-provider-aws/issues/9655), which is extremely inconvenient given that the automatic generation fails.

Terraform v0.12.24

**Comment by DiegoLelis** [comment]
HAving the same problem

**Comment by bryantbiggs** [comment]
hi all - unfortunately the `identifier` value was something that was used in multiple places in this module. we have made some changes to move away from this pattern but not fully - at the next breaking change we can look at fully removing this dependency and therefore make the `identifier` value optional like it is with the DB instance resource
