### ISSUE TITLE
different behavior between Terraform V11 and V12 on this module

### ISSUE THREAD

**Issue by mikamakusa** [terraform-aws-modules/terraform-aws-rds#219]
Hi,

I'm using this module for a pro mission, originally they use terraform V11 to provision resources with this module : 1 master and a read replica with another provider alias.
With Terraform v11, no errors are showing.
But when a do the same with Terraform V12, the following error occurs : 
```
Error: Unsupported block type

  on rds.tf line 123, in module "rds_master_replica":
 123:   providers {

Blocks of type "providers" are not expected here.
```
To be more precise, in the vars.tf, the map values doesn't activate the rds_master_replica resource...this is why I do not understand why the error above occurs.

I thought it could the version of terraform (like similar issues), but it's terraform v0.12.20.

Thanks for any help :)

**Comment by antonbabenko** [comment]
You should update your `rds.tf` and write `providers = {` in Terraform 0.12.

This problem is not related to the module, see [this section in Terraform 0.12 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks).
