### ISSUE TITLE
Update provider version to reflect requirements

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [terraform-aws-modules/terraform-aws-rds#224]
The provider requirement for Terraform 0.12.x appears to be lower than what is necessary to use this module. Per #184, which I experienced today, provider version should be `~> 2.37`

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/9aff82bec1bcfe1c7a9f5479bfda7926509bd967/versions.tf#L4-L6

**Comment by antonbabenko** [comment]
I think you are right, so pull-request is welcome.
