### ISSUE TITLE
only lowercase alphanumeric characters and hyphens allowed in parameter group "name_prefix"

### ISSUE THREAD

**Issue by mohammadasim** [terraform-aws-modules/terraform-aws-rds#225]
While using this module to create an instance of RDS postgres, I get the following error when I run terraform plan.
`module "db" {`
   ` source                       = "terraform-aws-modules/rds/aws"`
    `version                      = "~> 2.0"`

Terraform version:
`Terraform v0.12.19`
`provider.aws v2.61.0`

Error message:
`Error: only alphanumeric characters and hyphens allowed in "name_prefix"`
  `on .terraform/modules/db/terraform-aws-rds-2.14.0/modules/db_option_group/main.tf line 1,` `in resource "aws_db_option_group" "this":`
   `1: resource "aws_db_option_group" "this" {`

`Error: only lowercase alphanumeric characters and hyphens allowed in parameter group` `"name_prefix"`

  `on .terraform/modules/db/terraform-aws-rds-2.14.0/modules/db_parameter_group/main.tf` `line 33, in resource "aws_db_parameter_group" "this":`
  `33: resource "aws_db_parameter_group" "this" {`

**Comment by antonbabenko** [comment]
Hi @mohammadasim !

That's right, you should only use lowercase alphanumeric characters and hyphens in `parameter_group_name` and `identifier` as the error says.

**Comment by mohammadasim** [comment]
Thanks. Changed it and it works now

**Comment by SovitRed** [comment]
module "db" {
  source = "terraform-aws-modules/rds/aws"

  identifier = "trf_db"

  engine            = "mysql"
  engine_version    = "5.7.25"
  instance_class    = "db.t3a.large"
  allocated_storage = 5

  db_name  = "trf_database"
  username =  "risav_rds"
  port     = "3306"

Error: only alphanumeric characters and hyphens allowed in "name_prefix"
│ 
│   with module.db.module.db_option_group.aws_db_option_group.this[0],
│   on .terraform/modules/db/modules/db_option_group/main.tf line 12, in resource "aws_db_option_group" "this":
│   12:   name_prefix              = local.name_prefix
│ 
╵
╷
│ Error: only lowercase alphanumeric characters and hyphens allowed in parameter group "name_prefix"
│ 
│   with module.db.module.db_parameter_group.aws_db_parameter_group.this[0],
│   on .terraform/modules/db/modules/db_parameter_group/main.tf line 12, in resource "aws_db_parameter_group" "this":
│   12:   name_prefix = local.name_prefix


please resolve my issue

**Comment by antonbabenko** [comment]
`only alphanumeric characters and hyphens allowed in ...` means that you need to change the `identifier` from `trf_db` to something like `trf-db`.

**Comment by SovitRed** [comment]
okay thanks but i also resolve this error

**Comment by SovitRed** [comment]
actullay i want to create RDS using terraform can you send me file to create RDS using terraform
