### ISSUE TITLE
AWS version constraint is too narrow

### ISSUE THREAD

**Issue by Yopi** [terraform-aws-modules/terraform-aws-rds#227]
I think the version constraint should probably be minimum but not pessimistic. I.e.

```
  required_providers {
    aws = "=> 2.37"
  }
```

instead of
```
  required_providers {
    aws = "~> 2.37"
  }
```

Otherwise it makes it hard to use this module in conjunction with other modules.

**Comment by antonbabenko** [comment]
The reason for using `~>` is that sooner or later there will be breaking changes in AWS provider version 3.x, but `~> 2.37` say that this module works with AWS provider version starting from `2.37` and to `2.999`.

**Comment by Yopi** [comment]
Right, that makes sense! Seems like I have an issue somewhere else, I took it to mean `>= 2.37 & < 2.40`.

Thanks for the quick response!
