### ISSUE TITLE
Error creating DB Instance: InvalidParameterValue: DBName must be null for engine: sqlserver-se

### ISSUE THREAD

**Issue by mani26br** [terraform-aws-modules/terraform-aws-rds#228]
I am always having following issue while creating the sql server database, it is showing the invalid db engine, I gave the  parameter sqlserver-se (because I want the standard version), It is showing,

Error creating DB Instance: InvalidParameterValue: DBName must be null for engine: sqlserver-se

I tried giving the engine value Null then it is showing engine value should not be null. 

I also tried creating the db by using the example you have given in the following github source

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/examples/complete-mssql/main.tf

Still having the same issue, 

Please help me here.

Thanks,
Mani.

**Comment by antgel** [comment]
You didn't include your code, but have another look at the documentation. You have probably set `name` which is not supported, and perhaps you meant `identifier` instead.
