### ISSUE TITLE
Would like to use db_subnet_group_name natively

### ISSUE THREAD

**Issue by Vermyndax** [terraform-aws-modules/terraform-aws-rds#23]
I have another remote terraform state that I'm accessing to deploy RDS instances into - the VPC in that terraform deployment already has a DB Subnet Group. I'd like to reference it instead of creating a new one when I use this module.

**Comment by antonbabenko** [comment]
There was similar issue recently - https://github.com/terraform-aws-modules/terraform-aws-rds/issues/20

Please reopen this issue if you still have questions.
