### ISSUE TITLE
Option group always with name_prefix and timestamp generated by terraform

### ISSUE THREAD

**Issue by factotum-fox** [terraform-aws-modules/terraform-aws-rds#230]
"name" variable, in the option group module,  is missing.
The option group name is always a concatenation of "name_prefix" and and a timestamp generated by terraform.
"name" variable may be added in the option group module and, if set, it can be used to give a name without timestamp to the option group.
Thanks

**Comment by sergirosell** [comment]
it would be nice if it had the same behavior as the parameter_group option has with "use_parameter_group_name_prefix".
