### ISSUE TITLE
support for mysql 8.0

### ISSUE THREAD

**Issue by tnimni** [terraform-aws-modules/terraform-aws-rds#233]
Is there support for mysql 8.0?

I'm getting many errors when trying to set the engine to 8.0, wondering if is supported

**Comment by antonbabenko** [comment]
Yes, there should be a support for Mysql 8.0 according to AWS release notes:

> Amazon RDS for MySQL now supports MySQL Community Edition major version 8.0 in all AWS Regions.

See more https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt
