### ISSUE TITLE
Flag to ignore updates to password

### ISSUE THREAD

**Issue by ShayaTepper** [terraform-aws-modules/terraform-aws-rds#234]
I am on version 2.16.

For security purposes, we need to update the root password of the database on a monthly basis. There is also a requirement not to store the password in plain text anywhere. The easiest way to implement this would be to update the root password directly and apply an ignore_changes to the password attribute in Terraform. This way, we can apply changes to the database using Terraform without requiring to set the password. It won't be saved to the state file and the updated password won't be overridden.

I don't see any way to do this using this module. Perhaps a flag - something like `ignore_password_changes = true` - could do the trick?

**Comment by antonbabenko** [comment]
HI @ShayaTepper !

Password value is not returned by AWS, so it is not used in comparison and thus there is no need to add it to `ignore_changes`. You can set dummy password in terraform just to create an RDS instance and then rotate it monthly outside of Terraform as you are describing.
