### ISSUE TITLE
MySQL replica example appears to be broken

### ISSUE THREAD

**Issue by silviogutierrez** [terraform-aws-modules/terraform-aws-rds#239]
First off: thanks for these modules, they're very helpful when navigating the AWS ecosystem.

The RDS mysql replica example, verbatim, currently fails with terraform 0.12.7.

## Steps to reproduce:

1. `git clone git@github.com:terraform-aws-modules/terraform-aws-rds.git`
2. `cd terraform-aws-rds/examples/replica-mysql`
3. `terraform init`
4. `terraform apply`

```
module.replica.module.db_option_group.aws_db_option_group.this[0]: Creating...
module.master.module.db_option_group.aws_db_option_group.this[0]: Creating...
module.master.module.db_subnet_group.aws_db_subnet_group.this[0]: Creating...
module.master.module.db_subnet_group.aws_db_subnet_group.this[0]: Creation complete after 3s [id=demodb-master-mysql-20200720200939150700000003]


Error: Error creating DB Option Group: InvalidParameterValue: The parameter MajorEngineVersion must be provided and must not be blank.
        status code: 400, request id: e2973e1f-cb0b-49cf-835f-40ed9b3e7a77

  on ../../modules/db_option_group/main.tf line 1, in resource "aws_db_option_group" "this":
   1: resource "aws_db_option_group" "this" {



Error: Error creating DB Option Group: InvalidParameterValue: The parameter MajorEngineVersion must be provided and must not be blank.
        status code: 400, request id: c0a6ae89-97c3-40a2-87c7-09b9611b991a

  on ../../modules/db_option_group/main.tf line 1, in resource "aws_db_option_group" "this":
   1: resource "aws_db_option_group" "this" {
```

I tried to debug further but I'm not familiar enough with option groups. Hope this helps.

**Comment by yhkim-prestolabs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/c1b7f12a8b7c250b76a038e567dff47d3923c6f0/main.tf#L9

I think `var.option_group_name == ""` should be `var.option_group_name != ""`.

**Comment by tlecointre** [comment]
I'm getting the same error with `create_db_option_group = false` . The plan shows a option group creation and the apply fails with the same error as Silvio.

Module: 2.17.0
MySQL 8.0.15 for the RDS

**Comment by bryantbiggs** [comment]
hi all, we've gone through the examples and validated that they are all up to date and functional in #298
