### ISSUE TITLE
Confusing error message while providing password

### ISSUE THREAD

**Issue by aacecandev** [terraform-aws-modules/terraform-aws-rds#243]
Hi guys,

I've found a confusing error message while providing a password to an aurora-postgres RDS instance.

This is the error

Error: Error creating DB Instance: InvalidParameterValue: The parameter MasterUserPassword is not a valid password. Only printable ASCII characters <b>besides</b> '/', '@', '"', ' ' may be used.

But instead, those are exactly the forbidden characters, as I have checked.

Could it be possible to change besides > except?

**Comment by bryantbiggs** [comment]
hi @aacecandev this is controlled through either the AWS sdk or the upstream terraform provider for AWS - you'll need to file an issue with one of those libraries; we have no control over that error message here
