### ISSUE TITLE
Support AWS Provider 3.X

### ISSUE THREAD

**Issue by rifelpet** [terraform-aws-modules/terraform-aws-rds#245]
This module's version requirements do not support provider 3.0.

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/c1b7f12a8b7c250b76a038e567dff47d3923c6f0/versions.tf#L4-L6

Can these requirements be relaxed to also support 3.X ?

I'm guessing it will be similar to https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/479

**Comment by antonbabenko** [comment]
[v2.18.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.18.0) has been just released with support for AWS provider v3.
