### ISSUE TITLE
issue passing json file to options group

### ISSUE THREAD

**Issue by charlesanil** [terraform-aws-modules/terraform-aws-rds#246]
hi,
i am new to terrafom. I am able to create options group with this code.
But i want to pass options group json from a file. i have created file and passed the value .. below is syntax. but the options group modue says ... cannot convert string to list. there is for loop in options group module.. how can convert string to list. appreciate any help

Code to call from json file
data "template_file" "rds_options_policy" {

   template = "${file("policies/rds_options.json")}"

}

Resource module 
module "db_option_group" {
  source = "./../Modules/rds/db_option_group"

  create                   = local.enable_create_db_option_group
  identifier               = var.identifier
  name_prefix              = "${var.identifier}-"
  option_group_description = var.option_group_description
  engine_name              = var.engine
  major_engine_version     = var.major_engine_version
   options= ${data.template_file.rds_options_policy.rendered}

**Comment by bryantbiggs** [comment]
hi @charlesanil - could you please format your issue so we can see the syntax better? this sounds like you are running into a parsing error from trying to decode json and pass as parameters. I would suggest putting the parameters directly into the module configuration or use a local variable if the parameters are shared across multiple module configurations
