### ISSUE TITLE
Aurora Serverless

### ISSUE THREAD

**Issue by sachin-101** [terraform-aws-modules/terraform-aws-rds#248]
How can I provision Aurora serverless using this module?

**Comment by antonbabenko** [comment]
Hi @sachin-101 !

Check out another module's example - https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/tree/master/examples/serverless

**Comment by sachin-101** [comment]
Thanks @antonbabenko . Would be awesome if you changed the link for `Aurora Serverless` (on https://serverless.tf) to point to the above examples rather than this repo's examples.

**Comment by antonbabenko** [comment]
Good point! Updated.
