### ISSUE TITLE
Cannot attach KMS key

### ISSUE THREAD

**Issue by charlesanil** [terraform-aws-modules/terraform-aws-rds#249]
I create the KMS key dynamically in code and pass the ARN of KMS to RDS SQL KMS_Key_Id for encryption but the key doesn't get attached, it takes default key. I see that  key is generated and ARN listed in output variable. but it doesn't get attached. Anyne facing this problem ?

**Comment by robinvdvleuten** [comment]
Same here! Terraform recreates the RDS instance over and over because it cannot attach the KMS key.

**Comment by bryantbiggs** [comment]
can you share your code/configuration please?
