### ISSUE TITLE
What would it take to add support to allow executing SQL scripts against an RDS?

### ISSUE THREAD

**Issue by tovbinm** [terraform-aws-modules/terraform-aws-rds#267]
AWS currently offers [RDS Data API](https://docs.aws.amazon.com/cli/latest/reference/rds-data/execute-statement.html) to execute arbitrary SQL statements. 

What would it take to add support for it? Are there any existing alternatives?

**Comment by antonbabenko** [comment]
AFAIK, Terraform AWS provider still does not support this. Also, I am not sure how it can be integrated with the Terraform provisioning lifecycle (what should happen when such a resource is deleted?).

**Comment by tovbinm** [comment]
In a way, it's an application level concern and should be handled there (e.g [Flyway](https://flywaydb.org/documentation/getstarted/how)), since it goes beyond the AWS resource configuration. On the other hand, some RDS config, such as user creation and perms should happen only once. We currently do a hack like this for Kong proxy which is super annoying https://github.com/faros-ai/terraform-aws-kong/blob/main/cloud-init.sh#L75

**Comment by bryantbiggs** [comment]
I agree @tovbinm that this is an application level concern and not best suited for the module at this time
