### ISSUE TITLE
RDS is destroyed on next terraform apply if snapshot_identifier is changed

### ISSUE THREAD

**Issue by robinbowes** [terraform-aws-modules/terraform-aws-rds#270]
If we restore an RDS instance from a snapshot then change the snapshot identifier, the RDS instance is deleted and re-created.

Some discussion of the issue here: https://discuss.hashicorp.com/t/rds-restored-from-snapshot-is-destroyed-on-next-terraform-apply/3693

**Comment by bryantbiggs** [comment]
closing this in favor of what is provided by the latest release of the upstream AWS provider hashicorp/terraform-provider-aws#18013
