### ISSUE TITLE
Support ignoring engine_version when automatic version upgrades are enabled

### ISSUE THREAD

**Issue by fractos** [terraform-aws-modules/terraform-aws-rds#271]
If you have `auto_minor_version_upgrade` set to `true` and the RDS is later upgraded automatically by AWS, subsequent re-applies may fail as they will try and downgrade the DB engine to that which is specified in the Terraform. The de facto solution to this has been to use the `lifecycle { ignore_changes = [engine_version] }` construct for the `aws_db_instance` resource. That is not possible when wrapping up the creation of the database in this module, however.

I would expect the same problem to exist for major version upgrades as well.

In lieu of a solution such as wildcard support for engine_version happening in the AWS provider, is there something that could be added to this module that would support ignoring the natural changes to the engine_version as AWS upgrades it?

**Comment by mbyio** [comment]
I ran into this issue, and I found that the AWS provider has a builtin way to support this now. You can specify a version like "10.1" and it will automatically ignore changes to the patch version.

**Comment by fractos** [comment]
@mbyio I shall try that, thanks!

**Comment by bryantbiggs** [comment]
thanks for the info @mbyio!

**Comment by domeales-paloit** [comment]
@mbyio Do you know if there is a particular version of the AWS provider that does the automatic ignore changes on `engine_version`?

I have a Postgres RDS created with this module (v3.5.0 because I need AWS provider v3.x.x) that has had a minor version upgrade overnight night, and the terraform plan now wants to downgrade the engine version.

**Comment by kjhosein** [comment]
> I ran into this issue, and I found that the AWS provider has a builtin way to support this now. You can specify a version like "10.1" and it will automatically ignore changes to the patch version.

Direct link to the TF docs that describes this: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#engine_version

**Comment by leoplana** [comment]
@domeales-paloit ane

> @mbyio Do you know if there is a particular version of the AWS provider that does the automatic ignore changes on `engine_version`?
> 
> I have a Postgres RDS created with this module (v3.5.0 because I need AWS provider v3.x.x) that has had a minor version upgrade overnight, and the terraform plan now wants to downgrade the engine version.

Did you find any clue about this error? Terraform is also trying to downgrade here from Postgres 14.3 to 14.1
