### ISSUE TITLE
Postgres: apply fails due to use of Oracle character_set_name

### ISSUE THREAD

**Issue by chrisjomaron** [terraform-aws-modules/terraform-aws-rds#273]
For some reason this only occurs on some of our instances, but has a clear cause, and is triggering terraform 0.12+ trying to prevent the formation of inconsistent plans:

https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html#inaccurate-plans

**Comment by chrisjomaron** [comment]
When updating a Postgres instance, the plan will fail because of a variable meant only for Oracle instances

Error: Provider produced inconsistent final plan

When expanding the plan for
module.services.module.postgres-db.module.db_instance.aws_db_instance.this[0]
to include new values learned so far during apply, provider
"registry.terraform.io/-/aws" produced an invalid new value for
.character_set_name: was cty.StringVal(""), but now null.

This is a bug in the provider, which should be reported in the provider's own

issue tracker.

**Comment by chrisjomaron** [comment]
This  PR seems to have introduced an Oracle specific  variable  https://github.com/terraform-aws-modules/terraform-aws-rds/pull/51

The logic then excludes the use of this variable in the case of an MSSQL server instance, but does not take account of the fact is also does not apply to other engine types.

Would it make sense to code the logic the other way around, and only use the **character_set_name** where the instance type is Oracle?

**Comment by cristiansavaro** [comment]
This is indeed happening randomly for all releases from 2.15.0 to 2.20.0 !
