### ISSUE TITLE
How do we deal with importing existing resources

### ISSUE THREAD

**Issue by gayanhewa** [terraform-aws-modules/terraform-aws-rds#276]
If I am planning to use this module with terragrunt, is there a good reference I can use to see how I can use this module and import my existing resources.

**Comment by antonbabenko** [comment]
Hi!

I don't know of any complete guide related to this but there are some links that can help:
https://www.terraform.io/docs/commands/import.html + https://learn.hashicorp.com/tutorials/terraform/state-import

And one related to Terragrunt:
https://github.com/gruntwork-io/terragrunt/issues/727

If you will have questions related to Terragrunt, please consider asking here - https://community.gruntwork.io/

**Comment by gayanhewa** [comment]
👍🏼 Thanks @antonbabenko I managed sort it out. Given terragrunt is just a wrapper over terraform. I was able to do a 

`terragrunt import` for the resource directly. I just had to figure out the resource naming that would be used when we use the module. And I was able to do that with a simple `terragrunt plan`
