### ISSUE TITLE
I am unable to pass the parameters of parameter group from a variable to module. Is there a specific format that I need to use to pass the "name & value" of db_parameter_group

### ISSUE THREAD

**Issue by phanindra2407** [terraform-aws-modules/terraform-aws-rds#28]
@antonbabenko @khosrow https://github.com/terraform-aws-modules/terraform-aws-rds/blob/7d1ad3627e860afa8d99d9e732af289f5a1983dc/modules/db_parameter_group/main.tf#L11

**Comment by khosrow** [comment]
@phanindra2407 How are you passing your parameters? 

I have a working setup with the following variables passed to the module:

```
module "db" {
    source = "terraform-aws-modules/rds/aws"
    engine            = "postgres"
    engine_version    = "9.6.3"
    family = "postgres9.6"
    # some stuff removed here for brevity

    parameters = [
        { 
            name = "client_encoding",
            value = "utf8"
        }
    ]
}
```

**Comment by phanindra2407** [comment]
Below is the way I am trying to code.
module "db" {
    source = "terraform-aws-modules/rds/aws"
    engine            = "postgres"
    engine_version    = "9.6.3"
    family = "postgres9.6"

parameters = ["${var.db_parameters}"]
}

##Passing varibales ##
variable "db_parameters" {
type = "list"
default = [
{
name = "log_connections"
value = 1
}
{
name = "pg.audit"
value = "pg_audit"
}
]
}

I will need to modify these parameters frequently. so cannot hardcode them in the module.

**Comment by antonbabenko** [comment]
I think the code which @khosrow is writing is correct but the error can be is that you pass incorrect parameters (check AWS RDS documentation for details). This is what I got when I run your code:

```
* aws_db_parameter_group.this: Error modifying DB Parameter Group: InvalidParameterValue: Could not find parameter with name: pg.audit
	status code: 400, request id: c8a64a1a-aaa6-42a8-99ff-fd04747658ee
```

If you could update `examples/complete/postgres` with the failing code which should be actually working then we can have another look. Closing for now.
