### ISSUE TITLE
prefix_name should be optional

### ISSUE THREAD

**Issue by akdj** [terraform-aws-modules/terraform-aws-rds#280]
Hi, could you please make `prefix_name` optional? 
Because I create my RDS instance manually a long time ago, then now I am using Terraform, I try to import my RDS instance because it is for used a production environment infrastructure. 

But manually, I didn't add a `prefix_name` on AWS and there is no possibility to modify and add one manually on the AWS platform. And the issue is after import my instance in the state and using your module, it asks me to force to replace my instance because of a new `prefix_name` attribute will be added. 

`prefix_name` should be optional.

**Comment by cesarpball** [comment]
Hello,
Have you try?

`use_parameter_group_name_prefix = false`

**Comment by akdj** [comment]
Yes, but I am talking about the `aws_db_subnet_group`'s `prefix_name`

**Comment by kashyn89** [comment]
Same probleme here even if i set option_group_description or similiar

**Comment by bryantbiggs** [comment]
hi all, we are working on this. we have #302 and #304 completed so far and the last is the subnet group - stay tuned!

**Comment by kostiukolex** [comment]
Hello @bryantbiggs 
  
``parameter_group_name`` is required now and default value of ``parameter_group_use_name_prefix`` is ``true``
At the same time ``local.parameter_group_name_id`` uses ``var.parameter_group_name``, when ``db_parameter_group`` was created using ``name_prefix``

I could set ``parameter_group_use_name_prefix`` to ``false``, but i want to use ``name_prefix`` that is impossible now.

**Comment by bryantbiggs** [comment]
hi @kostiukolex - please try v2.26.0 which was just released when you get a chance

**Comment by kostiukolex** [comment]
@bryantbiggs thanks a lot!
