### ISSUE TITLE
Backward compatible for skip creating the optional group for PostgreSQL

### ISSUE THREAD

**Issue by cageyv** [terraform-aws-modules/terraform-aws-rds#309]
## Description

Version v2.24.0  contains changes that are not backward compatible. If the optional group for PostgreSQL was created earlier, a new version will require it to be removed. Removing the optional group will require additional steps.

## How to reproduce
- Create RDS PostgreSQL with the optional group using version v2.23.0 (or previous)
- Update module to version v2.24.0 (or newer)
- Run 'terraform apply'
```
  # module.db_default.module.db_option_group.aws_db_option_group.this[0] will be destroyed
  - resource "aws_db_option_group" "this" {
      - arn                      = "arn:aws:rds:eu-central-1:108859834221:og:complete-postgresql-default-20210310182549840800000003" -> null
      - engine_name              = "postgres" -> null
      - id                       = "complete-postgresql-default-20210310182549840800000003" -> null
      - major_engine_version     = "11" -> null
      - name                     = "complete-postgresql-default-20210310182549840800000003" -> null
      - name_prefix              = "complete-postgresql-default-" -> null
      - option_group_description = "complete-postgresql-default option group" -> null
      - tags                     = {
          - "Environment" = "dev"
          - "Name"        = "complete-postgresql-default"
          - "Owner"       = "user"
        } -> null

      - timeouts {
          - delete = "15m" -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```
- Waiting for error
```
Error: Error Deleting DB Option Group: InvalidOptionGroupStateFault: The option group 'complete-postgresql-default-20210310182549840800000003' cannot be deleted because it is in use.
        status code: 400, request id: 13a154ab-77cb-4eae-bdf0-470963822a91
```
- Try from AWS Managment Console
![Selection_20210311_0001](https://user-images.githubusercontent.com/51059484/110680301-02504c00-820b-11eb-926b-d483fd609440.jpg)
![Selection_20210311_0002](https://user-images.githubusercontent.com/51059484/110680309-04b2a600-820b-11eb-9650-cbe862e793fd.jpg)

**Comment by isilweo** [comment]
It also affects MySQL DB. 
Workaround If someone wants to remove old group is that you need to change DB Options and set Backup retention period to 0 and after removing change it back - more info here https://github.com/hashicorp/terraform-provider-aws/issues/4597

**Comment by mwhiter** [comment]
I am also facing this issue, and the workaround posted above doesn't seem to work at all.

My databases have a backup retention period of 0 days, the `skip_final_snapshot` option was set to false, and on AWS I manually assigned the option groups for the DBs to be the default mysql option groups. I also tried forcing the version of the AWS RDS module to v2.23.0. No luck - I am unable to delete option groups, and Terraform tries to do this every single run, causing it to fail.

**Comment by tovbinm** [comment]
I am facing the same issue. Why is it trying to delete `aws_db_option_group` in the first place?

**Comment by cageyv** [comment]
@tovbinm, the description is not a big problem. 
You can pass the old format to var.option_group_description and there will be no changes/errors.

**Comment by tovbinm** [comment]
So what's the recommendation here?

**Comment by cageyv** [comment]
@tovbinm,
`create_db_option_group = false` + `terraform state rm ...` for previous created resource

**Comment by tovbinm** [comment]
Got it. Worked!

**Comment by chancez** [comment]
This is unfortunate. The description change should have been reverted and the description change should have been done in 3.0. Defaults should not change without a major version bump.

**Comment by lobsterdore** [comment]
This has just bitten me as well, I am not sure why this was done so clumsily. Even if you specify ```create_db_option_group = false``` and you delete the option group from TF state you are left with a DB instance that still uses the orphaned option group, to fix this you have to use the AWS CLI like so (it can't be done via the GUI):

```aws ds modify-db-instance --db-instance-identifier [NAME] --option-group-name default:postgres-12 --apply-immediately```

Replace ```default:postgres-12``` as appropriate.

This module is great but this sort of breaking change should have been handled better with an option to keep the group or handle the clean more gracefully, most people will be using a pipeline to deploy changes so asking users to apply manual clean steps like this is not great.
