### ISSUE TITLE
Regression with db_subnet_group for replicas

### ISSUE THREAD

**Issue by JanKoppe** [terraform-aws-modules/terraform-aws-rds#316]
## Description
Hello,

it seems like 1245fac0c34e09e3145fa0f1a6084c9465097273 broke working with DB replicas. I'm getting the following error even when trying to run the provided `examples/replica-mysql`:

```
terraform-aws-rds/examples/replica-mysql on  master took 3s
➜ terraform apply

Error: Error in function call

  on ../../main.tf line 2, in locals:
   2:   db_subnet_group_name = coalesce(var.db_subnet_group_name, module.db_subnet_group.this_db_subnet_group_id)
    |----------------
    | module.db_subnet_group.this_db_subnet_group_id is ""
    | var.db_subnet_group_name is null

Call to function "coalesce" failed: no non-null, non-empty-string arguments.

```
As far as I understand the docs (and it's even mentioned in some comments) replicas in the same region should not have a subnet group defined on the resource. The recent change assumes that a subnet group must always be defined, though.

## Versions

 - Terraform:
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.32.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
 - Provider(s):
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.32.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
 - Module:

## Reproduction
Checkout the repository, and run the `examples/replica-mysql` code.

## Expected behavior
Replicas should work without any subnet group defined.

## Actual behavior
The code requires either a db_subnet_group_name to be defined, or a db subnet group to be created with the db_subnet_group submodule.

**Comment by davidkam** [comment]
Temporary workaround, add this to the replica module block:
`db_subnet_group_name = module.master.this_db_subnet_group_id`

**Comment by antonbabenko** [comment]
Please use [v2.31.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.31.0) which has been just released.
