### ISSUE TITLE
parameter_group_name expects string but receives a list

### ISSUE THREAD

**Issue by horsey** [terraform-aws-modules/terraform-aws-rds#32]
```Error: Error refreshing state: 1 error(s) occurred: * module.production.module.db.module.db_instance.var.parameter_group_name: variable parameter_group_name in module production.db.db_instance should be type string, got list```

Terraform version:
Terraform v0.11.1
+ provider.aws v1.5.0

**Comment by antonbabenko** [comment]
Please check this answer: https://github.com/terraform-aws-modules/terraform-aws-rds/issues/28#issuecomment-346982502

If the problem still persists, share your real piece of code in this issue.

**Comment by antonbabenko** [comment]
My bad. Issue #31 and #32 were related, and they are now fixed in [v1.5.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/tag/v1.5.0)
