### ISSUE TITLE
Fix: RDS Read Replica - Do not create random password module is created as a read replica

### ISSUE THREAD

**Issue by bondezbond** [terraform-aws-modules/terraform-aws-rds#324]
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/a853247232927c6ec62c9264c45cd377f899ce74/main.tf#L12-L17

This isn't really an error. Wanted to cleanup where when this module is created for a read replica we don't create a hanging random password resource

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.0 :tada:
