### ISSUE TITLE
Question: How to import RDS restored from backup to terraform state

### ISSUE THREAD

**Issue by lukoyanov** [terraform-aws-modules/terraform-aws-rds#325]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
We use this provider to provision our rds instances and now I wonder if we at some point will be forced to restore one of our rds from backup which creates brand new rds instance (we use aws backups for that) how can we "attach" newly created instance to our terraform state?

## Describe the solution you'd like.
Some guide how to import rds instance restored from backup to terraform state.

## Describe alternatives you've considered.
None

## Additional context
None

**Comment by bryantbiggs** [comment]
hi @lukoyanov - this seems more like a "how do I do X in terraform" and less of a concern of the module. to answer your question, yes you can import resources with `[terraform import xxx](https://www.terraform.io/docs/cli/import/index.html)` commands. however, if you want to create a new RDS instance form a snapshot, the module already offers this functionality https://github.com/terraform-aws-modules/terraform-aws-rds/blob/a853247232927c6ec62c9264c45cd377f899ce74/variables.tf#L75
