### ISSUE TITLE
Error creating DB Subnet Group: InvalidSubnet: Subnet IDs are required

### ISSUE THREAD

**Issue by alanq** [terraform-aws-modules/terraform-aws-rds#326]
## Description

After upgrading terraform from 0.12 to v0.13.6, I get:
```
module.db.module.db_subnet_group.aws_db_subnet_group.this[0]: Creating...

Error: Error creating DB Subnet Group: InvalidSubnet: Subnet IDs are required.
	status code: 400, request id: 42343266-b20a-4a22-8079-9e0ee7a6eda2

  on .terraform/modules/db/modules/db_subnet_group/main.tf line 8, in resource "aws_db_subnet_group" "this":
   8: resource "aws_db_subnet_group" "this" {
```

on terragrunt apply

My code is setting the `db_subnet_group_name`, which lists subnets in the .tfstate file json.
This had been sufficient. Is there a change that requires `subnet_ids` to be set directly instead?

## Versions
```
terragrunt providers -version
Terraform v0.13.6
+ provider registry.terraform.io/-/aws v3.35.0
+ provider registry.terraform.io/-/random v3.1.0
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Code Snippet to Reproduce
```
module "db" {
  source  = "terraform-aws-modules/rds/aws"
  version = "~> v2.0"

  identifier              = local.full_id
  engine                  = "postgres"
  db_subnet_group_name = local.db_subnet_group
```
Thanks

**Comment by bryantbiggs** [comment]
@alanq please checkout the examples https://github.com/terraform-aws-modules/terraform-aws-rds/blob/a853247232927c6ec62c9264c45cd377f899ce74/examples/complete-postgres/main.tf#L86

if you are wanting the module to create the subnet group for you, then you need to provide the subnet IDs. if you are wanting to use an existing subnet group, then set `create_db_subnet_group = false`

**Comment by alanq** [comment]
Thank you @bryantbiggs.
