### ISSUE TITLE
Missing sensitive values for outputs when upgrading to Terraform 0.15

### ISSUE THREAD

**Issue by dynamike** [terraform-aws-modules/terraform-aws-rds#328]
## Description

We are in the process of testing out Terraform 0.15 for some of our services and came across an error with this module. 

## Versions

 - Terraform: 0.15

 - Provider(s): 
   - provider registry.terraform.io/hashicorp/aws v3.37.0
   - provider registry.terraform.io/hashicorp/random v3.1.0

 - Module: 2.34.0

## Reproduction

1. Run `terraform plan` on Terraform 0.14.x with an existing instance of this module with 0.14 and ensure no changes.
2. Upgrade local Terraform CLI to 0.15.0 
3. Run `terraform plan` and get the following error
```
╷
│ Error: Output refers to sensitive values
│
│ on .terraform/modules/db/modules/db_instance/outputs.tf line 71:
│ 71: output "this_db_instance_name" {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
╵
╷
│ Error: Output refers to sensitive values
│
│ on .terraform/modules/db/modules/db_instance/outputs.tf line 76:
│ 76: output "this_db_instance_username" {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```

## Expected behavior
No changes in Terraform plan 

## Actual behavior
Error listed above around sensitive values associated with outputs.

## Additional context
I suspect this relates fo some new changes around sensitive outputs in Terraform 0.15 . See https://www.terraform.io/upgrade-guides/0-15.html#sensitive-output-values. I'll likely circle back to this and submit a fix soon if no one else gets to it first.

**Comment by bryantbiggs** [comment]
hmm, this looks like either route we go is a breaking change:
1. explicitly set the output as sensitive from the module
2. use the `nonsensitive()` function which is only available from v0.14 https://www.terraform.io/docs/language/functions/nonsensitive.html

I suspect we'll have to probably look at option 1 as its less of an impact - other convos about this are happening over at https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/issues/212

@antonbabenko any thoughts?

**Comment by antonbabenko** [comment]
Definitely option 1. Less impact is better. We are still increasing the version requirements to Terraform 0.13 across all modules and I don't think we are ready to think about 0.14 features in the modules just yet. :)

There was a similar fix in the IAM module recently - https://github.com/terraform-aws-modules/terraform-aws-iam/pull/148/files#diff-2b63a586906b18479b11c4c8ec84dd24ebcad3b93d25aae7194717582c3fd6a2R44

`nonsensitive()` is a function that should be primarily used on the user's side and not in the modules, if I understand the logic correctly.

**Comment by dynamike** [comment]
I was also planning to do 1) if y'all didn't get to it first. :) thanks for the quick response

**Comment by antonbabenko** [comment]
[v2.35.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.35.0) has been just released.

Thanks @bryantbiggs !

**Comment by dynamike** [comment]
We pulled in the update, but are still seeing one error related to the instance name 

```

Error: Output refers to sensitive values

  on .terraform/modules/db/modules/db_instance/outputs.tf line 71:
  71: output "this_db_instance_name" {

Expressions used in outputs can only refer to sensitive values if the
sensitive attribute is true.
```
