### ISSUE TITLE
While creating MySQL RDS with Replica with IOPS  "invalidparametercombination" error

### ISSUE THREAD

**Issue by prashantduggal** [terraform-aws-modules/terraform-aws-rds#334]
Below error is thrown while creating mysql rds with iops.

Storage size and iops are both supplied in code.

With GP2, there is no error. Also, after provisioning with GP2, I can successfully change storage to IOPS, but while creation it throws error.

I tried Terraform v12, v13, v 15 with provider > 2.49

invalidparametercombination: you must specify both the storage size and iops when modifying the storage size or iops on a db instance that has iops.

**Comment by prashantduggal** [comment]
Forgot to mention - all the components get successfully created but terraform state file gets tainted for replica instance.

After doing terraform plan or apply, it suggests to destroy and recreate the resource. However, it keeps repeating over and over.

It looks like provider doesn't pass allocated_storage and Iops variable along with creation command or modification command.

**Comment by bryantbiggs** [comment]
hi @prashantduggal - please try with the latest module if you can and let us know if your issue still persists
