### ISSUE TITLE
Changing instance type does nothing

### ISSUE THREAD

**Issue by kristijorgji** [terraform-aws-modules/terraform-aws-rds#337]
## Description

I created one rds instance for mysql and worked fine with initial value
`instance_class    = "db.t2.micro"`

Then I changed to t3.micro
`instance_class    = "db.t3.micro"`

And applied, apply went through fine and in state instance class was changed to db.t3.micro but no change was done in aws.

## Versions

 - Terraform:
 terraform -v
Terraform v0.14.7

 - Provider(s):
provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.36.0"

## Expected

I expected to see in AWS the RDS instance in modifying state and change of instance type to the db.t3.micro as specified.

**Comment by bryantbiggs** [comment]
most changes are scheduled to happen during the maintenance window unless you specify that the changes should be applied immediately https://github.com/terraform-aws-modules/terraform-aws-rds/blob/66336d9c489c4e318799219a7ec5584efdae70be/variables.tf#L192
