### ISSUE TITLE
inputs removed in v2.25.0 break variable contract in a minor release

### ISSUE THREAD

**Issue by rvandegrift** [terraform-aws-modules/terraform-aws-rds#340]
## Description

Some inputs were removed in v2.25.0 that were previously present in the v2 series.  This breaks the API exposed by the module's variables.  Since terraform generally follows semver conventions, a break in a minor release is unexpected.  It also breaks reasonable uses of terraform's pessimistic version match, such as `~> 2.0`.

The break was documented in the PR at https://github.com/terraform-aws-modules/terraform-aws-rds/pull/304 - but for some reason the following release was not 3.0.

This bug report is a few months late, since I didn't pull an new version for a while.  So I don't know if any resolution is really worth the effort.  But as a user, it'd be nice to depend on the expectations that terraform sets for modules.

**Comment by bryantbiggs** [comment]
apologies for this disruption
