### ISSUE TITLE
Call to function "coalesce" failed: no non-null, non-empty-string arguments.

### ISSUE THREAD

**Issue by thpang** [terraform-aws-modules/terraform-aws-rds#341]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

### Versions -
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.40.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.0

### Modules -

tf init    
Initializing modules...
Downloading terraform-aws-modules/rds/aws 3.0.0 for db...
- db in .terraform/modules/db
- db.db_instance in .terraform/modules/db/modules/db_instance
- db.db_option_group in .terraform/modules/db/modules/db_option_group
- db.db_parameter_group in .terraform/modules/db/modules/db_parameter_group
- db.db_subnet_group in .terraform/modules/db/modules/db_subnet_group
Downloading terraform-aws-modules/eks/aws 16.0.0 for eks...
- eks in .terraform/modules/eks
- eks.fargate in .terraform/modules/eks/modules/fargate
- eks.node_groups in .terraform/modules/eks/modules/node_groups
Downloading terraform-aws-modules/iam/aws 4.1.0 for iam_policy...
- iam_policy in .terraform/modules/iam_policy/modules/iam-policy
- jump in modules/aws_vm
- kubeconfig in modules/kubeconfig
- nfs in modules/aws_vm
- vpc in modules/aws_vpc

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 2.49.0, >= 3.22.0, >= 3.35.0, >= 3.37.0, 3.40.0"...
- Finding terraform-aws-modules/http versions matching ">= 2.3.0"...
- Finding hashicorp/kubernetes versions matching ">= 1.11.1, 2.2.0"...
- Finding hashicorp/template versions matching "2.2.0"...
- Finding hashicorp/external versions matching "2.1.0"...
- Finding hashicorp/random versions matching ">= 2.1.0, >= 2.2.0, >= 3.1.0, 3.1.0"...
- Finding latest version of hashicorp/cloudinit...
- Finding hashicorp/local versions matching ">= 1.4.0, 2.1.0"...
- Finding hashicorp/null versions matching "3.1.0"...
- Installing hashicorp/null v3.1.0...
- Installed hashicorp/null v3.1.0 (signed by HashiCorp)
- Installing hashicorp/kubernetes v2.2.0...
- Installed hashicorp/kubernetes v2.2.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)
- Installing hashicorp/external v2.1.0...
- Installed hashicorp/external v2.1.0 (signed by HashiCorp)
- Installing hashicorp/cloudinit v2.2.0...
- Installed hashicorp/cloudinit v2.2.0 (signed by HashiCorp)
- Installing hashicorp/aws v3.40.0...
- Installed hashicorp/aws v3.40.0 (signed by HashiCorp)
- Installing terraform-aws-modules/http v2.4.0...
- Installed terraform-aws-modules/http v2.4.0 (self-signed, key ID B2C1C0641B6B0EB7)
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
- Installing hashicorp/local v2.1.0...
- Installed hashicorp/local v2.1.0 (signed by HashiCorp)

## Reproduction
1. Create a module using this source: 
```
  source  = "terraform-aws-modules/rds/aws"
  version = "3.0.0" # Or any version between 2.28 - 3.0.0. Version 2.27.0 has no errors.
```
2. Set the following variables to `false`
```
  create_db_instance        = false
  create_db_subnet_group    = false
  create_db_parameter_group = false
  create_db_option_group    = false
```
3. Run the following `tf apply`

You will observe the following error:
```
│ Error: Error in function call
│ 
│   on .terraform/modules/db/main.tf line 3, in locals:
│    3:   db_subnet_group_name = var.replicate_source_db != null ? null : coalesce(var.db_subnet_group_name, module.db_subnet_group.db_subnet_group_id)
│     ├────────────────
│     │ module.db_subnet_group.db_subnet_group_id is ""
│     │ var.db_subnet_group_name is null
│ 
│ Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```
### Code Snippet to Reproduce
Supplied above

## Expected behavior
If one does not have the `create_db_subnet_group` variable set to `true`, there should be no failure.

This behavior changed between versions starting with version `2.28.0` of this module. The addition of the `coalesce` function in place of the if logic is failing given both variables have default values of either `null` or and empty string `""`

The error states the file and line number this would be addressed.

## Actual behavior
Error shown above is created.

### Terminal Output Screenshot(s)
Shown in sample above.

**Comment by evanstachowiak** [comment]
Not sure if this fixes your problem @thpang , but I had the same issue and opened a PR here: https://github.com/terraform-aws-modules/terraform-aws-rds/pull/335

**Comment by thpang** [comment]
@evanstachowiak that is what's missing and has been since v2.28.0. I'll try that hoping that PR gets pulled in soon. Thx.

**Comment by bryantbiggs** [comment]
#335 won't solve it either. I guess at this point we'll have to set a default name as a fallback in the coalesce

**Comment by thpang** [comment]
@bryantbiggs Yeah the logic is a bit off. But modified like this:
```
db_subnet_group_name = var.replicate_source_db != null ? null : var.create_db_subnet_group == false ? null : coalesce(var.db_subnet_group_name, module.db_subnet_group.db_subnet_group_id)
```
This was what is missing the check for the `create_db_subnet_group` flag. Testing now and things look promising. I'll update in #335 as well.

**Comment by bryantbiggs** [comment]
check out #342 - I believe it solves this issue and then some
