### ISSUE TITLE
unable to use lifecycle block in the module.  Pls guide me with example. 

### ISSUE THREAD

**Issue by mkanna** [terraform-aws-modules/terraform-aws-rds#343]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

**Comment by mkanna** [comment]
lifecycle {
    ignore_changes = [
      "snapshot_identifier",
    ]
}

**Comment by antonbabenko** [comment]
This is not supported by Terraform.

**Comment by mkanna** [comment]
Hello, Thank you for replying back.  Could you please help in understanding why it is not possible to use lifecycle block in this module? with TF resources it is straightforward but unable to understand the complexity behind using lifecycle block with the AWS rds module.  
Could you please point me to the link if this has already been raised and closed?  

Thanks for your time.

**Comment by antonbabenko** [comment]
This is a limitation of Terraform, we can't do anything about it here in the module. Here are the main issues with solid details - https://github.com/hashicorp/terraform/issues/27360
https://github.com/hashicorp/terraform/issues/4149

**Comment by g4rb1** [comment]
@mkanna as an alternative, you can just remove the `snapshot_identifier` argument from your module's calls and your instances won't be affected. Not ideal but the best option.
https://github.com/hashicorp/terraform-provider-aws/pull/18013/files
