### ISSUE TITLE
InvalidParameterCombination: The DB instance and EC2 security group are in different VPCs

### ISSUE THREAD

**Issue by avirtual** [terraform-aws-modules/terraform-aws-rds#344]
## Description
When trying to deploy a pgsql database, the database ends up on the default vpc.

## Versions

 - Terraform:
0.15.3
 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.2.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

 - Module: aws-rds

I am attempting to deploy a pg database, I created the SG, passed the proper subnet_ids and also `replicate_source_db = "" ` since I am not replicating any existing db.
The result is ```Error: Error creating DB Instance: InvalidParameterCombination: The DB instance and EC2 security group are in different VPCs. The DB instance is in vpc-07c6d3fdd59e4d972 and the EC2 security group is in vpc-0d8a5f4c135094414
│ 	status code: 400, request id: a63dc952-1d7f-4dfb-b542-1bb656ed7392
│ 
│   with module.master.module.db_instance.aws_db_instance.this[0],
│   on ../terraform-aws-rds/modules/db_instance/main.tf line 20, in resource "aws_db_instance" "this":
│   20: resource "aws_db_instance" "this" {```

The culprit seems to be https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/main.tf#L3
`locals {  db_subnet_group_name = var.replicate_source_db != null ? null : coalesce(var.db_subnet_group_name, module.db_subnet_group.db_subnet_group_id, var.identifier)`

So `db_subnet_group_name   = local.db_subnet_group_name` will set db_subnet_group_name to null, which results in the instance being attached to the default vpc.
If i pass `replicate_source_db=null` the result is `Error: Error creating DB Instance: DBInstanceNotFound: The source instance could not be found: null
│ 	status code: 404, request id: `

**Comment by gricasaws** [comment]
@avirtual 
hey man did you figure out how to work around  your issue? 
I have similar error ` Error: Error creating DB Instance: InvalidParameterCombination: The DB instance and EC2 security group are in different VPCs.`
I deployed the modules "pg.DB+ read replica" in the same region, But when I am trying to deploy a Read Replica from the source pg.DB in a different region I get `InvalidParameterCombination`. Hardcoded sec-grp; subnetGroupName; subnetIds. Still having same error. IDK what am I missing , if anyone can point to something.
Thank you!

**Comment by bryantbiggs** [comment]
without a reproduction we won't be able to provide much help or insight into the issues faced
