### ISSUE TITLE
var identifier has no default

### ISSUE THREAD

**Issue by jbragdon1** [terraform-aws-modules/terraform-aws-rds#347]
## Description

I'm attempting to omit the variable "identifier". The expected behavior is a randomly generated ID provided by AWS. The error I see is that identifier is a required variable. 

## Versions

 - Terraform: v1.0.0

- provider registry.terraform.io/hashicorp/aws v3.47.0
- provider registry.terraform.io/hashicorp/random v3.1.0

 - Module:

## Reproduction

Omit idenfier to any example of launching RDS. 

## Expected behavior
Code passes validation and plan with an omitted identifier variable - and produces an RDS instance with a randomly assigned identifier. 

## Actual behavior

```
│ Error: Missing required argument
│
│   on rds.tf line 2, in module "rds":
│    2: module "rds" {
│
│ The argument "identifier" is required, but no definition was found.

```

**Comment by bryantbiggs** [comment]
correct - based on logic within the module, the identifier is required as a fallback name used throughout the module.  if you check `main.tf` for `identifier` you will see it used throughout and therefore the module has made this a required variable, even though the `aws_db_instance` resource itself allows it to be optional

**Comment by jbragdon1** [comment]
@bryantbiggs - then would it be possible to update the verbiage around this variable? 

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/variables.tf#L2

"The name of the RDS instance, if omitted, Terraform will assign a random, unique identifier"

This, to me, reads like if we leave this variable blank - it will still work.

**Comment by bryantbiggs** [comment]
Yes! You are correct, the variable description should be updated, 100%
