### ISSUE TITLE
Error: Unsupported argument

### ISSUE THREAD

**Issue by Hardik2607** [terraform-aws-modules/terraform-aws-rds#352]
## Description
Postgres deployment is not working and not able to deploy the RDS instance through postgres. Each and every element gives **Error: Unsupported argument** while planning or applying terraform code.

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

**Comment by antonbabenko** [comment]
Please complete the template when open an issue:

> Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

Also, include `Code Snippet to Reproduce`

**Comment by Hardik2607** [comment]
![image](https://user-images.githubusercontent.com/62460135/130071316-e48333de-70b4-458f-ae0a-d8eab27f172d.png)
Getting above errors when using the module [complete-postgres](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/v3.3.0/examples/complete-postgres/main.tf)

**Comment by antonbabenko** [comment]
If you want to run example code, you should check out the module source and run commands specified in the [usage section](https://github.com/terraform-aws-modules/terraform-aws-rds/tree/v3.3.0/examples/complete-postgres#usage).

All arguments used in the `complete-postgres` example are already specified there.

**Comment by bryantbiggs** [comment]
closing for now - please provide more info and a sample of your configuration so that we can help troubleshoot the issue you are facing

**Comment by Hardik2607** [comment]
Kindly find the [Link](git@github.com:Hardik2607/Psotres_issue.git) for the code that I am trying the deploy as test case. and kindly suggest if any changes are required.

**Comment by bryantbiggs** [comment]
you need to set the proper source location https://github.com/Hardik2607/Psotres_issue/blob/e1bce86803c9e06a174e2e1b9583b4cdc60e959c/rds.tf#L2

**Comment by Hardik2607** [comment]
As Suggested have change the source https://github.com/Hardik2607/Psotres_issue/blob/f7bf9dc623320bde0d0597f9db36457a4e7f711b/rds.tf#L2

![image](https://user-images.githubusercontent.com/62460135/130227552-789cd306-1f83-4293-90c6-961447aa59c6.png)
If Module Source has issue then the Initialization of Module should fail but the ```terraform init``` is returning successful message and the ```terraform plan``` is failing

**Comment by bryantbiggs** [comment]
I'm sorry but I think you need to go expand your understanding of Terraform in general a bit more, these questions are not related to this module but more of "how do I use Terraform"
1. you updated the source to point to the example directory which won't work, its not setup that way. you should point to the module root
2. you cannot just copy+paste from an example and expect it to work locally for you. the use of local variables and other supporting resources within the example will need to be adjusted accordingly for your setup
