### ISSUE TITLE
restore_to_point_in_time for RDS SQL Server instance engine

### ISSUE THREAD

**Issue by Roxyrob** [terraform-aws-modules/terraform-aws-rds#362]
## Is your request related to a new offering from AWS?
Restore to Point In Time seems supported by RDS SQL Server since initial release.

## Describe the solution you'd like.
This module can easily support Restore to Point In Time for AWS RDS SQL Server Instance supported feature as do for not mssql Intance `false == local.is_mssql`

This feature is key for RDS SQL Server Instance Disaster Recovery strategy.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.0 :tada:
