### ISSUE TITLE
Error creating DB Instance: InvalidParameterCombination: IAM role provided is not valid, please check that the role exists and has the correct policies

### ISSUE THREAD

**Issue by MichaelMosayev** [terraform-aws-modules/terraform-aws-rds#365]
Trying to deploy a mysql database,  getting "Error creating DB Instance: InvalidParameterCombination: IAM role provided is not valid, please check that the role exists and has the correct policies"
Since the last update, I'm having this error with the same configuration as before. I've tried a clean environment, and the issue persists.

**Comment by michaelallcloud** [comment]
Looks like the domain variable at the db instance module caused this issue.

**Comment by MichaelMosayev** [comment]
Looks like the domain variable at the db instance module causing this issue.

**Comment by MichaelMosayev** [comment]
It's seems like like the issue was with global variable from my side.
issue can be closed.
