### ISSUE TITLE
Creating multiple RDSs with create-role-monitor it will throw an exception that the role exists cause it's used with hardcoded name in the code, the name should be depend to some variable

### ISSUE THREAD

**Issue by ananhagyahya** [terraform-aws-modules/terraform-aws-rds#367]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

**Comment by bryantbiggs** [comment]
there is a variable for the role name https://github.com/terraform-aws-modules/terraform-aws-rds/blob/e38aaced17278567973dad4980fae8757d6a1265/modules/db_instance/main.tf#L216
