### ISSUE TITLE
Name variable should be optional

### ISSUE THREAD

**Issue by analytically** [terraform-aws-modules/terraform-aws-rds#37]
Error: module "db": missing required argument "name"

**Comment by antonbabenko** [comment]
Could you show the code? Also, please check `examples`.

**Comment by analytically** [comment]
From the docs: 

When creating a DB instance, some database engines require that a database name be specified. A DB instance can host multiple databases, or a single Oracle database with multiple schemas. The database name value depends on the database engine:

For the MySQL and MariaDB database engines, the database name is the name of a database hosted in your DB instance. Databases hosted by the same DB instance must have a unique name within that instance.

For the Oracle database engine, database name is used to set the value of ORACLE_SID, which must be supplied when connecting to the Oracle RDS instance.

For the Microsoft SQL Server database engine, database name is not a supported parameter.

For the PostgreSQL database engine, the database name is the name of a database hosted in your DB instance. A database name is not required when creating a DB instance. Databases hosted by the same DB instance must have a unique name within that instance.

**Comment by analytically** [comment]
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/variables.tf#L62 -> the default should be ""
