### ISSUE TITLE
Database password sensitive value

### ISSUE THREAD

**Issue by Jonathan-7** [terraform-aws-modules/terraform-aws-rds#372]
The variable for the database password should be set as a sensitive value, e.g:
variable "password" {
  description = "Password for the master DB user. Note that this may show up in logs, and it will be stored in the state file"
  type        = string
  default     = ""
  sensitive   = true
}

**Comment by bryantbiggs** [comment]
placing this on hold for the moment since it requires bumping up minimum supported version of Terraform to 0.14.x

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.0.0 :tada:
