### ISSUE TITLE
Oracle DB ReplicaMode Support

### ISSUE THREAD

**Issue by nyt-larahelenaroth** [terraform-aws-modules/terraform-aws-rds#373]
## Is your request related to a new offering from AWS?

https://github.com/hashicorp/terraform-provider-aws/issues/17991
TF has since added support for the Oracle RDS replica mode (`mounted` or `open-read-only` with default of `open-read-only`)

## Describe the solution you'd like.

It would be great to have an optional flag for this!

## Describe alternatives you've considered.

Since we cannot utilize the replica mode, we are unable to use this module and have to create our own for Oracle. 😿

**Comment by antonbabenko** [comment]
Please open a pull request with this rather simple feature.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.0 :tada:
