### ISSUE TITLE
"engine" conflicts with "replicate_source_db" in hashicorp/aws 4.0.0

### ISSUE THREAD

**Issue by baturayozcan** [terraform-aws-modules/terraform-aws-rds#377]
When trying to create a MySQL read replica, in "hashicorp/aws 4.0.0", "engine" conflicts with "replicate_source_db" since its default value is "". It should be set as "null". However, in that case, Terraform throws an error because of "is_mssql" local definition ("engine" should not be "null).

`│ Error: Conflicting configuration arguments
│ 
│   with module.db.module.db_instance.aws_db_instance.this[0],
│   on .terraform/modules/db/modules/db_instance/main.tf line 25, in resource "aws_db_instance" "this":
│   25:   engine            = var.engine
│ 
│ "engine": conflicts with replicate_source_db`

`│ Error: Invalid function argument
│ 
│   on .terraform/modules/db/modules/db_instance/main.tf line 2, in locals:
│    2:   is_mssql = element(split("-", var.engine), 0) == "sqlserver"
│     ├────────────────
│     │ var.engine is null
│ 
│ Invalid value for "str" parameter: argument must not be null.`

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.0.0 :tada:
