### ISSUE TITLE
Module wants to destroy all mssql instances

### ISSUE THREAD

**Issue by AndriMar** [terraform-aws-modules/terraform-aws-rds#381]
## Description
Whene the instance type is mssql the database is not created.

## Versions
 - Terraform:
Terraform v1.0.5
 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v4.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
 - Module:
    RDS 4.0.0
## Reproduction
Not using Workspaces
Cleared all cache 

Upgrade to V4.0.0 with engine = `sqlserver-web`
And to terraform plan
It will want to destroy the instance because of the is_mssql variable in this line
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L30
Probably some leftovers after these changes
[```Separate RDS instance resource for MSSQL/SQLServer has been removed - all engines are supported under one resource```](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/UPGRADE-4.0.md?plain=1#L11)

## Expected behavior
To not destroy the database instance

## Actual behavior
Wants to destroy the database instance

**Comment by cmd-werner-diers** [comment]
Related to this, for a new resource, the db_instance is not created for mssql

**Comment by cmd-werner-diers** [comment]
BTW The same issue persists in v4.1.0 of this module

**Comment by antonbabenko** [comment]
You will need to move/rename resource in the Terraform state file as described here at the very end - https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/UPGRADE-4.0.md#mssqlsqlserver

Please confirm that you did that.
