### ISSUE TITLE
aws_db_instance listener endpoint

### ISSUE THREAD

**Issue by aceandy1975** [terraform-aws-modules/terraform-aws-rds#387]
I can't see an option in the aws_db_instance code to extract the listener endpoint address.  This is an item created as part of a multi-az RDS for SQL Server.  Am I missing something?

**Comment by bryantbiggs** [comment]
if its not exposed by the AWS provider, then we cannot expose it here

**Comment by aceandy1975** [comment]
The details can be obtained from the aws cli using describe-db-instance and the property ListenerEndpoint

**Comment by bryantbiggs** [comment]
you will need to file a feature request here https://github.com/hashicorp/terraform-provider-aws to get this added to the provider first before we can support it here
