### ISSUE TITLE
Backward compatiblity with AWS provider 3.x

### ISSUE THREAD

**Issue by lxw2016** [terraform-aws-modules/terraform-aws-rds#389]
## Is your request related to a new offering from AWS?
Yes, we are using a lot 3rd party modules that are not ready to move to AWS provider 4.0,

## Is your request related to a problem? Please describe.
We are using this module to provision our RDS sqlserver DB, we are currently on v3.5.0, but it doesn't support restore point in time feature in this version, in the v4.0 it seems it finally support that feature, but it requires update to AWS provider 4.0, at this point we can't simply update it (we are using several other modules that are still only work with provider 3 - related to S3, subnet etc),

## Describe the solution you'd like.
Remove the hard link to the AWS provider 4.0 version restrain and allow to be used with provider 3.x and 4.x

## Describe alternatives you've considered.
Continue 3.x version stream with different branch, merge the v4.1.3 features into there with only support AWS provider 3.x

**Comment by bryantbiggs** [comment]
unfortunately we cannot do this because the attribute `db_name` (was `name` which is now deprecated) is only available in the v4 provider
