### ISSUE TITLE
Specifying availability zone?

### ISSUE THREAD

**Issue by allaire** [terraform-aws-modules/terraform-aws-rds#39]
Hi, is there a way to specify the AZ when using the main module? I see the variable in db_instance, but nothing in main.tf

Thanks

**Comment by antonbabenko** [comment]
Thanks for this issue! https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v1.12.0 has been released.

**Comment by allaire** [comment]
that was fast, thanks!

**Comment by antonbabenko** [comment]
You have night - I have day :)

**Comment by jross-ai** [comment]
Was parameter subsequently removed from the terraform-aws-rds module? If so, is there a new way to specify the AZ in the main module?
