### ISSUE TITLE
apply fails with SerializationError

### ISSUE THREAD

**Issue by robins** [terraform-aws-modules/terraform-aws-rds#390]
## Description

Ever so often the `terraform apply` would fail with the error below. I've seen it with both a 200 and a 400 response code from AWS... so don't rule out my internet connection is partly to blame.

## Versions
```
>terraform -version
Terraform v1.1.6
on windows_amd64

>terraform providers -version
Terraform v1.1.6
on windows_amd64
```

## Reproduction

This is not easily reproducible at will, but I've had 2 TF scripts fail twice (each) today owing to this error. 

## Expected behavior
A retry in case terraform couldn't understand the response of a DescribeAPI.

## Actual behavior
Terraform crashes and leaves the `apply` half-way abandoned.

### Terminal Output Screenshot(s)
```
module.replica1.module.db_instance.aws_db_instance.this[0]: Still creating... [12m41s elapsed]
module.replica1.module.db_instance.aws_db_instance.this[0]: Still creating... [12m51s elapsed]
╷
│ Error: Error retrieving DB Instances: SerializationError: failed decoding Query response
│       status code: 200, request id: xxxxxx
│ caused by: read tcp 10.55.7.234:58440->52.39.167.104:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
│
│   with module.master2.module.db_instance.aws_db_instance.this[0],
│   on ..\..\modules\db_instance\main.tf line 27, in resource "aws_db_instance" "this":
│   27: resource "aws_db_instance" "this" {
│
```

## Additional context
What is important to note is that I am having a bad day in terms of packet-loss on my home network (~5% packet loss), so unsure if this is related to that.

Googling, this appears to be more of a Windows + Golang specific error and then the request from this bug-report is to see if terraform could be more robust to catch such cases and retry if possible (at least for read-only API requests).

**Comment by bryantbiggs** [comment]
Hi @robins - I would file this with the upstream Terraform project https://github.com/hashicorp/terraform since its not related to this module
