### ISSUE TITLE
The DB instance and EC2 security group are in different VPCs

### ISSUE THREAD

**Issue by dev-minds** [terraform-aws-modules/terraform-aws-rds#395]
Hi guyz, im currently using this module to create a mssql RDS/Directory - 

TF Version: 1.1.2 
Module v4.2.0

i get this error message when i use an existing VPC/SG IDs on the inputs for both DB instance and directory_service. 

```ruby 
│ Error: Error creating DB Instance: InvalidParameterCombination: The DB instance and EC2 security group are in different VPCs. The DB instance is in vpc-045019xxxxxx and the EC2 security group is in vpc-0006xxxxxx
│       status code: 400, request id: 2a5c13aa-xxxxxxxxxxxxx
│ 
│   with module.db.module.db_instance.aws_db_instance.this[0],
│   on .terraform/modules/db/modules/db_instance/main.tf line 26, in resource "aws_db_instance" "this":
│   26: resource "aws_db_instance" "this" {
```
When i look at the proposed file line in the error message, i see that SGs ID is properly injected. 

Just wondering why and where its taking the `default VPC SGs` - 

Any help will be appreciated

**Comment by dev-minds** [comment]
Ok, got this fixed, i had to enable the `create_db_subnet_group = true` in the module caller input. Essentially if you don't enable this "aws" will use the default vpc, hereby creating conflict with the `directory_service` resource. 

It will be good to note this in the documentation. 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#db_subnet_group_name

**Comment by danihodovic** [comment]
It would be even better if this was included in the examples in the documentation. If db_subnet_group_name is specified, create_db_subnet_group should be included by default.
