### ISSUE TITLE
small typo, big consequences

### ISSUE THREAD

**Issue by mvk** [terraform-aws-modules/terraform-aws-rds#396]
## Description

while reading the variable names, I've stumbled upon a variable named `putin_khuylo`
I totally disagree with this grammar. Usually "kh" is used to describe fricative sounds, so European languages do not have this sound. It would be proper to use just "h" (huylo), or maybe "x" (xuylo).
What do you think ?
If need be I can send a PR.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

## Versions

- Module version [Required]: `v4.2.0`

- Terraform version: 

- Provider version(s):
```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.9.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/tls v3.3.0

```

## Reproduction Code [Required]

N/A

No

Yes

`rm -fr .terraform terraform.hcl.* *.tfstate`

**Comment by antonbabenko** [comment]
Thank you for the input, Max!

I took the spelling from English Wikipedia - https://en.wikipedia.org/wiki/Putin_khuylo!

I believe that people writing, reading, and proofreading the articles there just can't be wrong, so I will close this improvement for the time being.

Glory to Ukraine! 🇺🇦❤️
