### ISSUE TITLE
Add support for restoration of Automated Backups (just one line change)

### ISSUE THREAD

**Issue by jonasoneves** [terraform-aws-modules/terraform-aws-rds#397]
This parameter was added to the AWS provider in this PR and merged to the main branch on March 15:
https://github.com/hashicorp/terraform-provider-aws/pull/23086

For this to work with the module terraform-aws-modules/terraform-aws-rds, the parameter "source_db_instance_automated_backups_arn" needs to be added to the dynamic block restore_to_point_in_time, like in the example below.

[terraform-aws-rds](https://github.com/terraform-aws-modules/terraform-aws-rds)/[modules](https://github.com/terraform-aws-modules/terraform-aws-rds/tree/master/modules)/[db_instance](https://github.com/terraform-aws-modules/terraform-aws-rds/tree/master/modules/db_instance)/main.tf
```
  dynamic "restore_to_point_in_time" {
    for_each = var.restore_to_point_in_time != null ? [var.restore_to_point_in_time] : []

    content {
      restore_time                             = lookup(restore_to_point_in_time.value, "restore_time", null)
      source_db_instance_automated_backups_arn = lookup(restore_to_point_in_time.value, "source_db_instance_automated_backups_arn", null)
      source_db_instance_identifier            = lookup(restore_to_point_in_time.value, "source_db_instance_identifier", null)
      source_dbi_resource_id                   = lookup(restore_to_point_in_time.value, "source_dbi_resource_id", null)
      use_latest_restorable_time               = lookup(restore_to_point_in_time.value, "use_latest_restorable_time", null)
    }
  }
```

This will hugely simplify restoration of backups based on Automated Backups, right now I've been using an external script for that.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.3.0 :tada:
