### ISSUE TITLE
Could we support prevent_destroy in the RDS db_instance block?  

### ISSUE THREAD

**Issue by meyerkev** [terraform-aws-modules/terraform-aws-rds#399]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform]

Yes, it's possible to request prevent_destroy if we don't use this module

## Is your request related to a problem? Please describe.
There are several things that will destroy my running RDS cluster and I don't see a way to pass in lifecycle values to our db_instance resources.  

## Describe the solution you'd like.
Can we pass in the lifecycle as a value? 

db_instance_prevent_destroy = true -> `module.postgres.module.db_instance.aws_db_instance.this[0].lifecycle.prevent_destroy` is set to True

## Describe alternatives you've considered.
I could stop using this module?

## Additional context
None

**Comment by gurland** [comment]
@meyerkev how was it resolved?

The only usage I see is there https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L122

But at first glance it won't work for ignoring `snapshot_id`, for example

**Comment by meyerkev** [comment]
Honestly, I had deletion protection on the db, so it's not _great_, but I can't wipe prod by accident.
