### ISSUE TITLE
About `putin_khuylo` variable

### ISSUE THREAD

**Issue by 5er9e1** [terraform-aws-modules/terraform-aws-rds#405]
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/9299ae1e770c039bcd81ee7ae72f62216b7684f8/main.tf#L2

pretty sure that mention inside `readme` will be enough. Source code is not an opinion board.

**Comment by bryantbiggs** [comment]
Thank you for your opinion but we are not planning to make any changes at this time
