### ISSUE TITLE
Provide support for aws_db_instance_automated_backups_replication resource in the AWS Terraform provider

### ISSUE THREAD

**Issue by mbacchi** [terraform-aws-modules/terraform-aws-rds#406]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: introduced in version [4.9.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.9.0) of the Terraform provider

## Is your request related to a problem? Please describe.

No

## Describe the solution you'd like.

Add support for the [aws_db_instance_automated_backups_replication](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance_automated_backups_replication) resource in the AWS Terraform provider.

## Describe alternatives you've considered.

N/A

**Comment by bryantbiggs** [comment]
shhh

**Comment by bryantbiggs** [comment]
provided in #413
