### ISSUE TITLE
Can you provide examples of Multi AZ DB cluster?

### ISSUE THREAD

**Issue by ianeinser** [terraform-aws-modules/terraform-aws-rds#408]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

**Comment by antonbabenko** [comment]
You have to specify [`multi_az = true`](https://github.com/terraform-aws-modules/terraform-aws-rds#input_multi_az) as a module argument, and AWS RDS service will do the rest.

**Comment by rickychew77** [comment]
hi @antonbabenko, currently there were 3 deployment options based on [RDS docs here](aws.amazon.com/rds/features/multi-az/). Also can be seen in AWS console while provisioning in UI.

1. Single-AZ
2. Multi-AZ with one standby (the standby just act as failover, does not serve read traffic)
3. Multi-AZ with two readable standby 

Using `multi_az = true` seems like deploying #2 options above. Does RDS terraform provider support option #3 above? 

Saying so because I've just tried using `multi_az = true` and it was able to create with instance class `db.t3.micro` and #3 option only supports m and r classes (as seen in console UI).

**Comment by agomezvidalee** [comment]
> hi @antonbabenko, currently there were 3 deployment options based on [RDS docs here](https://aws.amazon.com/rds/features/multi-az/) (see comparison table in the link). Also can be seen in AWS console while provisioning in UI.
> 
> 1. Single-AZ
> 2. Multi-AZ with one standby (the standby just act as failover, does not serve read traffic)
> 3. Multi-AZ with two readable standby
> 
> Using `multi_az = true` seems like deploying option 2 above. Does RDS terraform provider support option 3 above?
> 
> Saying so because I've just tried using `multi_az = true` and it was able to create with instance class `db.t3.micro` and option 3 only supports m and r classes (as seen in console UI).

which engine do you deploy?

**Comment by rickychew77** [comment]
I am deploying to PostgreSQL

**Comment by agomezvidalee** [comment]
> I am deploying to PostgreSQL @agomezvidalee

I used to use "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html" value "replicate_source_db" may this helps to you "[replicate_source_db](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/UPGRADE-4.0.md#modified)"

**Comment by rickychew77** [comment]
@agomezvidalee thanks for the respond. 

That seems to be just creating replica from source DB. Read [docs here](https://aws.amazon.com/rds/features/multi-az/) (see comparison table) as my first comment above there are 3 kinds of deployments, similar to what can be seen in AWS console while creating RDS instance. 

The third option is what I want to achieve, closest thing that I can think of is to enable `multi_az` + read replica, possibly with RDA proxy. Not sure if there's just one argument to enable within `aws_db_instance`.

**Comment by agomezvidalee** [comment]
I just was using this module to deploy a mariadb instance (the master one) and then invoking the module to deploy the read one passing as parameter the master one. I guess this would work for your use case.

**Comment by magreenbaum** [comment]
I believe the resource needed for the 3rd option is [`aws_rds_cluster`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster). These [attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#rds-multi-az-cluster) are needed for multi-az cluster support. 

This option is not yet available in this module.

**Comment by ravindrasinghh** [comment]
HI,
you can use this flag multi_az = true/false.
I have created RDS previous using below module code, you can refer this link below
[](https://github.com/ravindrasinghh/module-aws-rds)
