### ISSUE TITLE
Support existing cloudwatch log group

### ISSUE THREAD

**Issue by shilpa-0** [terraform-aws-modules/terraform-aws-rds#410]
Hi,

Could you please support the usage of existing cloudwatch log groups? 

Thanks

**Comment by bryantbiggs** [comment]
Hi, what do you mean by `support the usage of existing cloudwatch log groups`? This sounds like you are trying to import a log group that was not created by Terraform to be managed by Terraform

**Comment by shilpa-0** [comment]
I wanted to create the log groups using Terraform but independently of the module.

**Comment by antonbabenko** [comment]
There is an argument `create_cloudwatch_log_group`, which you can set to `false`.

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L132
