### ISSUE TITLE
Make 'password' input variable sensitive

### ISSUE THREAD

**Issue by shilpa-0** [terraform-aws-modules/terraform-aws-rds#411]

**Comment by shilpa-0** [comment]
When will the fix for this be released?

**Comment by magreenbaum** [comment]
For visibility, I ran across this issue where this request was on hold since it would require changing the minimum supported version to terraform 0.14.x. https://github.com/terraform-aws-modules/terraform-aws-rds/issues/372

**Comment by bryantbiggs** [comment]
@magreenbaum is correct - we can bump the minimum Terraform version to 1.0 and make this change and mark it as breaking (will release as v5.0.0)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.0.0 :tada:
