### ISSUE TITLE
Allow specifying identifier_prefix for DB instances

### ISSUE THREAD

**Issue by tsndqst** [terraform-aws-modules/terraform-aws-rds#414]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: unknown but it was added [5 years ago](https://github.com/hashicorp/terraform-provider-aws/commit/8ed01f32eddb5cd769389ffca865315a29df3a72)

## Is your request related to a problem? Please describe.
We currently create DB instances using `identifier_prefix` parameter in the db_instance resource. We would like to continue using that pattern but move to this module.

## Describe the solution you'd like.
Add support for `identifier_prefix` in the db_instance module so it is similar to how name prefixes are handled in the db_subnet_group, db_parameter_group, and db_option_group modules.

## Describe alternatives you've considered.
Create a random string and concatenate it to a name and pass that as `identifier` in the db_instance resource.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.5.0 :tada:
