### ISSUE TITLE
monitoring_role_name to use prefixed/suffixed/random name instead of static string by default

### ISSUE THREAD

**Issue by damienleger** [terraform-aws-modules/terraform-aws-rds#417]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality
I don't know but this is not relevant

## Is your request related to a problem? Please describe.

When `create_monitoring_role = true` and `monitoring_role_name` is left blank then `monitoring_role_name` takes the default value `rds-monitoring-role` which overlaps in case of two terraform files using this same configuration and result in "resource already exists" error when apply terraform.

## Describe the solution you'd like.

That the default `monitoring_role_name` value be prefixed/suffixed/random such as other variables or derived from the RDS instance identifier + region. I mention region because since IAM is global and not region based on AWS, it's necessary to guarantee that IAM role is unique because it's possible to have the same RDS identifier on several different regions.

## Describe alternatives you've considered.

I've done this
```
data "aws_region" "current" {}
locals {
   identifier = "production-postgresql-v2"
}
module "production-rds_v2" {
  identifier        = local.identifier
  ...
  # Monitoring
  monitoring_role_name = "${local.identifier}_${data.aws_region.current.name}"
  create_monitoring_role = true
  ...
}
```

## Additional context

I've got this situation when trying some BCP (business continuity plan) scenario. Essentially trying to take my tf code, change the minimum to switch region, and apply it. Hence seeing the naming situation with IAM role being global described above.

**Comment by bryantbiggs** [comment]
this is now resolved in #418 - users can set `monitoring_role_use_name_prefix` to enable this functionality. This was not made the default because that would be considered a breaking change, but the ability to opt in is available now for users - thanks @magreenbaum !
