### ISSUE TITLE
db_subnet_group support for name?

### ISSUE THREAD

**Issue by allaire** [terraform-aws-modules/terraform-aws-rds#42]
Hi, I see that the `db_subnet_group` module only support `name_prefix` and not `name`. Can you shed some lights on that decision? I could probably create manually my db subnet group and pass its name to `db_subnet_group_name`, but is it recommended to have a db subnet group per rds instance, hence why name_prefix is only supported?

Thanks!

**Comment by antonbabenko** [comment]
`name_prefix` helps to create unique resources, which is important when reusing this module multiple times within the same scope (eg, single region in single AWS account where resources should be unique). `name_prefix` is preferred over `name` for the majority of resources, not just for RDS.

**Comment by danvaida** [comment]
@antonbabenko what about people that want handle the "uniqueness" themselves by using "name"?

**Comment by antonbabenko** [comment]
@danvaida Hi! :)

This should be possible to implement easier once Terraform 0.12 is ready. Currently, this module does not have this feature.
