### ISSUE TITLE
In database names hyphen is not allowed 

### ISSUE THREAD

**Issue by stratos-fasly** [terraform-aws-modules/terraform-aws-rds#425]
From this terraform module not allowed to give DB name with hyphen (-), but its allowed with to create database with hyphen from AWS console.

Error: Error creating DB Instance: InvalidParameterValue: DBName must begin with a letter and contain only alphanumeric characters.
│       status code: 400, request id: 11199d72-a991-4824-8c32-349c021a2e80, {
│   AllocatedStorage: 20,
│   AutoMinorVersionUpgrade: true,
│   BackupRetentionPeriod: 5,
│   CopyTagsToSnapshot: false,
│   DBInstanceClass: "db.t4g.large",
│   DBInstanceIdentifier: "db-uw2-augst-postgre",
│   DBName: "db-uw2-augst-postgre",
│   DBParameterGroupName: "db-uw2-augst-postgre-20220802133332704100000001",
│   DBSubnetGroupName: "db-uw2-augst-postgre",
│   DeletionProtection: false,
│   Engine: "postgres",
│   EngineVersion: "14.1",
│   MasterUserPassword: "********",
│   MasterUsername: "master",
│   MaxAllocatedStorage: 100,
│   Port: 3306,
│   PubliclyAccessible: false,
│   StorageEncrypted: true,
│   Tags: [{
│       Key: "DB-Name",
│       Value: "db-uw2-augst-postgre"
│     }]
│ }

**Comment by cuyk** [comment]
It looks like an answer from AWS API, not the module issue.

**Comment by SolidSly** [comment]
Hello @stratos-fasly, I think this question deserves a more detailed answer. What @cuyk said is true, the error is an AWS error and I don't think it is a good idea to manage all exceptions through Terraform. We should let AWS handles errors.

However, I would like to comment on your first sentence. It is **not** possible to create a RDS with a database name containing hyphens. However, it is possible that the identifier of the RDS contains hyphens. Therefore, in your example, you should rename the DBName, but you can keep the DBInstanceIdentifier as you want.

I hope my answer was clear enough. Don't hesitate to tell me you need more information.
