### ISSUE TITLE
Add support to Start/Stop RDS

### ISSUE THREAD

**Issue by ricardson** [terraform-aws-modules/terraform-aws-rds#43]
Hi in some cases like QA, Playground environment add the option to shutdown the RDS save us some money :)

AWS Docs
https://aws.amazon.com/about-aws/whats-new/2017/06/amazon-rds-supports-stopping-and-starting-of-database-instances/

Actually I'm using the AWS API to perform that with Ansible (shell module)

aws rds start-db-instance --db-instance-identifier DB_INSTANCE
aws rds stop-db-instance --db-instance-identifier DB_INSTANCE

**Comment by antonbabenko** [comment]
Yes, this is a good feature, but Terraform does not support those action as far as I know, so you should use aws-cli as you specify.

**Comment by mlescaudron** [comment]
It has been implement for EC2 instance, maybe we can implement it for RDS too ?
https://github.com/terraform-providers/terraform-provider-aws/issues/22

**Comment by ntkawasaki** [comment]
Why was this closed, can we reopen? I'd like to be able to control state with terraform as well, seeing as EC2 can do this.

**Comment by nicolasdonoso** [comment]
this will be really good for QA/DEV resources that don't need to be on 24/7

**Comment by antonbabenko** [comment]
Once this feature is available in Terraform AWS we can have support for it here in this module also. Meanwhile, you can achieve the same by using null_resource's local-exec as mentioned in https://github.com/terraform-providers/terraform-provider-aws/issues/22#issuecomment-514365075
