### ISSUE TITLE
Upgrade from v3.5 to v4+ forces deletion of module.db.module.db_subnet_group.aws_db_subnet_group.this[0]

### ISSUE THREAD

**Issue by dsunterov-barb** [terraform-aws-modules/terraform-aws-rds#430]
## Description

Once we try to upgrade AWS RDS Terraform module version from 3.5 to any 4+ version (5.3.0 included) we see in the following 
 in terraform plan:
 
 ```
  # module.db.module.db_subnet_group.aws_db_subnet_group.this[0] will be destroyed
  # (because index [0] is out of range for count)
  - resource "aws_db_subnet_group" "this" {
  <output omitted>
  }
 ```
I suppose the problem is with modules/db/modules/db_subnet_group/main.tf 
>  count = var.create ? 1 : 0

## Workaround
set create_db_subnet_group option to true, which is not clear, as it is already exists and this option is not mandatory required, according to the documentation

## Versions

- Module version [Required]:
AWS RDS Terraform module 5.3.0

- Terraform version:
Terraform v1.1.5
- Provider version(s):
AWS 4.30.0

**Comment by zahorniak** [comment]
Hi @BZakir @dsunterov-barb,
Please check the List of backward incompatible changes before upgrading to version `4.x` [UPGRADE-4.0.md](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/UPGRADE-4.0.md#upgrade-from-v3x-to-v4x)

> set create_db_subnet_group option to true, which is not clear, as it is already exists and this option is not mandatory required, according to the documentation

It's pretty clear from the docs: `create_db_subnet_group` is now set to `false` by default; was previously `true`; typically a shared DB subnet group will be used, most likely from the VPC module
