### ISSUE TITLE
Support aws_rds_global_cluster

### ISSUE THREAD

**Issue by chenrui333** [terraform-aws-modules/terraform-aws-rds#433]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform]: Yes (https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

The aws_rds_global_cluster resource [was included in 1.53.0 release](https://github.com/hashicorp/terraform-provider-aws/pull/6861)

**Comment by bryantbiggs** [comment]
its a bit confusing and we should probably add some clarifying notes in the docs between the RDS and RDS Aurora modules now, but here is an example https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/examples/global-cluster/main.tf#L35
