### ISSUE TITLE
odule "db" {   source = "terraform-aws-modules/rds/aws"    identifier = "trf_db"    engine            = "mysql"   engine_version    = "5.7.25"   instance_class    = "db.t3a.large"   allocated_storage = 5    db_name  = "trf_database"   username =  "risav_rds"   port     = "3306"

### ISSUE THREAD

**Issue by SovitRed** [terraform-aws-modules/terraform-aws-rds#434]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by antonbabenko** [comment]
https://github.com/terraform-aws-modules/terraform-aws-rds/issues/225#issuecomment-1251908550
