### ISSUE TITLE
RDS MYSQL AURORA upgrade failure

### ISSUE THREAD

**Issue by chandankashyap19** [terraform-aws-modules/terraform-aws-rds#435]
## Description

I am getting the below error while upgrading the MySQL aurora from 5.6 to 5.7 using terraform.

Error: `Failed to modify RDS Cluster : InvalidParameterCombination: The current DB instance parameter group xxxx-parameter-group is custom. You must explicitly specify a new DB instance parameter group, either default or custom, for the engine version upgrade.`

I have explicitly defined a new parameter group resource block for MySQL aurora 5.7 and it is getting created successfully but while doing rds upgrade the above error is coming.

terraform version is Terraform v1.1.4
hashicorp/aws v4.15.1

The resource block that was used to create MySQL aurora is below.

```
resource "aws_rds_cluster" 
  skip_final_snapshot                 = false
  storage_encrypted                   = true
  backup_retention_period             = "${var.backup_retention_period}"
  deletion_protection                 = "${var.cluster_deletion_protection}"
  allow_major_version_upgrade         = true
  apply_immediately                   = true
  db_cluster_parameter_group_name     = "${aws_rds_cluster_parameter_group.cluster_parameter_group.name}"
  snapshot_identifier                 = "${var.snapshot_identifier}"
  engine_version                      = "${var.engine_version}"
  final_snapshot_identifier           = "${var.deployment_prefix}-${var.service_name}-cluster-final-snapshot"
  enable_global_write_forwarding      = "false"
  tags                                = "${var.tags}"
}

```

Please help here.

**Comment by bryantbiggs** [comment]
hard to say from the info provided but it looks like you have a mis-match between the database engine version and the parameter group version
