### ISSUE TITLE
AWS RDS Modules is not working as desired. Re-deploying the same terraform code is destroying the RDS instance.

### ISSUE THREAD

**Issue by naveenkumarer** [terraform-aws-modules/terraform-aws-rds#439]
## Description

AWS RDS Modules is not working as desired. Re-deploying the same terraform code is destroying the RDS instance. We are trying to use the module and create an RDS postgres database with standard configuration. DB instance is created successfully. We have build CI?CD pipeline for the same. When we re-trigger the build without making any changes to any of terraform file, terraform is detecting a change and destroying the DB instacnce and all associated resources. 

We have tried to do same with CI/CD i.e. from local, but still facing the same issue.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

## Expected behavior

Terraform should not make change to any of the resources in 2nd apply.

## Actual behavior

Terraform is destroying the DB instacne.

**Comment by bryantbiggs** [comment]
Hi @naveenkumarer - how best can we help you without any reproduction or plan outputs?
