### ISSUE TITLE
Add gp3 storage_type support to aws_db_instance

### ISSUE THREAD

**Issue by crimean-celica** [terraform-aws-modules/terraform-aws-rds#441]
## Is your request related to a new offering from AWS?
https://github.com/hashicorp/terraform-provider-aws/issues/27702

**Comment by bryantbiggs** [comment]
there isn't any changes required here - once the provider supports the new attribute value, you can just simply specify it

**Comment by YanRah** [comment]
the provider supports the new attribute value but i am getting that when apply.

Error: expected storage_type to be one of [standard gp2 io1], got gp3
│ 
│   with module.ef-core.module.db.module.db_instance.aws_db_instance.this[0],
│   on .terraform/modules/ef-core.db/modules/db_instance/main.tf line 42, in resource "aws_db_instance" "this":
│   42:   storage_type      = var.storage_type

**Comment by antonbabenko** [comment]
It is not yet supported by the Terraform AWS provider - https://github.com/hashicorp/terraform-provider-aws/issues/27702 . There is nothing we can or should do about it in the module.

**Comment by klesher** [comment]
> there isn't any changes required here - once the provider supports the new attribute value, you can just simply specify it

With the new gp3 storage type, IOPS will apparently already be covered via the settings for io1 storage type.  However, the volume's "Storage Throughput" will also now be a configurable option.  Please see [the terraform-provider-aws MR to implement gp3](https://github.com/hashicorp/terraform-provider-aws/pull/27670).

Also note that unlike EC2 gp3 EBS volumes the [_baseline_ performance changes](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#Concepts.Storage.GeneralSSD) from 3000 IOPS/125 MiBps to 12,000 IOPS/500 MiBps for volumes larger than 400 GiB.  I'm assuming this sort of validation is preferred to be left to the upstream provider, but figured it's worth mentioning!

I likely won't have a need to modify storage throughput on any of my volumes, but wanted to at least give a heads up that I do believe at the minimum a new variable will be needed in the module (once upstream support is provided, of course).

**Comment by bryantbiggs** [comment]
thank you for the details @klesher - however, this is exactly why we have the feature request template that calls out the relevant information thats necessary https://github.com/terraform-aws-modules/.github/blob/master/.github/ISSUE_TEMPLATE/feature_request.md#is-your-request-related-to-a-new-offering-from-aws

we should fill out the feature request template properly, we can reference any provider level PRs, and then once the functionality has landed in the provider we can look at implementation here
