### ISSUE TITLE
RDS is being created in Default VPC version : 5.1.0 latest 

### ISSUE THREAD

**Issue by yk3823** [terraform-aws-modules/terraform-aws-rds#444]
Hi all , moving from **3.0.0** to the latest **5.1.0** , keep getting
Error: creating RDS DB Instance (scanovatedb): InvalidParameterCombination: The DB instance and EC2 security group are in different VPCs. The DB instance is in vpc-a39254da and the EC2 security group is in vpc-0dcac20201c949eaa
│ status code: 400, request id: fac4feaa-c3b1-4f14-9eb6-752a647f497e
│
│ with module.rdsdb.module.db_instance.aws_db_instance.this[0],
│ on .terraform/modules/rdsdb/modules/db_instance/main.tf line 32, in resource "aws_db_instance" "this":
│ 32: resource "aws_db_instance" "this" {

cloud you share ....

Trying **4.1.0** and still the same ..

Error: creating RDS DB Instance (scanovatedb): InvalidParameterCombination: The DB instance and EC2 security group are in 
**sharing my vpc configuration :**

module "vpc" {
source = "terraform-aws-modules/vpc/aws"
version = "3.14.4"

name = "${local.name}-${var.vpc_name}"
cidr = var.vpc_cidr_block

azs = var.vpc_availability_zones
private_subnets = var.vpc_private_subnets
public_subnets = var.vpc_public_subnets
database_subnets = var.vpc_database_subnets
create_database_subnet_group = var.vpc_create_database_subnet_group
create_database_subnet_route_table = var.vpc_create_database_subnet_route_table

create_database_internet_gateway_route = true

create_database_nat_gateway_route = true

NAT Gateways - Outbound Communication

enable_nat_gateway = var.vpc_enable_nat_gateway
single_nat_gateway = var.vpc_single_nat_gateway

VPC DNS Parameters

enable_dns_hostnames = true
enable_dns_support = true

tags = local.tags
vpc_tags = local.tags

public_subnet_tags = {
Type = "Public Subnets"
}
private_subnet_tags = {
Type = "Private Subnets"
}
database_subnet_tags = {
Type = "Private Database Subnets"
}
}

**Comment by zahorniak** [comment]
Hi @yk3823,
I've been using the `5.x` version for some time and have had no issues. Can you share your RDS Terraform configuration?
It looks like you specified the wrong DB subnet group for your RDS instance.

**Comment by yk3823** [comment]
hi @zahorniak thank you for your response ! 

 
module "rdsdb" {
  source  = "terraform-aws-modules/rds/aws"
  version = "3.5.0"
  identifier = var.db_instance_identifier
  
  # version 4.0.0 and above 
  # db_name  = var.db_name
  name  = var.db_name
  username = var.db_username
  create_random_password = false
  password = var.db_password
  port     = 3306

  multi_az               = true
  subnet_ids             = module.vpc.database_subnets
  vpc_security_group_ids = [module.rdsdb_sg.security_group_id]
  
  
  
  # All available versions: http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt
  engine               = "mysql"
  engine_version       = "8.0.27"
  family               = "mysql8.0" # DB parameter group
  major_engine_version = "8.0"      # DB option group
  instance_class       = "db.t4g.large"

  allocated_storage     = 20
  max_allocated_storage = 100

  

  maintenance_window              = "Mon:00:00-Mon:03:00"
  backup_window                   = "03:00-06:00"
  enabled_cloudwatch_logs_exports = ["general"]
  # create_cloudwatch_log_group     = true

  backup_retention_period = 0
  skip_final_snapshot     = true
  deletion_protection     = false

  performance_insights_enabled          = true
  performance_insights_retention_period = 7
  create_monitoring_role                = true
  monitoring_interval                   = 60

  parameters = [
    {
      name  = "character_set_client"
      value = "utf8mb4"
    },
    {
      name  = "character_set_server"
      value = "utf8mb4"
    }
  ]

  tags = local.tags
  db_instance_tags = {
    "Sensitive" = "high"
  }
  db_option_group_tags = {
    "Sensitive" = "low"
  }
  db_parameter_group_tags = {
    "Sensitive" = "low"
  }
  db_subnet_group_tags = {
    "Sensitive" = "high"
  }
}

**Comment by zahorniak** [comment]
Hey @yk3823 
Try to set RDS Module param `create_db_subnet_group` to `true`. By default, it's `false` in the new module versions and may cause situations like yours.

**Comment by yk3823** [comment]
added create_db_subnet_group = true ...
and it's working great using the latest rds module 5.1.0 
@zahorniak thank you , much appreciated !

**Comment by antonbabenko** [comment]
+1 on @zahorniak helping with answering issues! Highly appreciate it mate!
