### ISSUE TITLE
Addition of availability_zone parameter forces recreation of the db

### ISSUE THREAD

**Issue by ishirav** [terraform-aws-modules/terraform-aws-rds#45]
After availability_zone was added as a parameter, Terraform wants to destroy and recreate my database:
`availability_zone:                     "eu-central-1b" => <computed> (forces new resource)`

This is when I don't specify the availability_zone in my configuration.
If I try adding it, I get an error saying that it cannot be specified when using multi-az RDS.

**Comment by antonbabenko** [comment]
Thanks for reporting. Maybe someone can take a look into this and send a PR which fixes this.

**Comment by bryantbiggs** [comment]
@ishirav since this issue is quite out of date - closing for now but if this is still an issue please let us know and we can re-open
