### ISSUE TITLE
Add support for `storage_throughput` attribute

### ISSUE THREAD

**Issue by take-five** [terraform-aws-modules/terraform-aws-rds#452]
Hi, AWS recently added support for `gp3` storage type in RDS: https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-rds-general-purpose-gp3-storage-volumes/

Terraform AWS provider also released support for it in version 4.45.0.

Would it be possible to add support for it in this module as well?

## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

Yes, support for `gp3` storage type and `storage_throughput` attribute was added to Terraform AWS provider in version 4.45.0: https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4450-december--2-2022

---

FWIW, I can create a PR myself, but I'd like to understand what's the general strategy when adding new attributes? Do you increase Terraform AWS version provider requirement? Do you bump minor version? Or major?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.2.0 :tada:
