### ISSUE TITLE
aws_db_instance - name parameter when specified for child node results in force replacement for 2nd terraform apply

### ISSUE THREAD

**Issue by MayuriD89** [terraform-aws-modules/terraform-aws-rds#458]
## Description

- In aws_db_instance there is a parameter 'name' which is used to specify name of the database, it's a optional parameter.

- When we create a read-replica (restoring the db instance from existing one), the complete parent configuration gets applied to the child node.

- However, if the database names of the parent and child nodes different, force replacement occurs during the 2nd terraform apply command.

- **NOTE :** **In provider version 3.61.0, this change isn't observed, but in 3.70.0, we are observing this change (i.e., force replacement)**

      
## Versions

- Terraform version:
0.12.31

- Provider version(s):
3.70.0

## Reproduction Code [Required]

**Code for -**

**Child db instance(read replica) -**

```
`resource "aws_db_instance" "test-db" {
 
  allocated_storage    = 10
  name = "database_03"
  engine               = "mysql"
  engine_version       = "5.7"
  instance_class       = "db.t3.medium"
  replicate_source_db  = "source-db"
  storage_encrypted    = true
  max_allocated_storage = 1000
}`
```

**Parent db instance** 
```

resource "aws_db_instance" "source-db" {
 
  allocated_storage    = 10
  name = "database_02"
  engine               = "mysql"
  engine_version       = "5.7"
  instance_class       = "db.t3.medium"
  storage_encrypted    = true
  max_allocated_storage = 1000
}
```

- terraform apply (2nd terraform apply after resource creation)

## Expected behavior

- db instance (child) shouldn't show any change

## Actual behavior

- For 2nd terraform apply after resource creation it's showing a change which leads to the force replacement.

### Terminal Output Screenshot(s)

![SS-error-name-rds](https://user-images.githubusercontent.com/71746353/207873130-5bdc4ccb-423f-448f-b1bf-ad1f7774b23b.JPG)

**Comment by ihatecodingaf** [comment]
I am not sure but I don't see a name parameter defined anywhere but I can see a parameter db_name. Are both same?
