### ISSUE TITLE
Add - aws_db_instance_role_association

### ISSUE THREAD

**Issue by andormarkus-alcd** [terraform-aws-modules/terraform-aws-rds#464]
Hi All,

## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? 
  - Yes ✅: [2.9.0](https://github.com/hashicorp/terraform-provider-aws/pull/8466)

## Is your request related to a problem? Please describe.
I would like to associate an IAM role with the rds instance in one step instead of manually adding it later.

## Describe the solution you'd like.
This module should support like this:

```hcl
instance_role_association" {
  feature_name           = "S3_INTEGRATION"
  role_arn               = aws_iam_role.example.arn
}
```

## Describe alternatives you've considered.
Manually add `aws_db_instance_role_association` resource after his module.

## Additional context
I'm happy to submit a PR if this feature can be added.

Thanks,
Andor

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.2.0 :tada:
