### ISSUE TITLE
Missing required inputs in the documentation

### ISSUE THREAD

**Issue by ivellios** [terraform-aws-modules/terraform-aws-rds#469]
## Description

According to the documentation the only required input for the module is `identifier`, but when running the simplest code I get errors on the missing required arguments:

```shell
│ Error: Missing required argument
│
│   with module.rds.module.db_option_group.aws_db_option_group.this[0],
│   on .terraform/modules/rds/modules/db_option_group/main.tf line 14, in resource "aws_db_option_group" "this":
│   14:   engine_name              = var.engine_name
│
│ The argument "engine_name" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   with module.rds.module.db_option_group.aws_db_option_group.this[0],
│   on .terraform/modules/rds/modules/db_option_group/main.tf line 15, in resource "aws_db_option_group" "this":
│   15:   major_engine_version     = var.major_engine_version
│
│ The argument "major_engine_version" is required, but no definition was
│ found.
╵
╷
│ Error: Missing required argument
│
│   with module.rds.module.db_parameter_group.aws_db_parameter_group.this[0],
│   on .terraform/modules/rds/modules/db_parameter_group/main.tf line 14, in resource "aws_db_parameter_group" "this":
│   14:   family      = var.family
│
│ The argument "family" is required, but no definition was found.
╵
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 5.2.3

- Terraform version: v1.3.7
- Provider version(s): aws v4.51.0

## Reproduction Code [Required]

1. Create the simplest module use terraform file:

```terraform
module "rds" {
  source = "terraform-aws-modules/rds/aws"
  identifier = "simple-rds"
}
```

2. Run `terraform plan` to get the errors.

## Expected behavior

The module should run without issues for the most minimal use with required inputs.
The documentation should explicitly state which inputs are really required for the module.

**Comment by antonbabenko** [comment]
You need to provide required arguments as error messages telling - engine_name, major_engine_version, family...

Please look at the code in the `examples` folder for more information.

**Comment by ivellios** [comment]
Um... looks like `vault_path` is really path to the password file 🤨 Oh, I used it, but the path was with a typo and I got message: 

```no vault password file or vault pass provided```

🤦‍♂️ 

Nevermind

**Comment by ivellios** [comment]
Sure, but the documentation is misleading then. Shouldn't it point to the required inputs if they are in fact... required? Right now it's like: put required, run and then have fun checking errors, because we didn't want to put it into docs. 🤷
