### ISSUE TITLE
Upgrade read replica to more recent version than master

### ISSUE THREAD

**Issue by ajax-mykhailo-oleksiuk** [terraform-aws-modules/terraform-aws-rds#470]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
Due to this condition, it's impossible to upgrade/provision existing/new read replica to a more recent version than the master - https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L16

Scenario:
1. We got information from AWS that they will deprecate some version of MySQL.
2. We upgrade a read replica first (and can be done during business hours because we have a couple of them and can switch DNS from active/passive ones)
3. We upgrade a master at night because it causes some downtime.

## Describe the solution you'd like.
`engine_version` - should not be ignored by module and provision read replica with specified version.

## Describe alternatives you've considered.
The only one alternative for today is to upgrade read replica using AWS Console and run `terraform apply -refresh-only` to update state after upgrade.

**Comment by Thirumalaivel** [comment]
Facing the same issue. AWS documentation recommends to upgrade the replica first before upgrading the source. Since the upgrade of replica version is allowed via console, I would like terraform to support the same. If someone can look into this issue, that would be great, thanks.

**Comment by yuokada** [comment]
I'm also facing with the same issue.

Currently, when the `replicate_source_db` variable is set, `engine_version` is ignored like below in replica. The commit, 9149ec147327fbe5a7675ac48e9e641b5d7ec6e1 , changed behavior.

- https://github.com/terraform-aws-modules/terraform-aws-rds/commit/9149ec147327fbe5a7675ac48e9e641b5d7ec6e1#diff-2883367311130aa7774395acb120b8c862a6e0e7c1b718a1ec99d0fc32445d71
- https://github.com/terraform-aws-modules/terraform-aws-rds/blob/aa23ea2049e2f1df1bfa601229b0afb0fdf650fd/modules/db_instance/main.tf#L12-L16
