### ISSUE TITLE
FinalDBSnapshotIdentifier can not be specified when deleting a replica instance

### ISSUE THREAD

**Issue by OJFord** [terraform-aws-modules/terraform-aws-rds#472]
## Description

> │ Error: deleting RDS DB Instance (name): InvalidParameterCombination: FinalDBSnapshotIdentifier can not be specified when deleting a replica instance

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 5.2.3

- Terraform version: 1.3.7

- Provider version(s): 4.5.0

## Reproduction Code [Required]

```
module "other" {
  source  = "terraform-aws-modules/rds/aws"
  version = "v5.2.3"

  identifier = "other"
  engine = "postgres"
  engine_version = "13" 
  # ...
  
  final_snapshot_identifier = "foobar"
}

module "repro" {
  source  = "terraform-aws-modules/rds/aws"
  version = "v5.2.3"

  identifier = "name"

  replicate_source_db         = module.other.this_db_instance_id
  # ...
}
```

Apply, remove the config for replica, try to apply again.

## Expected behavior

Replica destroyed

## Actual behavior

Error in description

## Additional context

Workaround is to specify and apply `skip_final_snapshot = true` to the replica module instance first, explicitly, but I believe this should be implied by non-null `replicate_source_db`.

**Comment by OJFord** [comment]
Is that helpful?

**Comment by OJFord** [comment]
This kind of thing is just irritating - I'm unlikely personally to hit this again, but I put the time in to create an issue to help others (with the workaround) and alert to an issue that might then potentially be fixed. And then it's just closed because nobody says anything? Because there's nothing to say?

**Comment by antonbabenko** [comment]
Unfortunately, yes, we have a significantly larger amount of users and open issues than the number of hours we can spend on fixing various problems. We do our best all the time... for 6 years actually...

PS: Consider sponsoring us on GitHub if you want to support us, too.

**Comment by OJFord** [comment]
Consider that filing an (sensible) issue is a form of support too.

> we have a significantly larger amount of users and open issues than the number of hours we can spend on fixing various problems. We do our best 

I'm not demanding you fix it ASAP or asking why it isn't done or whatever - it's just irritating to have the issue closed unsolved, I wasted my time in bothering to inform you.

**Comment by bryantbiggs** [comment]
> Consider that filing an (sensible) issue is a form of support too.

Is getting upset and snapping at maintainers that your one issue wasn't addressed how you like a form of support too?
