### ISSUE TITLE
identifier_prefix not taken into consideration to create cloudwatch log groups

### ISSUE THREAD

**Issue by j-furtado** [terraform-aws-modules/terraform-aws-rds#477]
## Description

When creating a RDS instance using the `identifier_prefix` with `create_cloudwatch_log_group` set to true, and the `enabled_cloudwatch_logs_exports` properly set, the log groups created use the `identifier` name, not taking into consideration the `identifier_prefix`. This compromises the original purpose of the `identifier_prefix`, and can lead to issues if two instances are created with the same name.

Currently, the module is [hardcoded](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L148) to use only the `identifier` as part of the cloudwatch log group, making it impossible to change.

One way to fix this could be to use the same logic as the RDS instance, and use the [name_prefix](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#name_prefix) on `aws_cloudwatch_log_group`.

```hcl
module "db" {
  source  = "terraform-aws-modules/rds/aws"
  version = "5.2.3"
  
  identifier                                     = "testdb"
  instance_use_identifier_prefix = true
  
  ....
  
  create_cloudwatch_log_group = true
  enabled_cloudwatch_logs_exports = [
    "postgresql",
    "upgrade",
  ]
```

The cloud watch log groups will be created with the following names:

- `/aws/rds/instance/testdb/postgresql`
- `/aws/rds/instance/testdb/upgrade`

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `5.2.3`

- Terraform version: `v1.3.7`

- Provider version(s): 
```shell
+ provider registry.terraform.io/hashicorp/aws v4.53.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

## Reproduction Code [Required]

```hcl
provider "aws" {
  region = "eu-west-1"
}

module "db" {
  source  = "terraform-aws-modules/rds/aws"
  version = "5.2.3"

  identifier                     = "testdb"
  instance_use_identifier_prefix = true
  engine                         = "postgres"
  engine_version                 = "14.6"
  allocated_storage              = 20
  db_name                        = "testdb"
  instance_class                 = "db.m5.large"
  port                           = 5432
  family                         = "postgres14"

  create_cloudwatch_log_group = true
  enabled_cloudwatch_logs_exports = [
    "postgresql",
    "upgrade",
  ]
}
```

```shell
terraform init
terraform plan # should be enough to watch the behaviour
terraform apply -auto-approve # if you need to deploy it
```

## Expected behavior

TF Plan:

```shell
# module.db.module.db_instance.aws_cloudwatch_log_group.this["postgresql"] will be created
  + resource "aws_cloudwatch_log_group" "this" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/rds/instance/testdb-<UniqueID>/postgresql" # It would probably show a (known after apply)
      + name_prefix       = (known after apply)
      + retention_in_days = 7
      + skip_destroy      = false
      + tags_all          = (known after apply)
    }

  # module.db.module.db_instance.aws_cloudwatch_log_group.this["upgrade"] will be created
  + resource "aws_cloudwatch_log_group" "this" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/rds/instance/testdb-<UniqueID>/upgrade" # It would probably show a (known after apply)
      + name_prefix       = (known after apply)
      + retention_in_days = 7
      + skip_destroy      = false
      + tags_all          = (known after apply)
    }
```

## Actual behavior

TF Plan:

```shell
# module.db.module.db_instance.aws_cloudwatch_log_group.this["postgresql"] will be created
  + resource "aws_cloudwatch_log_group" "this" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/rds/instance/testdb/postgresql"
      + name_prefix       = (known after apply)
      + retention_in_days = 7
      + skip_destroy      = false
      + tags_all          = (known after apply)
    }

  # module.db.module.db_instance.aws_cloudwatch_log_group.this["upgrade"] will be created
  + resource "aws_cloudwatch_log_group" "this" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + name              = "/aws/rds/instance/testdb/upgrade"
      + name_prefix       = (known after apply)
      + retention_in_days = 7
      + skip_destroy      = false
      + tags_all          = (known after apply)
    }
```

**Comment by bryantbiggs** [comment]
this is not going to be possible - Terraform creates the random suffix that is added to the name when using a name prefix. Therefore, its impossible for us to know what the name will be ahead of time when using a prefix

**Comment by j-furtado** [comment]
I'm assuming that, even if a prefix is added to the log group creation (that is different from the RDS one), the logs will not go to the correct place? I'm assuming the pattern `/aws/rds/instance/<identifier>/<log>` is part of RDS' behaviour.

**Comment by bryantbiggs** [comment]
correct. I think there is one takeaway here - if `instance_use_identifier_prefix` is `true`, then we should not allow for the module to create the log group
