### ISSUE TITLE
Can't pass an already existing db_subnet_group: `value of 'count' cannot be computed`

### ISSUE THREAD

**Issue by jordiclariana** [terraform-aws-modules/terraform-aws-rds#48]
Hi,

As for [this change](https://github.com/terraform-aws-modules/terraform-aws-rds/commit/f681318e78d0b141e4d479177fb054c4d8c0b787) it is impossible to pass a resource/data's derived subnet_group_id to this current module, it throws:

> aws_db_subnet_group.this: value of 'count' cannot be computed

Example, taking the already existing example from the RDS module itself:

```hcl
provider "aws" {
  region = "eu-west-1"
}

##############################################################
# Data sources to get VPC, subnets and security group details
##############################################################
data "aws_vpc" "default" {
  default = true
}

data "aws_security_group" "default" {
  vpc_id = "${data.aws_vpc.default.id}"
  name   = "default"
}

data "aws_subnet_ids" "all" {
  vpc_id = "${data.aws_vpc.default.id}"
}

// Added for this issue purposes:
resource "aws_db_subnet_group" "this" {
  name_prefix = "my_db_subnet_group"
  subnet_ids  = ["${data.aws_subnet_ids.all.ids}"]
}

#####
# DB
#####
module "db" {
  source  = "terraform-aws-modules/rds/aws"
  version = "1.13.0"

  identifier = "demodb"

  # All available versions: http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.VersionMgmt
  engine            = "mysql"
  engine_version    = "5.7.19"
  instance_class    = "db.t2.large"
  allocated_storage = 5
  storage_encrypted = false

  # kms_key_id        = "arm:aws:kms:<region>:<accound id>:key/<kms key id>"
  name     = "demodb"
  username = "user"
  password = "YourPwdShouldBeLongAndSecure!"
  port     = "3306"

  vpc_security_group_ids = ["${data.aws_security_group.default.id}"]

  maintenance_window = "Mon:00:00-Mon:03:00"
  backup_window      = "03:00-06:00"

  # disable backups to create DB faster
  backup_retention_period = 0

  tags = {
    Owner       = "user"
    Environment = "dev"
  }

  # DB subnet group
  # Disable automatic db_subnet_group creation, as we want to pass one that already exists:
  create_db_subnet_group = false
  db_subnet_group_name   = "${aws_db_subnet_group.this.id}"

  # DB parameter group
  family = "mysql5.7"

  # Snapshot name upon DB deletion
  final_snapshot_identifier = "demodb"
}
```

When runing `terraform plan`:
```bash
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_vpc.default: Refreshing state...
data.aws_subnet_ids.all: Refreshing state...
data.aws_security_group.default: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* module.db.module.db_subnet_group.aws_db_subnet_group.this: aws_db_subnet_group.this: value of 'count' cannot be computed
```

So reusing a DB subnet group is impossible.

**Comment by jordiclariana** [comment]
The only workaround I found so far is to create a db_subnet_group with a deterministic name (using `name` instead of `name_prefix`) and passing that (a simple string) to the RDS module.

I guess this is somehow related with #42, as if you are able to set the `name` in a deterministic way you can reuse the db_group_name created inside RDS module for another RDS call (create a slave of a previously created master, for instance).

**Comment by antonbabenko** [comment]
The issue you are describing is related to the way computed values work in Terraform, and currently, it is one of the most popular problems within Terraform modules. So, yes, values should be known/computed before using them in `count`. One of the solutions to this is to split your code into two pieces - one create `aws_db_subnet_group` and output `name`, another reads this value.

The solution you are proposing may also work, but it will not allow creating resources with the same names in the same AWS account (for example, when we need to have several similar RDS resources in test/staging AWS account).

I don't know better solution at the moment, though I am open to working suggestions and solutions.
