### ISSUE TITLE
Support provider default_tags propagation

### ISSUE THREAD

**Issue by pmcenery-bl** [terraform-aws-modules/terraform-aws-rds#480]
## Is your request related to a problem? Please describe.
No

## Describe the solution you'd like.
The AWS provider's default_tags are not propagated to the resources created by the module. Other modules have implemented changes to better support the propagation of `default_tags`. Please can you consider implementing these features in this module?

## Describe alternatives you've considered.
Workarounds include `merge()` but this causes tag churn on apply.

**Comment by bryantbiggs** [comment]
`default_tags` should work as is based on the provider - there shouldn't be additional changes required by modules to support them. In the past when we have tried to "add better support" for them it has created numerous issues

**Comment by pmcenery-bl** [comment]
Thanks @bryantbiggs 

You are right. I had incorrectly specified a few tags which were already specified in the provider `default_tags` which caused churn on every apply. Removing duplicates has solved the problem. Apologies for the confusion, but hopefully this steers someone in the right direction in future!

**Comment by bryantbiggs** [comment]
thank you!
