### ISSUE TITLE
Support for storing master user password in Secrets Manager

### ISSUE THREAD

**Issue by adammichalik** [terraform-aws-modules/terraform-aws-rds#488]
Copied from the provider issue https://github.com/hashicorp/terraform-provider-aws/issues/28538, supported since [provider ver. 4.61.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4610-march-30-2023):

> Amazon RDS now supports integration with AWS Secrets Manager to streamline how you manage your master user password for your RDS database instances. With this feature, RDS fully manages the master user password and stores it in AWS Secrets Manager whenever your RDS database instances are created, modified, or restored. The new feature supports the entire lifecycle maintenance for your RDS master user password including regular and automatic password rotations; removing the need for you to manage rotations using custom Lambda functions.
> 
> RDS integration with AWS Secrets Manager improves your database security by ensuring your RDS master user password is not visible in plaintext to administrators or engineers during your database creation workflow. Furthermore, you have flexibility in encrypting the secrets using your own managed key or by using a KMS key provided by AWS Secrets Manager. RDS and AWS Secrets Manager provide you the ease and security in managing your master user password for your database instances, relieving you from complex credential management activities such as setting up custom Lambda functions to manage password rotations.

This is a great improvement from the security perspective, I would love to see it propagated to this module.

**Comment by sptdevos** [comment]
+1

**Comment by ishwar-amzn** [comment]
@adammichalik @sptdevos I am starting working on this request.

**Comment by gruckion** [comment]
> @adammichalik @sptdevos I am starting working on this request.

How you getting on?

**Comment by terry-wade-cko** [comment]
+1

**Comment by rlmartin** [comment]
+1

**Comment by rlmartin** [comment]
Any progress on this?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.0.0 :tada:
