### ISSUE TITLE
Support for Reserved Instances with RDS

### ISSUE THREAD

**Issue by Richard-Barrett** [terraform-aws-modules/terraform-aws-rds#490]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform]: AWS (https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is available in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_reserved_instance
  - LATEST

## Is your request related to a problem? Please describe.

The current setup does not allow for the db instance to be a reserved db instance, and the company I represent would like to see a db instance set to a reserved pricing instance.

## Describe the solution you'd like.

We would like to be able to choose rather or not the reserved instance type is reserved or not using a boolean value like either true or false.

Example of current Usage:

```HCL
data "aws_rds_reserved_instance_offering" "test" {
  db_instance_class   = "db.t2.micro"
  duration            = 31536000
  multi_az            = false
  offering_type       = "All Upfront"
  product_description = "mysql"
}

resource "aws_rds_reserved_instance" "example" {
  offering_id    = data.aws_rds_reserved_instance_offering.test.offering_id
  reservation_id = "optionalCustomReservationID"
  instance_count = 3
}
```

We would like to see merged functionality with the same above fields within this module as optional with `reserved_instance` being a field such that it defaults to `false` allowing for the base functionality of the module to remain the same.

## Describe alternatives you've considered.

Just using the main provider

## Additional context

This would help customers save money and extend the functionality of this module.

**Comment by bryantbiggs** [comment]
I don't think that would make a lot of sense - reserved instances are not tied to one RDS instance/cluster, they can be used across any number of instances

What would be the benefit of having this embedded in the module?

**Comment by bryantbiggs** [comment]
closing for now
