### ISSUE TITLE
Support for aws_db_instance_role_association

### ISSUE THREAD

**Issue by Roxyrob** [terraform-aws-modules/terraform-aws-rds#493]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality
 
aws provider: 2.33.0

## Is your request related to a problem? Please describe.
N/A

## Describe the solution you'd like.
Support for aws_db_instance_role_association to allow RDS instance to interact with AWS services (like s3) would be better integrated in this RDS module.

## Additional context
e.g. RDS SQL Server .ispac package import to SSIS, but used also for PostgreSQL and Oracle.

**Comment by Roxyrob** [comment]
Hi,
some news on this.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.2.0 :tada:
