### ISSUE TITLE
Add support for aws_db_option_group

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-rds#5]
Similar to this - https://github.com/douglasfraser-aviva/terraform-aws-rds/commit/a08d7039e151e17acacbf006ad17f3bfe04adb90

**Comment by douglasfraser-aviva** [comment]
First attempt was non-functional, PR #24 is replacement.

**Comment by antonbabenko** [comment]
[v1.17.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v1.17.0) has been released with this feature.
