### ISSUE TITLE
Add documentation on how to migrate from 5.9.0 to 6.0.0 - password breaking change

### ISSUE THREAD

**Issue by cfernhout** [terraform-aws-modules/terraform-aws-rds#500]
## Is your request related to a problem? Please describe.
I want to upgrade from 5.9.0 to 6.0.0. However, it's unclear from the gecko how to deal with the removal of the password generation. I don't want to change the password because that will generate application downtime.

## Describe the solution you'd like.
Have some clear documentation on how to achieve this, such that not everyone needs to figure this out on their own.

## Describe alternatives you've considered.
I'm considering moving away from the module and importing the created resources as individual resource blocks. Bing AI/ChatGPT is pretty good in such mappings. 

An alternative would be to add the db id fix to version 5.10, such that it is not coupled with the breaking change.

## Additional context
I just moved to 5.9.0 just to find out it broke other stuff because of the bug concerning the db id. Which is fixed in 6.0.0, only to find out that it is coupled with a breaking change with no clear solution.

**Comment by cfernhout** [comment]
My current solution is:
While on 5.9.0, create a random_password resource block
```
resource "random_password" "rds_master_password" {
  length  = 16
  special = false
}
```
Move the password from the module to the new resource block by running
```
terraform state mv 'module.db.random_password.master_password[0]' random_password.rds_master_password
```
Change these parts in the module
```
version                                = "~> 5.9.0"
create_random_password = true
random_password_length = 16
```
to
```
version     = "~> 6.0.0"
password = random_password.rds_master_password.result
```
Run
```
terraform init -upgrade
terraform plan
terraform apply
```

**Comment by bryantbiggs** [comment]
While your current solutions seems sound, I would recommend you revisit the manner in which the master password is used. It should be treated similar to the AWS root user's password - where its there when you need it for only a small select set of actions, but by in large, you should create additional users with the appropriately scoped permissions for their respective tasks. This is what allows you to enable the auto rotation of the master user password as well
