### ISSUE TITLE
Add outputs for master_user_secret

### ISSUE THREAD

**Issue by lwj** [terraform-aws-modules/terraform-aws-rds#501]
## Is your request related to a problem? Please describe.
When using a "managed" password in 5.x.x, `db_instance_password` could be used to retrieve the password. In 6.0.0, the replacement `manage_master_user_password` provides no way of retrieving the secret containing the master password.

## Describe the solution you'd like.
Respective output(s) for the https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#master_user_secret attribute block.

**Comment by divbell** [comment]
Is there a way to dereference the SecretsManager arn or key name with version 6.0.0 while we wait for the PR and 6.0.1 release?

**Comment by meap** [comment]
This is super helpful. How was it actually supposed to be used?

**Comment by lwj** [comment]
> This is super helpful. How was it actually supposed to be used?

I'm not sure. In previous versions we passed the `db_instance_password` into our database provider which would handle creating databases/users for applications mapped to IAM roles, which as far as I'm aware is best practice. Unless I'm mistaken there's no way to do this currently in 6.0.0. Hoping a maintainer will come along at some point and either approve the PR or tell me we're doing it wrong 😄

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.1.0 :tada:
