### ISSUE TITLE
Add output for master user secret name to complement db_instance_master_user_secret_arn

### ISSUE THREAD

**Issue by divbell** [terraform-aws-modules/terraform-aws-rds#503]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

I'm frustrated retrieving the AWS SecretsManager secret name to complement the db_instance_master_user_secret_arn when crafting ExternalSecret manifests.

## Describe the solution you'd like.

I would like an output such as db_instance_master_user_secret_name, or to understand what existing output contains this secret name.

## Describe alternatives you've considered.

I have tried extracting the key name from the arn using a couple of split()s and coalesce.
I considered using a Terraform data resource to fetch the secret via arn and then retrieve the secret name from the data resource, but that does not appear to be supported either.

## Additional context

Maybe I'm being thick!? :)  Any pointer to an elegant way to access the secret name would be helpful.  Otherwise, perhaps a new feature?

**Comment by bryantbiggs** [comment]
we are pulling directly from the output of the resource which currently does not expose the name of the secret. And since this is not generated by Terraform, we do not have a direct way to retrieve this value https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#master_user_secret

**Comment by divbell** [comment]
Hrmph, well, that's what I was seeing too.  It can be extracted from the arn.

Example db_instance_master_user_secret_arn:
arn:aws:secretsmanager:us-east-1:111122223333:secret:rds!db-de1a2435-5623-8135-b2cc-db8eaa2d32ad-FMiCx1

If we split on ":", then the seventh element contains:
rds!db-de1a2435-5623-8135-b2cc-db8eaa2d32ad-FMiCx1

Then splitting on "-", we can take elements 1-6, or otherwise chop off that last hyphen and everything that follows.
This is the secret name.

**Comment by bryantbiggs** [comment]
sure, its possible

**Comment by divbell** [comment]
Perhaps `regex( "(rds!.+)-[^-]+$", module.db.db_instance_master_user_secret_arn)`...
