### ISSUE TITLE
aws_db_subnet_group : "An argument named "create" is not expected here."

### ISSUE THREAD

**Issue by BertCatsburg** [terraform-aws-modules/terraform-aws-rds#505]
## Description

When setting up a aws_db_subnet_group, the "create" attribute is used. 
However, it gives the error: **An argument named "create" is not expected here.**

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions
```
$ terraform --version
Terraform v1.5.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.9.0
+ provider registry.terraform.io/hashicorp/http v3.4.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

So, Terraform version is >= 1.0, and aws version is >= 5.0. That's ok. 

## Reproduction Code [Required]

The resource definition: 
```
resource "aws_db_subnet_group" "this" {
  create      = var.db_subnet_group
  name        = "rds_subnet_group"
  description = "The RDS Subnet Group in the Private Network"
  subnet_ids  = [for i in module.module_subnet_private.subnet_ids : i]

  tags = {
    Name  = "${var.aws_resource_group}_RDS_SUBNET_GROUP"
    Group = var.aws_resource_group
  }
}
```

Are you using workspaces? No
Have you cleared the local cache (see Notice section above)? Yes
List steps in order that led up to the issue you encountered
- Setup a simple module
- Use the 'create' attribute.

## Expected behavior
'create' should not give an error.

## Actual behavior
Error: 

```
│ Error: Unsupported argument
│
│   on module_networking/main.tf line 144, in resource "aws_db_subnet_group" "this":
│  144:   create      = var.db_subnet_group
│
│ An argument named "create" is not expected here.

```

**Comment by bryantbiggs** [comment]
You are mixing a module variable `create` with a resource `aws_db_subnet_group` which does not have this attribute. Either you should utilize the module which supports this variable, or look at creating your own conditional creation logic
