### ISSUE TITLE
MySQL RDS - Unable to apply certificate authority parameter

### ISSUE THREAD

**Issue by nutakkimurali** [terraform-aws-modules/terraform-aws-rds#511]
## Description

When provisioning RDS using this module, we've noticed that the ca_cert_identifier is defaulting to rds-ca-2019, which is set to expire on August 22, 2024. AWS recommends updating the certificate authority to one of the following options.

rds-ca-rsa2048-g1
rds-ca-rsa4096-g1
rds-ca-ecc384-g1

However, when we explicitly assign the new ca_cert_identifier, Terraform's plan command correctly shows the new assignment. However, during the apply phase, Terraform does not apply this change as expected.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 3.5.0

```terraform {
  required_version = "~> 1.0.10"

  required_providers {

    aws = {
      source  = "hashicorp/aws"
      version = "4.9.0"
      #version = "3.68.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.1"
    }

  }

}```

## Reproduction Code [Required]

```
module "db" {
  source = "./modules/rds"

  identifier = "${local.identifier}"

  engine            = var.engine
  engine_version    = var.engine_version
  instance_class    = var.instance_class
  allocated_storage = var.allocated_storage
  storage_encrypted = var.storage_encrypted
  ca_cert_identifier = var.ca_cert_identifier
```

Steps to reproduce the behavior:

<!-- Are you using workspaces? --> No
<!-- Have you cleared the local cache (see Notice section above)? --> Yes
<!-- List steps in order that led up to the issue you encountered --> terraform init, terraform plan and terraform apply

## Expected behavior

Expecting the terraform to update the RDS certificate authority with any of the following values  

rds-ca-2019
rds-ca-rsa2048-g1
rds-ca-rsa4096-g1
rds-ca-ecc384-g1


## Actual behavior

Though there is no error after executing the terraform apply, it is still holding the default value i.e rds-ca-2019

### Terminal Output Screenshot(s)
N/A

## Additional context

refer AWS documentation for release notes about this change: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

**Comment by magreenbaum** [comment]
Seems that this setting takes place during a maintenance window if `apply_immediately` isn't set to `true`. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html#UsingWithRDS.SSL-certificate-rotation-updating

Using `apply_immediately = true` should apply it right away. 

There's also a related upstream issue: https://github.com/hashicorp/terraform-provider-aws/issues/33546

**Comment by nutakkimurali** [comment]
@magreenbaum Thanks for pointing out and certificate has been applied successfully after setting apply_immediately = true s.
