### ISSUE TITLE
module rds not work on 1.6.0

### ISSUE THREAD

**Issue by Mieszko96** [terraform-aws-modules/terraform-aws-rds#514]
## Description

module rds 6.1.1 does not work on terraform 1.6.0
related to 
https://github.com/hashicorp/terraform/issues/33977

error
Terraform v1.6.0
on linux_amd64
Initializing plugins and modules...

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is marked, so must be unmarked first
goroutine 1181 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2b92ec0?, 0x38c4c30?})
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.AsString({{{0x3902720?, 0xc000012c29?}}, {0x2e1de40?, 0xc0036863d8?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/value_ops.go:1385 +0x47
github.com/zclconf/go-cty/cty.Value.Range({{{0x3902720?, 0xc000012c29?}}, {0x2e1de40?, 0xc0036863d8?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/value_range.go:53 +0x285
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc000858a80, 0xc0036863c0)
        /home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.0/hclsyntax/expression.go:746 +0xd6a
github.com/hashicorp/terraform/internal/lang.(*Scope).EvalExpr(0xc0036ae090, {0x3902df8?, 0xc000858a80}, {{0x3902f48?, 0x5130520?}})
        /home/runner/work/terraform/terraform/internal/lang/eval.go:175 +0x1bd
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).evalModuleVariable(0xc001196900, {0x391fb60?, 0xc00263c460?}, 0x80?)
        /home/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:248 +0x225
github.com/hashicorp/terraform/internal/terraform.(*nodeModuleVariable).Execute(0xc001196900, {0x391fb60, 0xc00263c460}, 0x4)
        /home/runner/work/terraform/terraform/internal/terraform/node_module_variable.go:183 +0x12c
github.com/hashicorp/terraform/internal/terraform.(*ContextGraphWalker).Execute(0xc0054b6240, {0x391fb60, 0xc00263c460}, {0x7fc77fdf5200, 0xc001196900})
        /home/runner/work/terraform/terraform/internal/terraform/graph_walk_context.go:143 +0xbe
github.com/hashicorp/terraform/internal/terraform.(*Graph).walk.func1({0x2f07ca0, 0xc001196900})
        /home/runner/work/terraform/terraform/internal/terraform/graph.go:78 +0x375
github.com/hashicorp/terraform/internal/dag.(*Walker).walkVertex(0xc0011969c0, {0x2f07ca0, 0xc001196900}, 0xc002da55c0)
        /home/runner/work/terraform/terraform/internal/dag/walk.go:384 +0x2e5
created by github.com/hashicorp/terraform/internal/dag.(*Walker).Update in goroutine 625
        /home/runner/work/terraform/terraform/internal/dag/walk.go:307 +0xde8
Operation failed: failed running terraform plan (exit 11)

reproduce

```
module "rds" {
  source  = "terraform-aws-modules/rds/aws"
  version = "~> 6.1.1"

  identifier = "test"

}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = local.tags
  }
}
```

**Comment by bryantbiggs** [comment]
thank you - as shown in the error message output:

```
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1](https://github.com/hashicorp/terraform/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) so that we can fix this.

When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
```

Please file a ticket with the Terraform core project for this issue
