### ISSUE TITLE
Module breaks with Terraform v1.6

### ISSUE THREAD

**Issue by digorgonzola** [terraform-aws-modules/terraform-aws-rds#515]
## Description

We're getting a Terraform crash when running against v6.1.1 of this module using Terraform v1.6.0!

Not sure if I should be reporting this here or with Terraform...

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v6.1.1

- Terraform version: v.1.6.0

- Provider version(s): 
+ provider registry.terraform.io/hashicorp/aws v5.20.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

## Reproduction Code [Required]

Upgrading terraform version broke this completely! I can successfully run a plan/apply operation by downgrading to Terraform v1.5.7.

## Expected behavior

I expect the plan to successfully run...

## Actual behavior

Terraform initialised successfully but plan causes a crash.

### Terminal Output Screenshot(s)

![image](https://github.com/terraform-aws-modules/terraform-aws-rds/assets/29941279/9eac2750-7ad8-47b3-8881-88bfa6d88d74)

Running Terraform version 1.5.7:
![image](https://github.com/terraform-aws-modules/terraform-aws-rds/assets/29941279/58299df2-7f6a-4251-8353-62f68233b937)

**Comment by antonbabenko** [comment]
There is a known issue in Terraform 1.6.0, which has been fixed in 1.6.1 (waiting for the release) - https://github.com/hashicorp/terraform/issues/33977

**Comment by mteodori** [comment]
same as #514 thanks for the resolution info!
