### ISSUE TITLE
In-place upgrade of AWS RDS MySQL

### ISSUE THREAD

**Issue by giautm** [terraform-aws-modules/terraform-aws-rds#519]
## Description

I ran into the same issue with https://github.com/terraform-aws-modules/terraform-aws-rds/issues/506 when trying to upgrade a read replica to the new version.

The module is unable to delete the options-group because it is attached with system snapshot

## Versions

- Module version v6.3.0
- Terraform versions:
```
Terraform v1.6.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.26.0
```

**Comment by bryantbiggs** [comment]
unfortunately this is not something we are going to be able to handle here. I would suggest looking for a related issue in the AWS provider, or creating one if one does not exist

a temporary work around would be to remove the option group from Terraform using `terraform state rm <resource>`
