### ISSUE TITLE
Cannot create multi-region + multi-az (MySQL)

### ISSUE THREAD

**Issue by Bryji** [terraform-aws-modules/terraform-aws-rds#52]
I've created a multi-region (3 regions) MySQL deployment with *multi_az = true*. So we have the primary instance and read-replicas in 2 other regions. It all applies successfully, no errors but on inspecting the infra in the AWS console I can see the primary instance is *multi_az* but the read-replicas (in different regions) are not. 

If I do another *terraform apply* then terraform notices that the other regions are not *multi_az* and states that they will be set to *true* but on applying it remains stubbornly set to false.

I am able to turn it on in the AWS console and I notice this seems to be a recent feature: https://aws.amazon.com/about-aws/whats-new/2018/01/amazon-rds-read-replicas-now-support-multi-az-deployments/ - perhaps this is why it is not working?

Output of re-running terraform apply (not 2 other attributes also failed to take, backup retention and IAM access):
```
Terraform will perform the following actions:

  ~ module.rds-sydney.module.db.module.db_instance.aws_db_instance.this
      backup_retention_period:             "0" => "1"
      iam_database_authentication_enabled: "false" => "true"
      multi_az:                            "false" => "true"

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.rds-sydney.module.db.module.db_instance.aws_db_instance.this: Modifying... (ID: test-multiregion-rds-sydney)
  backup_retention_period:             "0" => "1"
  iam_database_authentication_enabled: "false" => "true"
  multi_az:                            "false" => "true"
module.rds-sydney.db.db_instance.aws_db_instance.this: Still modifying... (ID: test-multiregion-rds-sydney, 10s elapsed)
module.rds-sydney.db.db_instance.aws_db_instance.this: Still modifying... (ID: test-multiregion-rds-sydney, 20s elapsed)
module.rds-sydney.db.db_instance.aws_db_instance.this: Still modifying... (ID: test-multiregion-rds-sydney, 30s elapsed)
module.rds-sydney.module.db.module.db_instance.aws_db_instance.this: Modifications complete after 37s (ID: test-multiregion-rds-sydney)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by antonbabenko** [comment]
Bryan, I think you are right, it is not supported by Terraform AWS provider. Look at this similar issue - https://github.com/terraform-providers/terraform-provider-aws/issues/2909 

Please open an issue there. There is not much we can do inside this module.

**Comment by Bryji** [comment]
Thanks Anton, will do, just getting familiar with this stuff so wasn't sure the right location to raise this.
