### ISSUE TITLE
Existing pg_stat_statements.max parameter re created with every plan

### ISSUE THREAD

**Issue by AnastasiaKnt** [terraform-aws-modules/terraform-aws-rds#525]
## Description

Every time I `plan` inside my RDS deployment, part of the parameter group is re-created. It is the same change every time performed on pg_stat_statements.max paremeter. Terraform wants to make the same change even if` terraform apply `was already executed a minute ago

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: ~> 6.3

- Terraform version:

Terraform v1.6.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.30.0
+ provider registry.terraform.io/hashicorp/random v3.6.0

## Reproduction Code [Required]

```
module "postgres" {
  source  = "terraform-aws-modules/rds/aws"
  version = "~> 6.3"

  identifier                          =  var.name
  engine                              = "postgres"
  engine_version                      = "15.2"
```

I also have the following parameter group:

```
  parameters = [
    {
      name = "rds.force_ssl"
      value = "0"
    },
    {
      name = "log_min_duration_statement"
      value = "500"
    },
    {
      name = "pg_stat_statements.max"
      apply_method = "immediate"
      value = "10000"
    },
    {
      name = "pg_stat_statements.track"
      value = "all"
    }
  ]
```

Execute `terraform plan ` in the instance that is already up and running

## Expected behavior

If no changes are performed on my code, `terraform plan` should not have changes in the output

## Actual behavior

There is the following output evey thime terraform plan is executed even if an apply has been executed previously:

`Terraform will perform the following actions:`

```
  # module.postgres.module.db_parameter_group.aws_db_parameter_group.this[0] will be updated in-place
  ~ resource "aws_db_parameter_group" "this" {
        id          = ""
        name        = ""
        tags        = {
            "Environment" = ""
            "Name"        = ""
            "Owner"       = ""
        }
        # (5 unchanged attributes hidden)

      - parameter {
          - apply_method = "pending-reboot" -> null
          - name         = "pg_stat_statements.max" -> null
          - value        = "10000" -> null
        }
      + parameter {
          + apply_method = "immediate"
          + name         = "pg_stat_statements.max"
          + value        = "10000"
        }
    }
```

**Comment by magreenbaum** [comment]
Looks like `pg_stat_statements.max` is a static parameter. Static parameters' apply method should be set to `pending-reboot` based on the docs. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/parameter-groups-overview.html#parameter-groups-overview.db-instance

**Comment by AnastasiaKnt** [comment]
Ups. Totally true. Thank you!
