### ISSUE TITLE
Support for Aurora MySQL

### ISSUE THREAD

**Issue by adrianbn** [terraform-aws-modules/terraform-aws-rds#53]
The module doesn't seem to play nice with RDS Aurora for MySQL (5.7). First it seems that `storage_type` is not supported for any of standard/io1/gp2:
```
aws_db_instance.this: Error creating DB Instance: StorageTypeNotSupported: Invalid storage type: io1
	status code: 400, request id: 326e86ca-cdb8-4a72-be42-e98d9708d61b
```

If I comment out that line for the resource creation a different error crops up: 
``` 
aws_db_instance.this: Error creating DB Instance: InvalidParameterCombination: Standalone DB Instances are not supported for the specified engine
	status code: 400, request id: 07ec75d1-5240-421b-b6ee-e553671faa2c
```

It seems that no cluster is created to host the Aurora instance, which is not a supported configuration for Aurora. Is it possible to support Aurora in this module?

**Comment by antonbabenko** [comment]
AWS and effectively Terraform treats `RDS Aurora for MySQL` and `RDS Mysql` differently (different concepts and resources), so it is not possible to cover both in an elegant module. Instead, separate modules can be used for one or another.

**Comment by antonbabenko** [comment]
If somebody wants to contribute RDS Aurora Terraform module to terraform-aws-modules and maintain it there it would be awesome.
