### ISSUE TITLE
Upgrade guide v5 -> v6

### ISSUE THREAD

**Issue by ayoh1** [terraform-aws-modules/terraform-aws-rds#539]
## Is your request related to a problem? Please describe.
We are upgrading some MSSQL instances currently in version 5. When moving to 6.0.0 **we are not sure about how to handle the removed argument "create_random_password"** and its impact in the instance when applying terraform.

We did understand we had to remove that parameter and replace with "manage_master_user_password", but we don't know if doing this it will modify the instance master password with a new one from the secret the module will be creating. Terraform plan is showing to delete "random_password" resource and "password" from the instance, so we thought it could be left in a state without master password or something weird.

    # module.database.module.mssql-db.random_password.master_password[0] will be destroyed
        # (because random_password.master_password is not in configuration)
        - resource "random_password" "master_password" {
            - bcrypt_hash = (sensitive value) -> null
            - id          = "none" -> null
            - length      = 10 -> null
            - lower       = true -> null
            - min_lower   = 0 -> null
            - min_numeric = 0 -> null
            - min_special = 0 -> null
            - min_upper   = 0 -> null
            - number      = true -> null
            - numeric     = true -> null
            - result      = (sensitive value) -> null
            - special     = false -> null
            - upper       = true -> null
          }

        # module.database.module.mssql-db.module.db_instance.aws_db_instance.this[0] will be updated in-place
        ~ resource "aws_db_instance" "this" {
              id                                    = "db-REDACTED"
            + manage_master_user_password           = true
            - password                              = (sensitive value) -> null
              # (55 unchanged attributes hidden)
              # (1 unchanged block hidden)
          }

Since there is a upgrade guide for 4.0 we thought we could ask for guidelines on best way to do the upgrade to 6.0 and handle this breaking change without breaking master password.

Thanks!!

## Describe the solution you'd like.
An UPGRADE-6.0.md file providing some guidance on how to handle this breaking change since could affect an instance master password and cause problems if terraform changes that password without the user previous knowledge.

## Describe alternatives you've considered.
We have thought on doing some trial/error in nonprod to see what happens, but thought that would also be helpful for others having a quick guide for this breaking in the repo.

## Additional context
Thank your for your work here!

**Comment by mukeshfulewale-h1** [comment]
Hi,
Is there any update on this? Thanks!

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.5.5 :tada:

**Comment by ayoh1** [comment]
thanks
