### ISSUE TITLE
Restore aws to required providers

### ISSUE THREAD

**Issue by ajax-mykhailo-oleksiuk** [terraform-aws-modules/terraform-aws-rds#545]
## Versions

- Module version [Required]: 6.5.3

- Terraform version: 1.6.3

- Provider version(s): hashicorp/aws 5.41.0

## Reproduction Code [Required]
Due to dropped required provider here - https://github.com/terraform-aws-modules/terraform-aws-rds/pull/542/files#diff-dfd5848fa77a04d0343891fe859286cc210473d10f0e62c7f99f0d5ecf1a9927L3-L9

I'm getting this warning:
```
Warning: Reference to undefined provider
│
│   on master.tf line 35, in module "master":
│   35:     aws = aws.master
│
│ There is no explicit declaration for local provider name "aws" in module.master, so Terraform is assuming you mean to pass a configuration for "hashicorp/aws".
│
│ If you also control the child module, add a required_providers entry named "aws" with the source address "hashicorp/aws".
```

## Expected behavior

Restore required_provider

## Additional context

Similar issue with eks module - https://github.com/terraform-aws-modules/terraform-aws-ecs/issues/180
And @antonbabenko's commenton it - https://github.com/terraform-aws-modules/terraform-aws-ecs/issues/180#issuecomment-2009390580

**Comment by antonbabenko** [comment]
Please open a PR where you revert changes to `versions.tf`
