### ISSUE TITLE
To restore deleted database from continuous AWS backup plan (PITR)

### ISSUE THREAD

**Issue by grzegorz-kulis** [terraform-aws-modules/terraform-aws-rds#567]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? Yes

## Is your request related to a problem? Please describe.
Right now it is not possible to restore a database using continuous AWS Backup plan (PITR) to restore a deleted database. Currently, no argument is able to provide the support for pointing to continuous recovery point with arn such as `arn:aws:backup:eu-west-1:***********:recovery-point:continuous:db-**************-**********`

## Describe the solution you'd like.
I would like to be able to perform PITR for a deleted database pointing to continuous recovery point in such a way:

```hcl
  restore_to_point_in_time = {
    restore_time                             = "2024-09-25T10:25:00Z"
    source_continuous_automated_backup_arn = "arn:aws:backup:eu-west-1:***********:recovery-point:continuous:db-**************-**********"
  }
``` 

## Describe alternatives you've considered.
The only alternative so far is building additional tools that would base on AWS CLI `aws backup start-restore-job` or AWS SDKs which introduces other issues when it comes to tracking the correct Terraform state which would have to be handled separately.

## Additional context
I can imagine that most of things in here are based off [restore-db-instance-to-point-in-time](https://docs.aws.amazon.com/cli/latest/reference/rds/restore-db-instance-to-point-in-time.html) which allow working with continuous backups while the feature I am describing is basing off [start-restore-job](https://docs.aws.amazon.com/cli/latest/reference/backup/start-restore-job.html) which might at this point make things undoable at this point already.

**Comment by cl0udf0x** [comment]
@grzegorz-kulis [This issue was resolved in version 4.3.0](https://github.com/terraform-aws-modules/terraform-aws-rds/issues/397).

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L114

**Comment by grzegorz-kulis** [comment]
@cl0udf0x Unfortunately, none of the available fields `source_db_instance_automated_backups_arn`, `source_db_instance_identifier`, `source_dbi_resource_id` are accepting the arn I have mentioned in my initial message which is `arn:aws:backup:eu-west-1:***********:recovery-point:continuous:db-**************-**********`. If you were to insert it into any of these fields you would get an error while applying terraform plan.

**Comment by grzegorz-kulis** [comment]
Is there any update?
