### ISSUE TITLE
final_snapshot_identifier has bad default

### ISSUE THREAD

**Issue by bdirito** [terraform-aws-modules/terraform-aws-rds#57]
./modules/db_instance/variables.tf final_snapshot_identifier is defined as
```
variable "final_snapshot_identifier" {
  description = "The name of your final DB snapshot when this DB instance is deleted."
  default     = false
}
```
According to terraform docs `false` will convert to the string `0`
https://www.terraform.io/docs/configuration/variables.html

Thus we are trying to to have a final snapshot with an identifier of 0. This however produces 
```
* aws_db_instance.this: InvalidParameterValue: The parameter FinalDBSnapshotIdentifier is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
```

**Comment by antonbabenko** [comment]
I think you are right, I can't find a reason why there is `false` by default, should be `""`. PR is welcome.

**Comment by ozbillwang** [comment]
Seems no one cares this issue.

I am looking for another issues and solution about `final_snapshot_identifier`, but get this issue, I am  fine to help to raise this PR.

**Comment by bryantbiggs** [comment]
this was changed to `null` on #126
