### ISSUE TITLE
Replace subnet group when VPC changes

### ISSUE THREAD

**Issue by tculp** [terraform-aws-modules/terraform-aws-rds#575]
## Is your request related to a problem? Please describe.
Subnet groups will try to update in-place when the subnets change. Unfortunately, this is the case even when the new subnets are in a different VPC, in which case the group needs to be replaced.

## Describe the solution you'd like.
When the subnets are in a different VPC the subnet group should be replaced instead of updated in-place

## Describe alternatives you've considered.
Manually deleting or tainting the subnet group to force recreation

## Additional context
The lifecycle.replace_triggered_by could be used to check the VPC ID that the first subnet belongs to and replace the resource if the VPC has changed

**Comment by bryantbiggs** [comment]
this is a provider level issue, not a module level issue - please open an issue on the provider for this

**Comment by tculp** [comment]
While it would be great if the provider was able to handle this case, this module would still be able to work around the issue with a new data source

```
data "aws_subnet" "selected" {
  id = var.subnets[0]
}

...

lifecycle {
  replace_triggered_by = [data.aws_subnet.selected.vpc_id]
}
```

**Comment by tculp** [comment]
Related: https://github.com/hashicorp/terraform-provider-aws/issues/17383

Since this issue has had no progress in over 3 years, I think working around it at the module level makes sense

**Comment by bryantbiggs** [comment]
>  I think working around it at the module level makes sense

maybe to you, but not to us maintainers 😬
