### ISSUE TITLE
Add a failover example?

### ISSUE THREAD

**Issue by andig** [terraform-aws-modules/terraform-aws-rds#60]
I understand that AWS Aurora supports DB clusters- which are not part of this module. With "plain" MySQL it should still be possible to create a Multi-AZ deployment (I assume using read replicas?).

An example for such a setup would be highly appreciated.

**Comment by antonbabenko** [comment]
AWS RDS has a concept [Multi-AZ](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html) which can be enabled by specifying `multi_az = true` as an argument to this module.

See an example in [usage section](https://github.com/terraform-aws-modules/terraform-aws-rds#usage) and put `multi_az = true` there.
