### ISSUE TITLE
Module tries to create db_option_group for postgres

### ISSUE THREAD

**Issue by artursmet** [terraform-aws-modules/terraform-aws-rds#62]
After update to the latest version of this module (`v1.17.0`), it tries to create `db_option_group` for postgresql engine. But this operation is not supported by the AWS API: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithOptionGroups.html

Applying the changes required by the update ends with infinite loop of:

```
module.postgres_db.db_option_group.aws_db_option_group.this: Still creating... (30m10s elapsed)
```

The issue can be resolved by disabling option_group creation: 
```
create_db_option_group = false
```

I think that the module should contain some logic that would know that option groups are not supported for Postgres engine. 

What do you think?

**Comment by antonbabenko** [comment]
Thanks for opening this issue. I didn't know that Postgres does not have option groups, I will issue a fix now.

**Comment by antonbabenko** [comment]
[v1.18.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v1.18.0) has been released.

**Comment by artursmet** [comment]
Thank you for very fast response :)

**Comment by abeluck** [comment]
This issue has resurfaced.

The default variable value for `create_db_option_group` is true, so if I do not use `create_db_option_group = false` myself, `local.enable_create_db_option_group` will always be true. See this line:  https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/main.tf#L9

The check for postgres should happen in an outer conditional
