### ISSUE TITLE
Issues passing option group options requiring settings

### ISSUE THREAD

**Issue by tfuser9** [terraform-aws-modules/terraform-aws-rds#63]
Samples in the readme include items such as:

options = [
    {
      option_name = "MARIADB_AUDIT_PLUGIN"
    }
  ]

For options requiring settings related to the option name, attempting a number of combinations such as this fail:

 options = [
   {
    option_name = "SQLSERVER_BACKUP_RESTORE"
       option_settings {
       name = "IAM_ROLE_ARN"
       value = "${aws_iam_role.database_role.arn}"
     }
   }
]

results in:
Error: module.database.module.db_option_group.aws_db_option_group.this: "option.0.option_name": required field is not set

The above example was formatted in the same manner used for aws_db_option_group resources. Is there another format in which they should be used with the terraform-aws-rds module? perhaps an item for the readme or one/some of the examples provided.

**Comment by antonbabenko** [comment]
I have updated example and README to show complete example - see [this commit](https://github.com/terraform-aws-modules/terraform-aws-rds/commit/f6af441e431ab6f04e7df4ea7c31173b4eaf4d72)

**Comment by jeremy-balmos** [comment]
I still get the same error when I try to pass in an ARN  with v1.28.0

options = [
    {
      option_name = "SQLSERVER_BACKUP_RESTORE"
      option_settings = [
        {
          name  = "IAM_ROLE_ARN"
          value = "${data.terraform_remote_state.database_management.this_sql_backup_role_arn}"
        },
      ]
    },
  ]

**Comment by eangeeag** [comment]
Experience the exact same issue as @jeremy-balmos.

This fails with error `module.bike_db.module.db_option_group.aws_db_option_group.this: "option.0.option_name": required field is not set`

```
options = [
    {
      option_name = "SQLSERVER_BACKUP_RESTORE"

      option_settings = [
        {
          name  = "IAM_ROLE_ARN"
          value = "${module.iam.rds_s3_integration_role_arn}"
        },
      ]
    },
  ]
```

On the other hand passing the hard-coded ARN in the value lets me run the plan successfully. This issue should be reopened.
