### ISSUE TITLE
Unable to login to MySQL Database

### ISSUE THREAD

**Issue by foreverXZC** [terraform-aws-modules/terraform-aws-rds#66]
This module seems really convenient for us to deploy a database on AWS. However, after I deploy a MySQL Database and try to login using MySQL Workbench, the connection failed.

I used code from following link and did not modify anything.
https://github.com/terraform-aws-modules/terraform-aws-rds/tree/v1.19.0/examples/complete-mysql

By contrast, if I follow the official guide, everything seems correct.
https://aws.amazon.com/getting-started/tutorials/create-mysql-db/

When I compare these two databases, I found that security groups are different. I wonder whether it causes the problem I met, or if I used this module incorrectly. Thanks a lot!

**Comment by foreverXZC** [comment]
For `main.tf`, I only changed `source = "../.."` to `source = "terraform-aws-modules/rds/aws"` and did not modify anything else. Also when I would like to connect to database, I have checked my username and password and guarantee all of them are correct. However, besides MySQL workbench, even if I use command line, which is something like `mysql -h <host> -u <username> -p`, the connection still fails...

**Comment by agomezvidalee** [comment]
So, 2 security groups are in play. One is provided by you into this imput:
vpc_security_group_ids
the other is the db security group. Try to align one or other following this instructions: https://aws.amazon.com/premiumsupport/knowledge-center/connect-rds-mysql-workbench/

Once you fixed it by hand you can come back to module tf files for a better understanding

**Comment by foreverXZC** [comment]
Thanks for reply. Did you mean that besides rds module, we still have to introduce another resource aws_db_security_group or something else? If yes, could you provide a more detailed example?

These links are pretty useful and informative. However, all of them do not meet my requirement and thus do not solve the problem that connection fails. I am sure that I can use MySQL Workbench to connect to the database I created using AWS Console, but not this terraform code. I am looking forward to a better solution. Thank you so much!

**Comment by agomezvidalee** [comment]
Hi, About "vpc_security_group_ids" you can found an exemaple into:
https://github.com/terraform-aws-modules/terraform-aws-rds/blob/f6af441e431ab6f04e7df4ea7c31173b4eaf4d72/README.md

As this tf module creates a plain MySQL RDS; you should jump into the MySQL administration itself in order to get access, so one thing is to get connectivity (related with AWS infrastructure) and another thing is how to connect to a MySQL, just related with MySQL behavior/setting.
