### ISSUE TITLE
vpc_security_group_ids reverts to VPC default SG

### ISSUE THREAD

**Issue by mr-smithers-excellent** [terraform-aws-modules/terraform-aws-rds#68]
If I specify an already-existing security group id (below) the RDS instance seems to ignore and reverts to the default VPC Security Group.

```
module "db" {
  vpc_security_group_ids = ["sg-123456"]
}
```

**Comment by mr-smithers-excellent** [comment]
Was able to get this working ultimately, turns out I wasn't patient enough.  It first applies the default SG, then changes to one you've specified after initialization.

**Comment by bascht** [comment]
@mr-smithers-excellent Excuse me if I drop in, but are you sure that this issue resolved itself? I'm currently trying to create an instance in a VPC created by https://github.com/terraform-aws-modules/terraform-aws-vpc and with security groups created by https://github.com/terraform-aws-modules/terraform-aws-vpc and running into the same issues as you.

I have set both subnet and vpc security group like

```terraform
  subnet_ids             = ["${module.vpc.database_subnets}"]
  create_db_subnet_group = false

  vpc_security_group_ids = ["${module.db_sg.this_security_group_id}"]°
```

and it looks like terraform is still creating the RDS instance in my default VPC:

```
module.example.module.db.module.db_instance.aws_db_instance.this: Creating...
  address:                             "" => "<computed>"
  allocated_storage:                   "" => "5"
  allow_major_version_upgrade:         "" => "false"
  apply_immediately:                   "" => "false"
  arn:                                 "" => "<computed>"
  auto_minor_version_upgrade:          "" => "true"
  availability_zone:                   "" => "<computed>"
  backup_retention_period:             "" => "1"
  backup_window:                       "" => "03:00-06:00"
  ca_cert_identifier:                  "" => "<computed>"
  character_set_name:                  "" => "<computed>"
  copy_tags_to_snapshot:               "" => "false"
  db_subnet_group_name:                "" => "<computed>"
  endpoint:                            "" => "<computed>"
  engine:                              "" => "mysql"
  engine_version:                      "" => "5.7.19"
  final_snapshot_identifier:           "" => "demodb"
  hosted_zone_id:                      "" => "<computed>"
  iam_database_authentication_enabled: "" => "false"
  identifier:                          "" => "demodb"
  identifier_prefix:                   "" => "<computed>"
  instance_class:                      "" => "db.t2.small"
  iops:                                "" => "0"
  kms_key_id:                          "" => "<computed>"
  license_model:                       "" => "<computed>"
  maintenance_window:                  "" => "mon:00:00-mon:03:00"
  monitoring_interval:                 "" => "0"
  monitoring_role_arn:                 "" => "<computed>"
  multi_az:                            "" => "false"
  name:                                "" => "demodb"
  option_group_name:                   "" => "demodb-20180806163832112100000001"
  parameter_group_name:                "" => "demodb-20180806163832112200000002"
  password:                            "<sensitive>" => "<sensitive>"
  port:                                "" => "3306"
  publicly_accessible:                 "" => "false"
  replicas.#:                          "" => "<computed>"
  resource_id:                         "" => "<computed>"
  skip_final_snapshot:                 "" => "true"
  status:                              "" => "<computed>"
  storage_encrypted:                   "" => "false"
  storage_type:                        "" => "gp2"
  tags.%:                              "" => "3"
  tags.Environment:                    "" => "dev"
  tags.Name:                           "" => "demodb"
  tags.Owner:                          "" => "user"
  timezone:                            "" => "<computed>"
  username:                            "" => "user"
  vpc_security_group_ids.#:            "" => "1"
  vpc_security_group_ids.995888166:    "" => "sg-123456"

Error: Error applying plan:

1 error(s) occurred:

* module.example.module.db.module.db_instance.aws_db_instance.this: 1 error(s) occurred:

* aws_db_instance.this: Error creating DB Instance: InvalidParameterCombination:
        The DB instance and EC2 security group are in different VPCs. The DB
        instance is in vpc-aaaaaa and the EC2 security group is in
        vpc-bbbbbbb status code: 400, request id: …

```

(vpc-aaaaaa being the default VPC and vpc-bbbbbb the one I want it to be in)

**Comment by agomezvidalee** [comment]
I faced a similar problem on RDS side ( using the rds modul). It was related with the behavior when some parameters was not set properly. Hope it helps.

**Comment by bascht** [comment]
I might have found a workaround for me. I tried to use the db subnet groups that the vpc module created via it's `database_subnets` parameter and that didn't work.

If I let the RDS module create it's own subnets everything is fine:

```terraform
  # subnet group
  subnet_ids             = ["${module.vpc.database_subnets}"]
  create_db_subnet_group = true
  vpc_security_group_ids = ["${module.db_sg.this_security_group_id}"]
```

**Comment by adecchi-2inno** [comment]
I have the same issue, When I configured the **subnet_ids**, **vpc_security_group_ids** and **availability_zone** from the region where I want to replicate the Oracle RDS, but I get:
`Error: Error creating DB Instance: InvalidParameterCombination: The DB instance and EC2 security group are in different VPCs. The DB instance is in vpc-XXXXXX and the EC2 security group is in vpc-YYYY
	status code: 400, request id: X`
I want the RDS replica in the VPC that I created, not in the default vpc.
@agomezvidalee what parameters did you set properly ?

**Comment by blacktoothgr1n** [comment]
I just hit same issue with the rds module against mariadb, default VPC deleted (as part of our standard practice) as TF is used to create the VPC I want RDS to live in. I tried to create the db_subnet_group separately but get same error as @adecchi-2inno about RDS and SG's in different VPC's. I finally found the answer at the link below, but in case the link is unavailable, try setting this property in the rds module:

cross_region_replica = true

If I let it create the db_subnet_group itself it was giving me this error (no default VPC present):
Error: Error creating DB Instance: InvalidSubnet: No default subnet detected in VPC. Please contact AWS Support to recreate default Subnets

I'm still verifying different combinations but with the param above it seems to work if I create the resource "aws_db_subnet_group" separately, tell the rds module:

`
create_db_subnet_group                  = false
`
`
db_subnet_group_name                   = aws_db_subnet_group.my-db-subnet-group.name
`

(I'm not showing the TF for my aws_db_subnet_group, it's standard issue nothing special, just subnets from the VPC I want)

To be clear, I didn't need multi-az or cross-region, I just needed a single AZ RDS instance in the VPC of my choice that I also created in TF.

Link that solved this for me:

[https://stackoverflow.com/questions/69125316/rds-replica-error-when-creating-in-different-vpc-with-terraform-failing/69770991#69770991](url)
