### ISSUE TITLE
Cannot modify existing RDS instance

### ISSUE THREAD

**Issue by pydo** [terraform-aws-modules/terraform-aws-rds#69]
**Description**
Applying the `multi_az` setting on an existing RDS instance does not work.

**Procedure**
1. Create a mysql instance using the following code:
```
module "db" {
  source = "terraform-aws-modules/rds/aws"
  identifier = "somedb"

  engine            = "mysql"
  engine_version    = "5.6.27"
  instance_class    = "db.t2.small"
  allocated_storage = 20
  storage_encrypted = false

  maintenance_window = "Mon:00:00-Mon:03:00"
  backup_window      = "03:00-06:00"

  backup_retention_period = 0


  family = "mysql5.6"
  major_engine_version = "5.6"

  name     = "somedb"
  username = "${var.mysql_username}"
  password = "${var.mysql_password}"
  port     = "3306"

  subnet_ids = "${data.terraform_remote_state.shared_resources.private_subnets}"
  vpc_security_group_ids =  ["${data.aws_security_group.default.id}"]

  tags = {
    Terraform = "true"
    Environment = "${terraform.workspace}"
  }
}
```
2. `terraform plan && terraform apply`
3. Modify the existing resource:
```
module "db" {
  source = "terraform-aws-modules/rds/aws"
  identifier = "somedb"

  engine            = "mysql"
  engine_version    = "5.6.27"
  instance_class    = "db.t2.small"
  allocated_storage = 20
  storage_encrypted = false

  maintenance_window = "Mon:00:00-Mon:03:00"
  backup_window      = "03:00-06:00"

  backup_retention_period = 7
  multi_az = true


  family = "mysql5.6"
  major_engine_version = "5.6"

  name     = "somedb"
  username = "${var.mysql_username}"
  password = "${var.mysql_password}"
  port     = "3306"

  subnet_ids = "${data.terraform_remote_state.shared_resources.private_subnets}"
  vpc_security_group_ids =  ["${data.aws_security_group.default.id}"]

  tags = {
    Terraform = "true"
    Environment = "${terraform.workspace}"
  }
}
```
4. repeat step 2

**Expected behavior**
The DB has `multi_az` enabled.

**Actual behavior**
`multi_az` is still disabled even though terraform reported that the command executed successfully

**Comment by antonbabenko** [comment]
Hi @pydo !

Once you specify `multy_az = true` or some other changes to an RDS instance AWS schedules these changes to be applied during next maintenance window (see `maintenance_window` argument). You can see this in the AWS console if you look at DB instance details:
```
Pending Modifications
Multi-AZ: Yes
```

In order to apply changes immediately you need to specify `apply_immediately = true` (see [variables.tf](https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/variables.tf#L148-L151)) and after few minutes DB instance will become multi-AZ ready.
