### ISSUE TITLE
Support for enabled_cloudwatch_logs_exports

### ISSUE THREAD

**Issue by marcincubernews** [terraform-aws-modules/terraform-aws-rds#70]
Feature to enable:
**enabled_cloudwatch_logs_exports** - (Optional) Name list of enable log type for exporting to cloudwatch logs. If omitted, any logs will not be exported to cloudwatch logs. Either of the following is supported: audit, error, general, slowquery.

[db_instance docs](https://www.terraform.io/docs/providers/aws/r/db_instance.html) 

Can I expect this coming anytime soon?

**Comment by antonbabenko** [comment]
Done.

[v1.21.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v1.21.0) has been released.
