### ISSUE TITLE
Facing problem After creating rds with snapshot.

### ISSUE THREAD

**Issue by sagar-babar** [terraform-aws-modules/terraform-aws-rds#72]
After terraform apply with snapshot, when I am doing terraform plan for second time its giving below error
* module.rds_xyz.module.db.module.db_instance.local.this_db_instance_password: local.this_db_instance_password: Resource 'aws_db_instance.this' does not have attribute 'password' for variable 'aws_db_instance.this.*.password'

Note: I am passing username and password blank, as I am restoring it

**Comment by sagar-babar** [comment]
Without parameter it will not accept it

**Comment by antonbabenko** [comment]
@sagar-babar Thanks for raising this issue.

In Terraform 0.11 it is not possible to make arguments optional based on whether it is restoring or creating a database, so you have to pass a password always (it can be random one for the restoration).
