### ISSUE TITLE
db option group not supported for sqlserver-se engine

### ISSUE THREAD

**Issue by tomyan** [terraform-aws-modules/terraform-aws-rds#75]
We just hit the same issue as #62, but where the engine is sqlserver-se - I guess this doesn't support db option groups either.

**Comment by merlincorey** [comment]
This issue also occurs with `sqlserver-ex`.

**Comment by bryantbiggs** [comment]
hi all, I believe this is now resolved with the latest version. if not, please feel free to open a new issue
