### ISSUE TITLE
Unable to destroy the RDS and the parameter_option_group during the same pipeline

### ISSUE THREAD

**Issue by idelkysq** [terraform-aws-modules/terraform-aws-rds#78]
Hello @antonbabenko,

While trying to destroy my RDS instance with terraform-destroy (using this template with modules), I'm getting errors as the db_parameter-group can't be deleted, it happens during the first time that I run terraform-destroy: "InvalidDBParameterGroupState: one or more database instances are still members of this parameter group". In this case, I checked and the rds instance is deleted and the db_option_group too.

When I tried for a second time, it's deleted without errors. I think there are dependencies issues and because the instance takes a long to be deleted, terraform doesn't realised that the rds is deleted when trying to delete the db_parameter group.

It could be possible to implement a wait condition between modules?

Thanks

**Comment by antonbabenko** [comment]
Hi @idelkysq !

There is no easy way to specify conditions between modules in Terraform 0.11 and rerun it the second time is sometimes the easiest solution (yes, it may be not optimal for some situations, I know).

**Comment by idelkysq** [comment]
Hi @antonbabenko 
Thanks very much for your reply! I'll keep running twice then! ;)

**Comment by asantos82** [comment]
@idelkysq 

Even going to AWS Console, and trying to delete the Option Group, when nothing is associated fails. You'll have to wait some time before being able to delete it

**Comment by bobchaos** [comment]
this is an AWS issue, RDS keeps a super-secret snapshot that you can't see or act upon, and those get cleaned up every 30mins or 1 hour, can't recall). Until the cleanup happens, the db_param group won't despawn (why those 2 things are tied together I don't know).

The only option available on TF side is to make it wait for some crazy amount of time like 1 hour before he declares failure, but that may not be desirable behavior either

**Comment by bryantbiggs** [comment]
hi all - closing this issue as its outside the scope of the module

**Comment by b-dean** [comment]
here's the related issue in the aws provider: https://github.com/hashicorp/terraform-provider-aws/issues/6448
