### ISSUE TITLE
output rds monitoring role arn if created for re-use

### ISSUE THREAD

**Issue by Ashtonian** [terraform-aws-modules/terraform-aws-rds#79]
Ff the module creates a role for monitoring, it would be nice to export the ARN so that it can be used in other db modules for example.

**Comment by SolidSly** [comment]
Cf #181

**Comment by antonbabenko** [comment]
Fixed in #181 and [v2.10.0](https://github.com/terraform-aws-modules/terraform-aws-rds/releases/v2.10.0) has been released.
