### ISSUE TITLE
invalid or unknown key: deletion_protection

### ISSUE THREAD

**Issue by idealhack** [terraform-aws-modules/terraform-aws-rds#86]
`terraform plan` will complain using `v1.22.0`:

`Error: module.my_rds_postgres.module.db_instance.aws_db_instance.this: : invalid or unknown key: deletion_protection`

but `v1.21.0` would pass without error.

**Comment by idealhack** [comment]
@antonbabenko I didn't notice that, and I've fixed it now. Thank you!

**Comment by Jyoti492** [comment]
even if I am using version > 1.39, it fails with same issue.

* provider.aws: version = "~> 1.59"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Jyotis-MacBook-Pro:terraform jyotisingh$ terraform plan

Error: provider.aws: : invalid or unknown key: access_secret_key

**Comment by antonbabenko** [comment]
@Jyoti492 Your problem is not related to the module but relates to AWS provider configuration. Follow instructions as described here - https://www.terraform.io/docs/providers/aws/index.html
