### ISSUE TITLE
sqlserver-ex database instances must have "null" name

### ISSUE THREAD

**Issue by merlincorey** [terraform-aws-modules/terraform-aws-rds#87]
The engine type `sqlserver-ex` only supports a single database and thus does not have a `DBName` (as reported by `terraform`) - that value must be null.

I was able to work around this issue by forking the module and commenting out the `name` in `resource "aws_db_instance" "this_mssql"` for now.

**Comment by merlincorey** [comment]
As long as the given module `name` is `""`, it will be accepted by an already existing database in the latest version.

As such, my issue is solved.

**Comment by remenaker** [comment]
For anyone that runs into this, I found that instead of using `name` you can use ` identifier` to name the instance. Not sure when this came about but it worked for me.
