### ISSUE TITLE
aws_db_subnet_group.this: value of 'count' cannot be computed

### ISSUE THREAD

**Issue by sunilkumarmohanty** [terraform-aws-modules/terraform-aws-rds#88]
Hi,

I created a VPC and database_subnet using
"terraform-aws-modules/vpc/aws" module.

Then, when I pass database_subnet_group  to "terraform-aws-modules/rds/aws" module, I get the error as

`aws_db_subnet_group.this: value of 'count' cannot be computed`

But, if I create the VPC first and then create the RDS, there is no issue.

**Comment by jvelasquezjs** [comment]
Hi @sunilkumarmohanty I am having the same problem. This issue is due to terraform not being able to know computed values in the count meta-parameter. This has been an issue for a long time. I will try to raise a PR for this issue and see how it goes.

**Comment by jvelasquezjs** [comment]
Same as #107
