### ISSUE TITLE
rds cluster support?

### ISSUE THREAD

**Issue by holms** [terraform-aws-modules/terraform-aws-rds#89]
Just wondering are there are any plans for rds cluster support? I'm not sure what's the point of single database instances, most of the time products requires to scale quite early so cluster is needed.

**Comment by max-rocket-internet** [comment]
> I'm not sure what's the point of single database instances

You can set `multi_az` to true and pass in mutiple `subnet_ids` to create a master with a read replica. This arrangement is not a `single` instance and is resilient with automatic failover.

Or perhaps you mean Amazon Aurora, which is more cluster like. But Aurora is a completely different AWS service, with a different API and different TF resources. So is not something that could be supported by this module. There is however, another TF module for Aurora [here](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora), but development there is very slow.

Hope that helps!

**Comment by holms** [comment]
Thank you Max for detailed explanation. Maybe then db instances will be
fine as long as it can do replicas

**Comment by holms** [comment]
I'm actually still wondering about this. There's `resource "aws_rds_cluster"` available. I have a need to make more nodes just for writing.

**Comment by max-rocket-internet** [comment]
`aws_rds_cluster` is a resource that is part of Aurora. This is covered in a different module as Aurora and regular RDS are completely different: https://github.com/terraform-aws-modules/terraform-aws-rds-aurora

> I have a need to make more nodes just for writing

I don't think multi-master (multiple `WRITER` nodes) is possible in Aurora or RDS.

**Comment by holms** [comment]
Oh thanks for link. But how do you scale writers then? I need more resources for write then for read. There's importer in here which takes tons of resources on INSERT's

**Comment by max-rocket-internet** [comment]
Then resize the instance to a larger size. For example going from `db.m4.large` to `db.m4.2xlarge`.

**Comment by holms** [comment]
I'm talking about horizontal scaling, how can one have 1000 of writers..? How do you scale writing operations in postgresql cluster :)?

**Comment by holms** [comment]
Ok found it, using shards. Just now really wondering what's a so big difference to use postgresql aurora vs db instances. People just need a database cluster.
