### ISSUE TITLE
Unable to specify option settings using remote variables

### ISSUE THREAD

**Issue by audiolomb** [terraform-aws-modules/terraform-aws-rds#92]
I am trying to create a db instance using the following options:

```options = [
    {
      option_name = "SQLSERVER_BACKUP_RESTORE"

      option_settings = [
        {
          name = "IAM_ROLE_ARN"

          value = "${data.terraform_remote_state.vpc.RdsBackupOption}"
        },
      ]
    },
  ]
```

The remote variable in Value is referenced correctly (I can use it as an output and see it just fine).
If I substitute the value field with a local variable or the direct value everything works.

Thank you,
Claudio

**Comment by shushry** [comment]
I'm experiencing the same issue.  Probably similar to above, I'm creating a role, and trying to populate the option_setting with the ARN from that role.

**Comment by bryantbiggs** [comment]
hi all, this sounds like a dependency issue. local variables can be used to ensure lookups are performed ahead of passing to the module config if this issue still persists in the later versions of Terraform and the AWS provider
