### ISSUE TITLE
v 1.22.0 never returns when creating  aws_db_option_group

### ISSUE THREAD

**Issue by horsey** [terraform-aws-modules/terraform-aws-rds#93]
Hello @antonbabenko 
v 1.22.0 does not return when creating the resource `aws_db_option_group`. 
I don't create this resource explicitly; it is called from the main module.  The message is when I run ```terraform apply```:

```module.production.db.db_option_group.aws_db_option_group.this: Still creating... (8m40s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still creating... (8m50s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still creating... (9m0s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still creating... (9m10s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still creating... (9m20s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still creating... (9m30s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still creating... (9m40s elapsed)
```

```terraform apply``` does not return after this.

**Comment by dpiddockcmp** [comment]
Hi @horsey.

You *have* to set `major_engine_version` to a valid value for the object group creation to work otherwise terraform waits until timeout. Maybe it's a terraform-aws-provider or AWS bug that this is not immediately rejected?

Or set `create_db_option_group = false` and get the default option group for your DB engine.

**Comment by seanscottking** [comment]
Coincidentally I'm dealing with the same problem this morning and I found that it's because an Options Group name "Must not end with a hyphen", but v1.22.0 (possibly other versions also) define it this way `name_prefix = "${var.identifier}-"` <-- see the hyphen? This should not have passed any testing even with the most basic usage of this module. Why are we tagging the hyphen on the end anyhow?

**Comment by dpiddockcmp** [comment]
It's a name prefix. Terraform will append a long value to the end. Each time the resource needs to be recreated it will be given a unique name to avoid conflicts.

`name_prefix = "mydb-"` would become something like `mydb-20181019080801873100000001` when created

https://www.terraform.io/docs/providers/aws/r/db_option_group.html#name_prefix

**Comment by seanscottking** [comment]
Nice, I've never seen that before. It's only available on a limited number of resources. I wonder why.

So, my previous theory as to why @horsey and myself are having issues is very incorrect. The requirement for the option group name `Must not end with a hyphen` is of course a true statement as per AWS's API docs, but `terraform plan` showing the line `name_prefix: "" => "MyApp-"` is not as it appears and it will actually tack a random string at the end of it so it looks like `MyApp--20181213170324554800000001`

It is still a mystery. I am fortunate that I do not need db_options_group support today so I will continue using a version tag from before it was added (v1.15.0 works for me), and when time allows I will come back and help troubleshoot this

**Comment by horsey** [comment]
> Hi @horsey.
> 
> You _have_ to set `major_engine_version` to a valid value for the object group creation to work otherwise terraform waits until timeout. Maybe it's a terraform-aws-provider or AWS bug that this is not immediately rejected?
> 
> Or set `create_db_option_group = false` and get the default option group for your DB engine.

Hi @dpiddockcmp, your solutions worked. But as you mentioned, instead of looping forever, the `terraform apply` command should reject or warn about this.

**Comment by antonbabenko** [comment]
If this is resolved then I am going to close this issue.

Thanks @dpiddockcmp for jumping and helping!

**Comment by horsey** [comment]
> Hi @dpiddockcmp, your solutions worked. But as you mentioned, instead of looping forever, the `terraform apply` command should reject or warn about this.

@antonbabenko  Don't you think the issue of `terraform apply` command 's  ability reject or warn if some option is mandatory, and not going to a loop is required?

**Comment by antonbabenko** [comment]
Unfortunately, this is not an easy thing to do universally nor common practice (we let terraform to validate something and let AWS validate some more and fail, if necessary). This module can create resources conditionally, so we have to have a lot of values with default values set to empty.

**Comment by horsey** [comment]
I have to continue this thread as I think this is odd behaviour and is related to the `create_db_option_group`: when I destroy the Terraform blueprint, the  db_option_group resource does  not get deleted and goes to an infinite loop. 

```
module.production.db.db_option_group.aws_db_option_group.this: Still destroying... (ID: xxxx-database-testy1-20181214100612824100000002, 12m40s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still destroying... (ID: xxxx-database-testy1-20181214100612824100000002, 12m50s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still destroying... (ID: xxxx-database-testy1-20181214100612824100000002, 13m0s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still destroying... (ID: xxxx-database-testy1-20181214100612824100000002, 13m10s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still destroying... (ID: xxxx-database-testy1-20181214100612824100000002, 13m20s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still destroying... (ID:xxxx-database-testy1-20181214100612824100000002, 13m30s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still destroying... (ID: xxxx-database-testy1-20181214100612824100000002, 13m40s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still destroying... (ID: xxxx-database-testy1-20181214100612824100000002, 13m50s elapsed)
module.production.db.db_option_group.aws_db_option_group.this: Still destroying... (ID: xxxx-database-testy1-20181214100612824100000002, 14m0s elapsed)
```

I am not saying there is a problem with this module, but I think the behaviour is odd. Can anyone else confirm this behavior?

**Comment by horsey** [comment]
This one looks relevant: https://github.com/terraform-providers/terraform-provider-aws/issues/4597
