### ISSUE TITLE
Flatten the Terraform code/refactor the module directory

### ISSUE THREAD

**Issue by skang0601** [terraform-aws-modules/terraform-aws-rds#95]
Hey there I see that this Terraform module uses the pattern of defining submodules within this modules to help organize and encapsulate the code. In my opinion, this tends to do more harm than good in the long run especially when trying to suss out plan outputs, creates confusion when making future modifications in this project, and tends to obscure where certain variable values are getting used. In fact, a really painful point is whenever you need to do targeted applies, the submodules makes this unnecessarily verbose and not intuitive.
If you're open to such a change I am willing to do this refactor to flatten out the Terraform code in this module.

**Comment by antonbabenko** [comment]
The point of decomposition into smaller submodules is that it makes it possible to use them either separately and all-at-once.

Normally, most users use the root module, which calls submodules.

Making targeted applies and refactoring is no different than if it would be in a single module.

There is no need to refactor this module by flattening it out.

Closing this issue.
