### ISSUE TITLE
Prominently document what engine(s) are not supported by this module

### ISSUE THREAD

**Issue by mungoknotwise** [terraform-aws-modules/terraform-aws-rds#96]
I understand it is difficult to elegantly support both Aurora and vanilla MySQL. Some words to that effect on the main README page would be helpful. I wasted a couple of precious hours figuring this out, while reading that on the README page would have taken, oh, 30 seconds.

**Comment by bryantbiggs** [comment]
hi @mungoknotwise PRs are always welcome! I'm not sure what information you would like added to the README but please feel free to open a PR to help others
