### ISSUE TITLE
engine version is drafted 

### ISSUE THREAD

**Issue by ozbillwang** [terraform-aws-modules/terraform-aws-rds#97]
I need your suggestion to take care of this situation. 

As in example, I set the similar version number in my terraform codes:

      engine_version              = "5.7.17"

But after the database runs for a while, it get minor upgraded to higher version. Then terraform detected the change and try to roll it back to old version, which is wrong. 

I tried with short version as `5.7`, seems it works, but need confirm if this is the best way I can do. 

If we set to `5.7` more than with minor version, then if someone doesn't allow minor upgrade, what will happen? Which db version will be deployed.

**Comment by antonbabenko** [comment]
Good point, Bill, I have fixed examples to use the latest version.

**Comment by ozbillwang** [comment]
Thanks, @antonbabenko 

Could you please point me out which commit you did for this fix? I went through the commits on master branch, can't find it out.

**Comment by antonbabenko** [comment]
You are right, there is no short `5.7` in examples but they are working with `5.7.19`. I think this is the behavior we have to follow to avoid moving targets. Once the version is updated outside of Terraform, it has to be updated in the code also as well.
